Андрей Сало
urfu-2018/markup-task-1 pull request #10
Opened 2018-10-10 14:19 UTC by rockyraccoon64

2018-10-10 14:19 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 14:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 14:48 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 14:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 14:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 02:20 UTC, phwb requested changes

2018-10-11 02:20 UTC, phwb commented on index.html
> +			<h2>Хочу подписаться!</h2>
почему не h1?

2018-10-11 02:20 UTC, phwb commented on index.html
> +						<input id="emailInput" type="email" placeholder="email@yandex.ru" required><br>
лишний br

2018-10-11 02:22 UTC, phwb commented
🍅

2018-10-11 02:33 UTC, phwb reviewed
🍅

2018-10-11 02:33 UTC, phwb commented on index.html
> +					<p class="textInputParagraph">
почему все классы названы в `camelCase`? используй `text-input-paragraph`

2018-10-11 02:33 UTC, phwb commented on index.html
> +		<article id="subscribe">
зачем тут айдишник, старайся избегать их использования

2018-10-11 02:33 UTC, phwb commented on index.html
> +						<input id="nameInput" type="text" pattern="[А-Яа-яЁё]+" placeholder="Имя" required>
может вместо айдишника и атрибута `for` просто обернуть тег `input` в `label`

2018-10-11 02:33 UTC, phwb commented on index.html
> +					<label><input id="mailCheck" type="checkbox">на почту</label><br>
лишний айдишник

2018-10-11 02:33 UTC, phwb commented on index.html
> +		<article id="subscriptionLetter">
тоже не понятно зачем тут айдишник

2018-10-11 02:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 02:55 UTC, rockyraccoon64 commented
Всё исправил. Мне казалось, что id в полях формы нужны для того, чтобы различать введённые данные, когда они приходят на сервер.
Один вопрос - наверное, классы тоже не нужны, раз в этом задании всё равно не требуется делать CSS?

2018-10-11 04:33 UTC, phwb commented
> Мне казалось, что id в полях формы нужны для того, чтобы различать введённые данные, когда они приходят на сервер.

`id` идентифицирует уникальный элемент на странице. кстати ты правильно подметил, чтобы данные правильно ушли на сервер нужно о все инпуты добавить атрибут `name`. после сабмита из данных формы сформируется зарос вида:
```
name1=value1&name2=value2 и т.д.
```
так что добавь атрибут `name`

2018-10-11 04:36 UTC, phwb commented
> Один вопрос - наверное, классы тоже не нужны, раз в этом задании всё равно не требуется делать CSS?

лишними они точно не будут, раз уж все равно написал. кстати я первый раз тут выступаю ментором, где текст задания? 😀

2018-10-11 04:54 UTC, phwb commented on index.html
> +		<article>
семантически тут будет верно использование тега `main` вместо `article`

2018-10-11 04:54 UTC, phwb commented on index.html
> +				<section>
тут лучше использовать тег `div`

2018-10-11 04:54 UTC, phwb commented on index.html
> +				<p>
и тут тоже лучше использовать тег `div`

2018-10-11 04:54 UTC, phwb commented on index.html
> +		<article>
так как эта часть будет являться письмом, которое будут отображать почтовые клиенты, то верстку писем лучше делать с помощью таблиц

2018-10-11 04:54 UTC, phwb commented on index.html
> +		<article>
для полноты картины (если бы это было не письмо), то семантически тут лучше использовать следующую структуру:
```html
<article><!-- или section -->
  <header>
    <h1>Здравствуйте, подписчик!</h1>
  </header>
  <p>...</p>
  <footer>
    <p>...</p>
  </footer>
</article>
```

2018-10-11 15:25 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 15:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 15:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 15:35 UTC, rockyraccoon64 commented
Спасибо за советы! Всё исправил. К сожалению, при добавлении атрибута name у поля ввода телефона длина строки превысила максимально возможную (110), поэтому я вернул соответствующий label на отдельную строку.

2018-10-11 15:49 UTC, phwb approved these changes

2018-10-11 15:51 UTC, phwb commented on index.html
> +						<label for="tel-input">Телефон</label>
ну ты мог бы сделать вот так:
```html
<label>
  <input .../>
</label>
```

2018-10-11 15:54 UTC, phwb commented
и есть я все правильно понял ты же должен сверстать форму как в макете, со стилями

2018-10-12 02:14 UTC, rockyraccoon64 commented
Я тоже изначально так думал, но в Slack уточнили, что конкретно в этой задаче стили не требуются:
![default](https://user-images.githubusercontent.com/43612261/46843767-bf95aa00-cded-11e8-96c5-af0669ee3745.png)
У нас только вчера была первая лекция по CSS :smiley:

2018-10-12 02:30 UTC, phwb commented
🍏

2018-10-12 02:30 UTC, closed without merging