Базун Филипп
urfu-2018/markup-task-1 pull request #105
Opened 2018-10-14 15:37 UTC by Phil9l

2018-10-14 15:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 15:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 15:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 15:30 UTC, chrighter requested changes
🍅

2018-10-16 15:30 UTC, chrighter commented on index.html
> +                <input name="phone" placeholder="89990007766" type="tel" pattern="\+?\d{11}" required>
Давай тогда во всех `input` атрибуты с новой строки писать, чтобы было единообразно

2018-10-16 15:30 UTC, chrighter commented on index.html
> +        <table>
Молодец, что для вёрстки писем используешь табличную вёрстку, это правильный подход! 👍

2018-10-16 15:30 UTC, chrighter commented on index.html
> +            <tfoot>
👍 за `tbody` и `tfoot`

2018-10-16 15:30 UTC, chrighter commented on index.html
> +                        <img
Давай будем располагать картинку как в макете - на одном уровне с первым и вторым абзацем, а не со вторым и третьим

2018-10-16 15:30 UTC, chrighter commented on index.html
> +            <label>Ваше имя: <input name="name" placeholder="Имя" required></label><br>
👍 за `required`

2018-10-16 15:30 UTC, chrighter commented on index.html
> +                            email и на указанный вами телефон &mdash;<br>
👍 за `&mdash;`

2018-10-16 15:30 UTC, chrighter commented on index.html
> +            <label><input type="checkbox" name="phone-notifications">Телефон</label><br>
Круто, что галочка в `checkbox` ставится даже если на текст нажимать!
Это удобно, например когда заполняешь форму с мобильного

2018-10-16 16:04 UTC, Phil9l commented on index.html
> +                <input name="phone" placeholder="89990007766" type="tel" pattern="\+?\d{11}" required>
Прямо во всех? В телефоне ещё понятно, зачем это, но в каком-нибудь `<input type="submit" value="Подписаться">` и чекбоксах выглядит не очень оправдано. Там правда это нужно?

2018-10-16 16:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-16 17:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 16:01 UTC, chrighter approved these changes
🍏 

На будущее: можно было так же расположить картинку с помощью атрибутов ячеек таблицы. Почитай про `colspan` и `rowspan`

2018-10-17 16:01 UTC, closed without merging