Немцев Евгений
urfu-2018/markup-task-1 pull request #106
Opened 2018-10-14 15:56 UTC by nevpont

2018-10-14 15:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-15 11:48 UTC, nex2hex requested changes
🍅

2018-10-15 11:48 UTC, nex2hex commented on index.html
> +                <td>Ваше имя</td>
Текст "Ваше имя" должен быть внутри label, чтобы при клике по нему курсор помещался в поле ввода

2018-10-15 11:48 UTC, nex2hex commented on index.html
> +        <input type="checkbox">на почту<br>
тут тоже самое

2018-10-15 11:48 UTC, nex2hex commented on index.html
> +        <button>Подписаться</button><br>
`type="submit"`

2018-10-15 11:48 UTC, nex2hex commented on index.html
> +        <tr>
можно tfoot

2018-10-22 18:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 21:25 UTC, closed without merging