Шарифянов Тимур
urfu-2018/markup-task-1 pull request #11
Opened 2018-10-10 14:42 UTC by Scvairy

2018-10-10 14:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-15 08:58 UTC, Scvairy commented
🔔 Тут проверка будет? Или закрытие pull request? А то я волнуюсь :D

2018-10-16 06:31 UTC, dotokoto requested changes

2018-10-16 06:31 UTC, Dotokoto commented on index.html
> +    <div id="subscribe">
Можно использовать здесь `<section>`

2018-10-16 06:31 UTC, Dotokoto commented on index.html
> +                <input id="phone" type="tel" placeholder="89990007766" pattern="\s*([\d+ ()-]{0,18})\s*">
<img width="659" alt="2018-10-16 11-25-44" src="https://user-images.githubusercontent.com/8973726/46996480-40c6a700-d136-11e8-83fe-4502e3617974.png">
Вот такой телефон тоже считается валидным ) Задача конечно не про регулярку, но если хочешь, можешь еще над ней поработать

2018-10-16 06:31 UTC, Dotokoto commented on index.html
> +            <p>
Это не похоже на просто абзац текста, скорее отдельный блок с настройками подписки

2018-10-16 06:31 UTC, Dotokoto commented on index.html
> +                <span>
Это список настроек, а не просто текст. Можно сделать семантичнее

2018-10-16 06:31 UTC, Dotokoto commented on index.html
> +    <div>
Тоже можно добавить семантики, это отдельный блок страницы - письмо. Используй `section` или `article`

2018-10-16 19:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 19:27 UTC, Scvairy commented
🍏

2018-10-17 08:07 UTC, Scvairy reviewed
Исправил

2018-10-19 09:51 UTC, Dotokoto commented on index.html
> +                    <input id="email" type="email" placeholder="email@yandex.ru">
Почему поле email не обязательно, как без него рассылку слать? )

2018-10-19 09:51 UTC, closed without merging