Дмитриев Виталий
urfu-2018/markup-task-1 pull request #115
Opened 2018-10-14 17:07 UTC by VitaliyDm

2018-10-14 17:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 17:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 17:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 17:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 17:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 17:45 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 18:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 20:25 UTC, SemyonMakhaev requested changes
🍅 

Виталий, здравствуй! Спасибо за пулл реквест. Вёрстка семантичная, молодец 👍 
Есть несколько правок. Если будут вопросы, пиши мне в слаке

2018-10-14 20:25 UTC, SemyonMakhaev commented on index.html
> +                <br>уведомления на почту и телефон
Этот элемент `p` тоже относится к шапке страницы?

2018-10-14 20:25 UTC, SemyonMakhaev commented on index.html
> +                        <input id="name" placeholder="Имя">
Давай сделаем все поля для ввода обязательными для заполнения

2018-10-14 20:25 UTC, SemyonMakhaev commented on index.html
> +                        <input id="tel" placeholder="89990007766" type="tel" pattern="(?:[+]7|8)\d{10}">
Давай поддержим также городские (семизначные) номера телефонов

2018-10-14 20:25 UTC, SemyonMakhaev commented on index.html
> +                        <img
Для картинок нужно также обязательно всегда указывать атрибут [title](http://htmlbook.ru/html/attr/title). Это необходимо для обеспечения доступности

2018-10-14 20:25 UTC, SemyonMakhaev commented on index.html
> +            <table>
Табличная вёрстка используется в первую очередь для создания таблиц. Для создания интерфейсов с сетчатой структурой таблицы использовать не рекомендуется, лучше добиться того же эффекта при помощи стилей. Попробуй использовать более подходящие теги.

Хотя для обеспечения совместимости с очень старыми браузерами, где новые технологии не поддерживаются, табличная вёрстка используется в качестве альтернативы и по сей день 😅

2018-10-14 20:25 UTC, SemyonMakhaev commented
Отдельный респект, если добавишь стилей, чтобы интерфейс получился, как на макете 😃 

![2015_06_10_12_06_35_79b56615ad6b75a28352dc50425e6c19](https://user-images.githubusercontent.com/18099714/46916579-faf2cd00-cfd5-11e8-95c4-d7951f13b8ef.jpg)

2018-10-15 11:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 13:40 UTC, SemyonMakhaev approved these changes
🍏 

Молодец! Получилось очень близко к макету, и в коде css всё чисто

2018-10-20 13:40 UTC, SemyonMakhaev commented on index.html
> +                               type="tel" required pattern="((?:[+]7|8)\d{10}|\d{7})">
👍 👍 👍

2018-10-20 13:40 UTC, closed without merging