Мамонтова Анастасия
urfu-2018/markup-task-1 pull request #119
Opened 2018-10-14 17:52 UTC by NastyaMamontova

2018-10-14 17:53 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 18:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 20:23 UTC, spt30 requested changes
🍅Привет! Формально ты сдала задачу за 19 часов до дедлайна проверки тестами, + неделя на проверку ментором, соответственно дедлайн продлеваю на неделю и 19 часов с текущего момента: то бишь до 30 октября 20:00

Извиняюсь, что долго не проверял – много дел было

2018-10-22 20:23 UTC, spt30 commented on index.css
> +    font-family: Helvetica, Arial, sans-serif;
не критично, но обычно в другом порядке пишут
`Arial, Helvetica, sans-serif`

2018-10-22 20:23 UTC, spt30 commented on index.html
> +            <span>Ваше имя</span>
Лишние спанчики, достаточно просто в `<label>` обернуть текст и инпут

2018-10-22 20:23 UTC, spt30 commented on index.html
> +        <div class="form-field checkbox-input">
почему этот обернут список, а верхний – нет?
и `<div>` тут плохой тег, давай подберем что-то более семантичное?

2018-10-22 20:23 UTC, spt30 commented on index.html
> +        <img src="yandex-logo.svg" height="64" alt="Лого Яндекса">
раз у тебя есть css, давай ответственность за высоту передадим ему

2018-10-22 20:23 UTC, spt30 commented on index.html
> +    <footer>
формально тут 2 разных блока: форма подписки и письмо
поэтому футер здесь не совсем уместен: `<footer>` – это нижняя часть страницы, тут это просто хотя бы `<div>`

2018-10-22 20:23 UTC, spt30 commented on index.html
> +    <form>
Правильно выделила ту часть, где начинается форма, молодец!)

2018-10-22 20:23 UTC, spt30 commented on index.html
> +<section class="letter">
Странная логика: есть главная часть страницы (`<main>`), есть некоторая секция (секция чего)? И почему-то `<article>` как самостоятельная часть, которая может использоваться отдельно от письма

`<main>` – это все, кроме `<header>` и `<footer>`, т.к. здесь вообще не должно их быть, то давай все обернем в `<main>`
Далее, у тебя есть 2 самостоятельных по смыслу части (более того, у них есть заголовки), значит это точно два `<article>`

В первой части все правильно: заголовок, параграф и форма (реализация формы не имеет значения тут, пусть будут 2 семантичных тега и в них label, хотя я бы еще сделал два ненумерованных списка, но пусть так будет)

Во второй части что-то странное: 4 параграфа, которые равноправны между собой (хотя явно, как минимум, в письме должен быть заголовок), потом часть, которая не имеет отношения к контенту (можешь прочитать про этот тег https://webref.ru/html/figure) и в конце импровизированный футер письма
Логично было бы так: 2 секции письма, одна с заголовком, другая без, между ними картинка
Раз у тебя есть css, можно все разложить красиво и верстку семантичной сделать

2018-10-22 20:25 UTC, spt30 commented
Совсем забыл – раз у тебя тут есть css, неплохо было бы ограничить ширину блоков, чтобы было как на макете±

2018-12-15 08:12 UTC, closed without merging