Чернецов Александр
urfu-2018/markup-task-1 pull request #12
Opened 2018-10-10 16:23 UTC by Resinchen

2018-10-10 16:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 16:35 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 16:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 16:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 16:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 17:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 17:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 18:37 UTC, spt30 requested changes
Требования к задаче выполнены не полностью. Пожалуйста, выполни поставленные условия и пришли решение повторно.

Поосторожнее с выражениями, молодой человек: ```<form action="mailto:qwerty@hyandex.ru">```

2018-10-12 09:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-12 10:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 14:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 15:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 15:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 15:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 10:05 UTC, spt30 commented
🍅 Теперь давай сделаем так, чтобы было похоже на то, что есть на макете

2018-10-14 10:06 UTC, spt30 requested changes
🍅 Теперь давай сделаем так, чтобы было похоже на то, что есть на макете

UPD: извиняюсь за претензию, можно оставить внешний вид, как есть

2018-10-14 13:46 UTC, spt30 requested changes

2018-10-14 13:46 UTC, spt30 commented on index.html
> +            <div>
Постарайся избегать оборачивания в ```<div>``` всего, что можно
Есть другие теги
Тут можно вообще без обертки обойтись

2018-10-14 13:46 UTC, spt30 commented on index.html
> +    <title>Форма подписки</title>
Чем вызвана необходимость менять что-то здесь?

2018-10-14 13:46 UTC, spt30 commented on index.html
> +                <label>Ваше имя <input type="text" placeholder="Иван" name="fullname"></label>
Желательно разносить на несколько строчек, вроде того:
```
<label>
    Ваше имя
    <input type="text" placeholder="Иван" name="fullname">
</label>
```

2018-10-14 13:46 UTC, spt30 commented on index.html
> +                <p>Уведомления будут приходить вам на этот email и на указанный вами телефон.</p>
Не критично, но текст не соответствует тому, что на макете

2018-10-14 16:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 16:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 16:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 17:16 UTC, spt30 requested changes
🍅постарайся картинку вставить справа от текста, как на макете
любым способом

и еще одно маленькое замечание (наверху)

2018-10-14 17:16 UTC, spt30 commented on index.html
> +            <br>
тут ```<br>``` впилил
а в полях ввода данных не впилил, в итоге наверху все на одной строке оказалось после избавления от дивов

P.S. тут вкусовщина на самом деле, можешь вернуть див, можешь доставить br, просто див – это лишняя вложенность

2018-10-14 17:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 18:54 UTC, spt30 commented
🍏 Молодец!

2018-10-14 18:54 UTC, closed without merging