Лопатин Николай
urfu-2018/markup-task-1 pull request #121
Opened 2018-10-14 18:22 UTC by LopatinNikolai

[Посмотреть решение](https://hruview.herokuapp.com/LopatinNikolai/markup-task-1/master/index.html)

2018-10-14 18:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 18:31 UTC, chrighter requested changes
🍅

2018-10-19 18:31 UTC, chrighter commented on .editorconfig
> +root = true
Подскажи, пожалуйста, какой редактор кода ты используешь?

2018-10-19 18:31 UTC, chrighter commented on index.html
> +            <tr>
Давай вынесем контент в `tbody` и `tfoot` для семантичности

2018-10-19 18:31 UTC, chrighter commented on index.html
> +            <label for="mail"><input id="mail" type="checkbox" name="email">на почту</label>
Круто, что галочка в `checkbox` ставится даже по нажатию на текст 👍

2018-10-19 18:31 UTC, chrighter commented on index.html
> +            <label for="tel"><input id="tel" type="checkbox" name="tel">на телефон</label>
Но давай расположим `checkbox` как на макете - друг под другом

2018-10-19 18:31 UTC, chrighter commented on index.html
> +        <table>
Верстка письма таблицей - правильный подход, молодец! 🔥

2018-10-19 18:31 UTC, chrighter commented on index.html
> +                <td><img src="./1.jpg" alt="Яндекс"></td>
`alt` не совсем информативный

2018-10-19 18:31 UTC, chrighter commented on index.html
> +                <td>&copy; 2018, <a href="">Яндекс</a></td>
Давай сделаем ссылки `#`

2018-10-19 18:31 UTC, chrighter commented on index.html
> +            <p>Ваше имя <input placeholder="Имя" required type="text"></p>
👍 за `required`

2018-10-19 18:31 UTC, chrighter commented on index.html
> +            <p>Email <input placeholder="email@yandex.ru" required type="email" pattern="/@/"></p>
Точно верный `pattern` ?

2018-10-19 18:31 UTC, chrighter commented on index.html
> +                <td><img src="./1.jpg" alt="Яндекс"></td>
Давай будем располагать картинку как на макете - между первым и вторым абзацем

2018-10-19 18:31 UTC, chrighter commented on index.html
> +                    для подтверждения перейдите по <a href="">ссылке</a>
Для

2018-10-19 18:31 UTC, chrighter commented on index.html
> +            <input type="submit" value="Подписаться">
Давай кнопку тоже расположим как на макете

2018-10-19 18:41 UTC, LopatinNikolai commented on .editorconfig
> +root = true
vs code

2018-10-19 18:47 UTC, LopatinNikolai commented on index.html
> +                <td><img src="./1.jpg" alt="Яндекс"></td>
стили применять нельзя, атрибуты применять нельзя.

2018-10-19 19:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 12:27 UTC, LopatinNikolai commented on index.html
> +                <td><img src="./1.jpg" alt="Яндекс"></td>
как там дела ?

2018-12-15 08:12 UTC, closed without merging