firstTry
urfu-2018/markup-task-1 pull request #124
Opened 2018-10-14 19:03 UTC by Apforviolet

2018-10-14 19:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 19:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 19:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 20:02 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 20:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 20:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 20:30 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 20:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 20:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-15 07:57 UTC, nex2hex requested changes
🍅

2018-10-15 07:57 UTC, nex2hex commented on index.html
> +                 value="Phone">на телефон<br><br>
фразу "на телефон" надо поставить тоже внутрь label
тогда при клике на нее будет отмечаться чекбокс

2018-10-15 07:57 UTC, nex2hex commented on index.html
> +                <p><label for="First_name">Ваше имя:</label><input id="First_name"
тут p не нужен
проще делать так:
```
<label>Ваше имя:<input ...> </label>
```
тогда не надо будет писать id шники

2018-10-15 07:57 UTC, nex2hex commented on index.html
> +    <fieldset>
зачем тут fieldset? тут нет формы

2018-10-15 07:58 UTC, nex2hex commented
Еще не хватает валидации формы

2018-10-21 08:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 18:36 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-22 18:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-22 20:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 08:51 UTC, closed without merging

2018-10-23 08:52 UTC, nex2hex commented
Правки по задаче были заккомичены 21 октября