Заостровская Анастасия
urfu-2018/markup-task-1 pull request #13
Opened 2018-10-10 16:55 UTC by ZaoAsya

2018-10-10 16:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 17:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 17:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-13 13:24 UTC, chrighter requested changes

2018-10-13 13:24 UTC, chrighter commented on index.html
> +                <label>
Неправильная табуляция

2018-10-13 13:24 UTC, chrighter commented on index.html
> +            <h2><strong>Хочу подписаться!</strong></h2>
Почему используешь `h2`, хотя до этого не использовала еще `h1`?

Это можно вынести за пределы формы, так как к самой форме данный контент не относится

2018-10-13 13:24 UTC, chrighter commented on index.html
> +                    <td></td>
Давай будем использовать атрибут `colspan` вместо создания пустых ячеек в таблице

2018-10-13 13:24 UTC, chrighter commented on index.html
> +            <tfoot>
👍

2018-10-13 13:24 UTC, chrighter commented on index.html
> +        <table>
Здорово, что для вёрстки письма используешь табличную вёрстку - это залог того, что вёрстка "не разъедется" ни в одном почтовом клиенте 🔥🔥

2018-10-13 13:24 UTC, chrighter commented on index.html
> +                    <input type="checkbox" value="onTel">
Давай назовем `value` `onPhone`, раз уж стала использовать `onMail`

2018-10-13 13:24 UTC, chrighter commented on index.html
> +                <input type="text" placeholder="Имя" required>
Молодец, что используешь `required` 👍

2018-10-13 13:24 UTC, chrighter commented on index.html
> +                    <input type="checkbox" value="onMail">
После сабмита происходит отправка данных формы на сервер в виде `name1=value1&name2=value2&...`, где `valueN` - это значение атрибута `value` в случае `checkbox` или введенное в поле ввода значение, а `nameN` - то, что для данного `input` записано в атрибут `name`

Поэтому давай еще добавим атрибут `name` во все `input`

2018-10-13 16:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 16:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 13:38 UTC, chrighter requested changes
🍅 

Кажется, ты не добавила атрибут `name` в `checkbox`

А в остальном - молодец 👍

2018-10-16 15:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 15:52 UTC, chrighter approved these changes
🍏

2018-10-17 15:52 UTC, closed without merging