Первый вариант задачи
urfu-2018/markup-task-1 pull request #130
Opened 2018-10-14 19:59 UTC by MargaritaNik

2018-10-14 20:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 20:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 21:12 UTC, spt30 requested changes
🍅
Привет!
В целом хорошо, но если ты здесь не используешь css, не нужно пытаться сделать форматирование с помощью html (например, использовать тег `<br>` для красоты)
Пусть будет не красиво: в этом задании главное уместно использовать различные теги
Их ты можешь посмотреть тут: https://webref.ru/html

Насчет дедлайна: извини, что долго не проверял, был занят: ты сдала задачу на проверку за 16 часов до дедлайна тестов + неделя на проверку ментором, я проверил только сейчас, значит сдвигаю дедлайн до 30 октября 18:00

2018-10-22 21:12 UTC, spt30 commented on index.html
> +    <form>
Форма – это то, что нужно заполнять, заголовок и подпись в форму не входят

2018-10-22 21:12 UTC, spt30 commented on index.html
> +            Ваше имя<input type="text" placeholder="Имя">
Давай оборачивать в тег `<label>`, тогда можно будет кликнуть на название и поля и input сразу получит фокус

Аналогичная петрушка и с чекбоксами

2018-10-22 21:12 UTC, spt30 commented on index.html
> +        <div>
Ты все-все-все обернула в `<div>`'ы, хотя формально тут список
Давай делать все списком: список полей для заполнения, список чекбоксов

2018-10-22 21:12 UTC, spt30 commented on index.html
> +        Хочу получать уведомления:
Стоит голый текст, хорошо бы его обернуть в какой-то тег – вдруг ты захочешь повесить на этот текст стили

2018-10-22 21:12 UTC, spt30 commented on index.html
> +    </form>
Ой форму что-то очень далеко закрыла

2018-10-22 21:12 UTC, spt30 commented on index.html
> +            <button>Подписаться</button>
Есть специальный тип инпута для кнопки в форме

2018-10-22 21:12 UTC, spt30 commented on index.html
> +        <div>
Можно подобрать более семантичный тег

2018-10-22 21:12 UTC, spt30 commented on index.html
> +                <img src="https://img.artlebedev.ru/everything/yandex/identity3/yandex2008.gif"
Для верстки писем хорошо подходит табличная верстка
Тогда ты сможешь картинку располагать отдельно от текста и выглядеть будет красиво

2018-10-22 21:12 UTC, spt30 commented on index.html
> +            <p>
Этот параграф слишком объемный: и приветствие, и вводная часть в одном
Можно его поделить на две части и одну сделать, например, заголовком

2018-10-22 21:12 UTC, spt30 commented on index.html
> +            <footer>
Футер – это нижняя часть страницы, а не письма, тут можно сделать 2 секции – основная часть и импровизированный футер

2018-10-22 21:12 UTC, spt30 commented on index.html
> +        <br>
Блочные теги, такие как `<div>`, `<li>` и так далее, создают вокруг себя блочный контекст форматирования
Это значит, что по умолчанию каждый такой элемент будет располагаться на своей строке, значит, не обязательно использовать `<br>`

2018-10-22 21:12 UTC, spt30 commented on index.html
> +            <input type="checkbox">на почту<br>
А если бы тут был список, не пришлось бы делать перенос строки)

2018-10-28 16:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-28 17:19 UTC, spt30 requested changes
🍅еще чуть-чуть)

2018-10-28 17:19 UTC, spt30 commented on index.html
> +            <input type="button" value="Подписаться">
`type="submit"`

2018-10-28 17:19 UTC, spt30 commented on index.html
> +            <td>
Как-то 4 параграфа в одной ячейке не очень
Давай разнесем на 4 ячейки, а картинку отцентрируем с помощью атрибута rowspan

2018-10-28 18:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 20:19 UTC, spt30 commented
:green_apple: все круто!)

2018-10-29 20:19 UTC, closed without merging