Сумина Елена
urfu-2018/markup-task-1 pull request #131
Opened 2018-10-14 20:03 UTC by JudithRomero

2018-10-14 20:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 05:30 UTC, dotokoto requested changes

2018-10-17 05:30 UTC, dotokoto commented on index.html
> +    <h1>Хочу подписаться!</h1>
Не хватает обертки для всего блока формы

2018-10-17 05:30 UTC, dotokoto commented on index.html
> +    <section>
Вот этот `section` лучше бы перенести выше, заголовок тоже входит в `section`. А здесь уже началась форма, можно использовать соответствующий тег

2018-10-17 05:30 UTC, dotokoto commented on index.html
> +    <section>
Вот этот `section` лучше бы перенести выше, заголовок тоже входит в `section`. А здесь уже началась форма, можно использовать соответствующий тег

2018-10-17 05:30 UTC, Dotokoto commented on index.html
> +            <input type="text" id="phoneNumber" placeholder="89990007766" required pattern="^8\d{10}">
Для телефонов есть свой тип инпута

2018-10-17 05:30 UTC, Dotokoto commented on index.html
> +            <table>
Почему здесь таблица? Это скорее список настроек

2018-10-17 05:30 UTC, Dotokoto commented on index.html
> +    <div>
Точно ли нужна эта обертка для кнопки?

2018-10-21 10:06 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 10:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 11:49 UTC, closed without merging