Елена Маклакова
urfu-2018/markup-task-1 pull request #136
Opened 2018-10-14 21:02 UTC by elena-i-m98

2018-10-14 21:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 15:05 UTC, chrighter requested changes
🍅

2018-10-16 15:05 UTC, chrighter commented on index.css
> +    background: rgb(241, 241, 241);
Почему иногда цвета задаёшь с помощью `rgb`, а иногда с помощью имени?

Давай приведем к одному виду

2018-10-16 15:05 UTC, chrighter commented on index.html
> +        <p class="margl">После Вашего согласия на подписку Вам
Давай вынесем это за пределы формы, так как к ней этот контент не относится

2018-10-16 15:05 UTC, chrighter commented on index.html
> +        <p class="margl">После Вашего согласия на подписку Вам
Непонятное именование класса

2018-10-16 15:05 UTC, chrighter commented on index.html
> +        <tr class="secondStr">
Давай будем использовать `tbody` и `tfoot`, это семантичнее

2018-10-16 15:05 UTC, chrighter commented on index.html
> +        <tr class="firstStr">
Давай не будем именовать классы в `camelCase`

2018-10-16 15:05 UTC, chrighter commented on index.html
> +        <tr class="firstStr">
Давай не будем использовать числительные при именовании

2018-10-16 15:05 UTC, chrighter commented on index.html
> +                <p>Уведомления будут прихоить Вам на этот email и
Давай исправим все опечатки в тексте

2018-10-16 15:05 UTC, chrighter commented on index.html
> +        <input type="tel" id="tel" class="tel" name="tel" value=""
Давай добавим валидацию для этого поля

2018-10-16 15:05 UTC, chrighter commented on index.html
> +               value="" placeholder="email@yandex.ru" required>
👍 за `required`

2018-10-16 15:05 UTC, chrighter commented on index.html
> +            <input type="checkbox" id="ch1" name="uvedoml"
Давай сделаем так, что галочка в `checkbox` будет проставляться, даже если просто на текст нажимаем (`на почту` или `на телефон`)

2018-10-16 15:05 UTC, chrighter commented on index.html
> +            <input type="checkbox" id="ch2" name="uvedoml"
`ch1`, `ch2`, `uvedoml` - непонятные именования

2018-10-16 15:05 UTC, chrighter commented on index.html
> +            <td class="tdImg">
`tdImg`, `txt` - непонятные именования

2018-10-16 15:05 UTC, chrighter commented on index.html
> +                <a href="#" class="clH">Пожаловаться</a>
Непонятное имя класса

2018-10-16 15:05 UTC, chrighter commented on index.html
> +    <table>
Молодец, что для верстки писем используешь табличную вёрстку, это правильный подход - гарантия того, что верстка "не разъедется" ни в одном почтовом клиенте 🔥

2018-10-16 15:05 UTC, chrighter commented on index.html
> +        <p>Хочу получать уведомления:<br>
Давай этот блок тоже выровняем по левому краю для единообразия

2018-10-16 15:05 UTC, chrighter commented on index.html
> +            <td class="bord">
`bord`?

2018-10-16 15:05 UTC, chrighter commented on index.css
> +    margin-left: 50px;
Давай все 3 инпута  - `.text`, `.e-mail`, `.tel` - выровняем по левому краю, сейчас не совсем ровно

2018-10-16 15:05 UTC, chrighter commented on index.css
> +    text-align: center;
Зачем этот стиль?

2018-10-16 15:05 UTC, chrighter commented on index.css
> +    margin-bottom: 12px;
Давай вместо 2 конкретных свойств использовать одно общее - `margin`

2018-10-16 15:05 UTC, chrighter commented on index.html
> +            <input type="checkbox" id="ch2" name="uvedoml"
Зачем тут `id`?

2018-10-16 15:05 UTC, chrighter commented on index.html
> +        <input type="tel" id="tel" class="tel" name="tel" value=""
`class="Phone"`?

2018-10-20 07:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-20 08:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-20 08:19 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-20 08:25 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-20 08:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 07:53 UTC, chrighter requested changes
🍅

2018-10-21 07:53 UTC, chrighter commented on index.css
> +.margin
Давай не будем называть классы `css`-свойствами, потому что через неделю кажется сложно будет понять, о каком элементе идет речь

2018-10-21 07:53 UTC, chrighter commented on index.html
> +        <p class="formscontent">После Вашего согласия на подписку Вам
1) Давай будем именовать через тире: `forms-content`
2) Почему называешь `forms-content`, если этот блок вообще за пределами формы?

2018-10-21 07:53 UTC, chrighter commented on index.html
> +            <input type="tel" id="tel" name="tel" value="" placeholder="89990007766" required>
Валидация, уже писала ранее

2018-10-21 07:53 UTC, chrighter commented on index.html
> +                    <p>Уведомления будут прихоить Вам на этот email и
Опечатки, уже писала ранее

2018-10-21 07:53 UTC, chrighter commented on index.html
> +        <tbody class="letter">
👍 За `tbody` и `tfoot`

2018-10-21 07:53 UTC, chrighter commented on index.css
> +    height: 50px;
Точно нужно?

2018-10-21 07:53 UTC, chrighter commented on index.html
> +                <td class="line">
Класс Линия?

2018-10-21 07:53 UTC, chrighter commented on index.html
> +                <label><input type="checkbox" name="notification" value="на телефон">На телефон</label>
👍 за то, что галочка проставляется даже по нажатию на текст, это удобно, например, когда заполняешь форму с телефона

Теперь давай сделаем как в макете - каждый `checkbox` с новой строки

2018-10-21 07:53 UTC, chrighter commented on index.css
> +input:invalid
👍 за `invalid` - такие выделения позволяют сделать страницу более отзывчивой

2018-10-21 07:53 UTC, chrighter commented on index.css
> +    vertical-align: top;
Зачем?

2018-10-21 07:53 UTC, chrighter commented on index.html
> +    <div>
Давай добавим семантику (заменим все `div` на что-то более говорящее)

2018-10-21 08:04 UTC, chrighter commented on index.html
> +                <td class="line">
Давай еще делать разделяющую линию между контентом и футером письма на макете не с помощью `border` у ячеек `tfoot`

2018-10-23 03:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 03:45 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 03:49 UTC, elena-i-m98 commented on index.html
> +                <td class="line">
К сожалению, тег <hr> внутри таблицы не работает. Найти возможность использовать его,  а не границы, не удалось. Граница всей строки почему-то не отобразилась в браузере тоже.
Подскажите, пожалуйста, каким способом тогда можно добиться рисования горизонтальной линии, если не уходить от табличной верстки?

2018-10-23 03:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 03:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 04:02 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 06:43 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 07:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 07:03 UTC, elena-i-m98 commented
Прошу прощения за задержку - вчера отправить исправленное не могла, так как не работал гитхаб.

2018-10-28 20:06 UTC, chrighter commented on index.html
> +                <td class="line">
Согласна, можно оставить как у тебя, но для того, чтобы линия не разрывалась, можно было добавить `border-collapse`

2018-10-28 20:19 UTC, chrighter requested changes
🍅

2018-10-28 20:19 UTC, chrighter commented on index.html
> +                        class="copyright-position">Яндекс</a></p>
Просто `copyright`

2018-10-28 20:19 UTC, chrighter commented on index.html
> +            name="tel" value="" placeholder="89990007766" required>
Валидация?

2018-10-28 20:19 UTC, chrighter commented on index.html
> +            <p class="content">Хочу получать уведомления:<br>
`notifications`

Блок с уведомлениями и блок перед формой имеют мало общего, не совсем правильно называть их одинаково

2018-10-28 20:19 UTC, chrighter commented on index.html
> +    <br><br><br><br>
Отступы можно делать не с помощью `br`, а при помощи `margin` или `padding`

2018-10-30 18:47 UTC, elena-i-m98 commented on index.html
> +            name="tel" value="" placeholder="89990007766" required>
Что предполагается под валидацией в данном случае? 
Я добавила атрибут pattern. Теперь если вводить неправильно, то появляется всплывающее сообщение: введите данные в указанном формате. Это неправильный вариант решения? Подскажите, пожалуйста, что сделано не так и что именно тогда подразумевалось в этом пункте?
![image](https://user-images.githubusercontent.com/43844991/47742282-221bf080-dc9e-11e8-9293-cc91b5cca8e6.png)

2018-10-31 02:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-31 11:55 UTC, chrighter approved these changes
🍏

2018-10-31 11:55 UTC, chrighter commented on index.html
> +            <p class="receipt_of_notification">Хочу получать уведомления:<br>
На будущее: давай не будем писать `CSS`-классы в `snake_case`
Должно быть `receipt-of-notification`

2018-10-31 11:55 UTC, closed without merging