Галиакбаров Эдуард
urfu-2018/markup-task-1 pull request #141
Opened 2018-10-15 08:16 UTC by Raseen7

2018-10-15 08:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 08:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 08:26 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 08:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-15 11:45 UTC, nex2hex commented
🍅 
задача не закончена

2018-10-22 19:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-22 19:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 07:36 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 07:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 07:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 07:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 11:57 UTC, nex2hex requested changes
🍅

2018-10-23 11:57 UTC, nex2hex commented on index.html
> +        <p><input type="checkbox">на телефон</p>
нет кнопки сабмита формы

2018-10-23 11:57 UTC, nex2hex commented on index.html
> +        <p><input type="checkbox">на почту</p>
тут тоже не хватает label

2018-10-23 11:57 UTC, nex2hex commented on index.html
> +        <p><label>Ваше имя <input type="text" placeholder="Имя"></label></p>
не хватает валидации формы

2018-10-23 11:57 UTC, nex2hex commented on index.html
> +    <form>
а тут зачем форма?

2018-10-23 11:57 UTC, nex2hex commented on index.html
> +        <p>Вы подписались на уведомления о новостях Яндекса.</p>
нет картинки

2018-10-23 11:57 UTC, nex2hex commented on index.html
> +        <p>Здравствуйте, Николай!</p>
тут уместно использовать тэги для заголовка

2018-10-23 14:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 14:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 14:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 15:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 15:05 UTC, nex2hex commented on index.html
> +        <button>Подписаться</button>
type="submit"

2018-10-23 15:05 UTC, nex2hex commented on index.html
> +        <img src="yandex.png" alt="yandex">
у картинок надо задавать высоту и ширину, чтобы контент не прыгал, пока картина грузится

2018-10-23 15:05 UTC, closed without merging