Skudarnova A
urfu-2018/markup-task-1 pull request #142
Opened 2018-10-15 09:44 UTC by AnastasiaSD

2018-10-15 09:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 21:29 UTC, spt30 requested changes
🍅
Привет!
Небольшой фидбек: есть некоторые замечания по первой части задания, а письмо сверстано отлично (отдельный плюс за `<tbody>` и `<tfoot>`), плюс очень четко ограничила, где начинается и где заканчивается форма, молодец!
Остались небольшие правки

По поводу дедлайна: ты сдала задачу за 3 часа до дедлайна + неделя на проверку ментором, то есть продлеваю дедлайн на неделю и 3 часа с текущего времени: новый дедлайн – 30 октября 5:30 утра
Извини, что долго не проверял, был занят

2018-10-22 21:29 UTC, spt30 commented on index.html
> +<fieldset>
`<fieldset>` используется для группировки элементов формы, а не для рисования границ
Эту задачу нужно было решить без использования css, так что можно не заморачиваться за внешний вид и не использовать что-то специально, чтобы сделать красиво

Пусть будет некрасиво и налеплено, главное в этой задаче – семантика
Описание тегов и их предназначение можешь посмотреть тут: https://webref.ru/html

2018-10-22 21:29 UTC, spt30 commented on index.html
> +        <div class="field">
Зачем ты даешь классы, если не используешь css?

2018-10-22 21:29 UTC, spt30 commented on index.html
> +        <div class="field">
`<div>` не самый подходящий тег, это все выглядит как список, давай подберем соответствующий тег

2018-10-22 21:29 UTC, spt30 commented on index.html
> +        <div>
Тоже выглядит, как маленький список

2018-10-22 21:29 UTC, spt30 commented on index.html
> +            <label><input type="checkbox" id="checkbox-email" name="check-email">на почту</label><br>
Был бы список, не пришлось бы делать переносы)

2018-10-22 21:29 UTC, spt30 commented on index.html
> +<div>
Выдержка из спецификации: "Элемент `<div>` следует использовать только в том случае, если никакой другой семантический элемент (такой как `<article>` или `<nav>`) не подходит."

2018-10-22 21:29 UTC, spt30 commented on index.html
> +    <table>
Лойс за табличную верстку: для верстки писем это лучшее на сегодняшний день решение, молодец)

2018-10-22 21:29 UTC, spt30 commented on index.html
> +                <p>Здравствуйте, Николай!</p>
Очень круто используешь табличные теги, но есть нюанс: у тебя целых 4 параграфа в одной ячейке. Вероятно, это сделано для того, чтобы картинка хорошо встала. Если ты разделишь эту строку на 4 строки, то чтобы выровнять картинку, можно воспользоваться атрибутом `rowspan` (парный к нему атрибут – `colspan`)

2018-10-22 21:29 UTC, spt30 commented on index.html
> +        <p><input type="button" value="Подписаться"></p>
Этот параграф выглядит, как лишняя обертка, давай от него избавимся

2018-10-27 10:01 UTC, AnastasiaSD commented on index.html
> +        <div class="field">
<ul>?

2018-10-27 10:02 UTC, AnastasiaSD commented on index.html
> +        <div class="field">
ul?

2018-10-27 11:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-27 22:37 UTC, spt30 commented
🍏Теперь все круто! Молодец!

2018-10-27 22:37 UTC, closed without merging