Евгений Шумейко
urfu-2018/markup-task-1 pull request #143
Opened 2018-10-15 10:40 UTC by EvgeniiShumeiko

2018-10-15 10:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-15 12:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 12:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 14:01 UTC, SemyonMakhaev requested changes
🍅 

Евгений, привет! Извини за долгое ревью

Молодец, что написал стили! Получилось очень круто)
Есть несколько замечаний. Если будут вопросы, пиши мне в слаке

2018-10-20 14:01 UTC, SemyonMakhaev commented on index.css
> +@font-face
👍 👍 👍

2018-10-20 14:01 UTC, SemyonMakhaev commented on index.css
> +    outline: 0;
Отключать `outline` не рекомендуется в целях обеспечения доступности. Вот статья на эту тему: http://outlinenone.com

2018-10-20 14:01 UTC, SemyonMakhaev commented on index.css
> +    outline: 0;
аналогично

2018-10-20 14:01 UTC, SemyonMakhaev commented on index.css
> +.sender_logo
`snake_case` не принято использовать для именования классов CSS, поскольку это усложняет их чтение. Используй `kebab-case`

Однако добавлю, что существуют разные соглашения по именованию классов. Например, в Яндексе наша команда использует методологию БЭМ, в которой реализуется некоторое подобие snake case написания. Если интересно, можешь поизучать 😉 
https://ru.bem.info/methodology/naming-convention/

2018-10-20 14:01 UTC, SemyonMakhaev commented on index.html
> +                            <img src="https://yastatic.net/www/_/_/i/tLI86LIriNsIJwhEqZS2o1Ckk.webp"
У тега `img` также обязательно надо указывать атрибут `title`. Это необходимо для доступности интерфейса

2018-10-22 18:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 18:54 UTC, SemyonMakhaev commented
🍏 

Всё здорово 👍

2018-10-22 18:54 UTC, closed without merging