Патанин Максим
urfu-2018/markup-task-1 pull request #145
Opened 2018-10-15 11:09 UTC by NorDDay

2018-10-15 11:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 14:11 UTC, SemyonMakhaev requested changes
🍅 

Привет, Максим! Извини за долгое ревью.

По коду всё круто, есть буквально пара замечаний. Если будут вопросы, пиши мне в слаке)

2018-10-20 14:11 UTC, SemyonMakhaev commented on index.html
> +        <input type="submit" value="Подписаться">
Не будет ли семантичнее для кнопки использовать тег `button`?

2018-10-20 14:11 UTC, SemyonMakhaev commented on index.html
> +        <div id="left-block">
Зачем `id`?

2018-10-20 14:11 UTC, SemyonMakhaev commented on index.html
> +                телефон &ndash; +79*******66</p>
👍

2018-10-20 14:11 UTC, SemyonMakhaev commented on index.html
> +        <div id="right-block">
Аналогично, `id`

2018-10-20 14:11 UTC, SemyonMakhaev commented on index.html
> +            <img alt="Yandex" title="logo" class="img"
👍 👍 👍

2018-10-20 14:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 14:33 UTC, NorDDay commented
Поправил

2018-10-20 19:41 UTC, SemyonMakhaev commented
Оперативно! 🔥

2018-10-20 19:41 UTC, closed without merging