Самойлова Екатерина
urfu-2018/markup-task-1 pull request #146
Opened 2018-10-15 11:15 UTC by Katerisa

2018-10-15 11:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:26 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:30 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:33 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:33 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-15 11:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 14:22 UTC, SemyonMakhaev requested changes
🍅 

Екатерина, привет! Извини за долгое ревью.

Молодец, что написала стили! Получилось очень здорово и качественно 👍 
Есть несколько замечаний. Если будут вопросы, пиши мне в слаке)

2018-10-20 14:22 UTC, SemyonMakhaev commented on index.css
> +p
Использование селекторов тегов чревато тем, что стили могут примениться к совершенно неожиданным элементам на странице. Лучше конкретно указывать, какие классы стилизуются, чтобы вёрстка не сломалась

2018-10-20 14:22 UTC, SemyonMakhaev commented on index.css
> +    border: 1px solid lightgray;
Правило дублируется. Нужно вынести в отдельный класс или объединить селекторы

2018-10-20 14:22 UTC, SemyonMakhaev commented on index.css
> +    background-color: white;
Цвета следует указывать во всём проекте в одной и той же нотации для сохранения общности. При этом лучше использовать `hex`-нотацию, так как она интуитивно более понятна, и ей проще воспользоваться при переносе цветов из макета в интерфейс

2018-10-20 14:22 UTC, SemyonMakhaev commented on index.css
> +    padding-top: 20px;
Тоже дублируется правило

2018-10-20 14:22 UTC, SemyonMakhaev commented on index.html
> +    <div class="main">
Можно добавить семантики
```suggestion
    <main class="main">
```

2018-10-20 14:22 UTC, SemyonMakhaev commented on index.html
> +            <input type="text" id="name-field" placeholder="Имя" pattern="^[А-Яа-яЁё]+$" autofocus required>
👍

2018-10-20 14:22 UTC, SemyonMakhaev commented on index.html
> +        <img class="logo" src="yandex.jpg" alt="Яндекс">
Картинка, кажется, потерялась

2018-10-20 14:22 UTC, SemyonMakhaev commented on index.html
> +        <img class="logo" src="yandex.jpg" alt="Яндекс">
У тега `img` также всегда обязательно нужно указывать атрибут `title`. Это необходимо для обеспечения доступности

2018-10-20 19:28 UTC, SemyonMakhaev commented
Для локального запуска линтера можешь использовать команду `npm run lint`

2018-12-15 08:13 UTC, closed without merging