Павельев Иван
urfu-2018/markup-task-1 pull request #147
Opened 2018-10-15 11:18 UTC by Pavelevivan

2018-10-15 11:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 19:14 UTC, SemyonMakhaev requested changes
🍅 

Привет, Иван! Извини за долгое ревью.

В целом всё круто! Есть несколько замечаний. Если будут вопросы, пиши мне в слаке)

2018-10-20 19:14 UTC, SemyonMakhaev commented on index.html
> +				<label>Телефон <input type="tel" name="telephone" required="" pattern="[0-9]{11}"
Зачем пустое значение у атрибута `required`?

2018-10-20 19:14 UTC, SemyonMakhaev commented on index.html
> +				<label><input type="checkbox" checked="">на почту</label><br>
Аналогично, пустое значение атрибута `checked`

2018-10-20 19:14 UTC, SemyonMakhaev commented on index.html
> +				<label><input type="submit" name="Subscribe" value="Подписаться"></label>
Не будет ли семантичнее для кнопки использовать тег `button`?

2018-10-20 19:14 UTC, SemyonMakhaev commented on index.html
> +				<label><input type="submit" name="Subscribe" value="Подписаться"></label>
Зачем лейбл у кнопки? Там ведь кроме кнопки ничего нет

2018-10-20 19:14 UTC, SemyonMakhaev commented on index.html
> +						<td><img alt="yandex" src="logo_yandex.gif" width="100" height="50"></td>
У тега `img` также всегда обязательно нужно указывать атрибут `title`. Это необходимо для обеспечения доступности

2018-10-20 19:14 UTC, SemyonMakhaev commented on index.html
> +							на указанный вами телефон - +79ххххххх78.
Используй `&mdash;` или `&ndash;`, иначе твой HTML будет невалидным

2018-10-20 19:14 UTC, SemyonMakhaev commented on index.html
> +				<label>E-mail: <input type="email" required
👍

2018-10-23 11:56 UTC, Pavelevivan commented on index.html
> +				<label>Телефон <input type="tel" name="telephone" required="" pattern="[0-9]{11}"
На лекции говорили, что так объявляют. В лекции 1 html 74 слайд

2018-10-23 12:11 UTC, Pavelevivan commented on index.html
> +				<label><input type="checkbox" checked="">на почту</label><br>
Аналогично

2018-10-23 12:18 UTC, Pavelevivan commented on index.html
> +							на указанный вами телефон - +79ххххххх78.
Хорошо, понял

2018-10-23 12:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 14:07 UTC, SemyonMakhaev approved these changes
🍏

2018-10-23 14:07 UTC, SemyonMakhaev commented on index.html
> +				<input type="button" name="Subscribe" value="Подписаться">
Атрибут `type` в значении `submit` - было правильно. Элемент с таким атрибутом триггерит отправку формы. А вот тег можно использовать `button`

2018-10-23 14:08 UTC, closed without merging