Юхатский Илья
urfu-2018/markup-task-1 pull request #148
Opened 2018-10-15 11:23 UTC by creewick

[Посмотреть решение](https://hruview.herokuapp.com/creewick/markup-task-1/master/index.html)

2018-10-15 11:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 19:25 UTC, SemyonMakhaev requested changes
🍅 

Илья, привет! Извини за долгое ревью.

Молодец, что написал стили! Получилось очень круто 👍 
Есть несколько замечаний. Если будут вопросы, пиши мне в слаке

2018-10-20 19:25 UTC, SemyonMakhaev commented on index.css
> +h1
Использование селекторов тегов чревато тем, что стили могут примениться к совершенно неожиданным элементам на странице. Лучше конкретно указывать, какие классы стилизуются, чтобы вёрстка не сломалась

2018-10-20 19:25 UTC, SemyonMakhaev commented on index.html
> +    <fieldset class="form">
Почему `fieldset` имеет имя класса `form`?

2018-10-20 19:25 UTC, SemyonMakhaev commented on index.html
> +                <td><input class="field" type="tel" placeholder="89990007766"
👍

2018-10-20 19:25 UTC, SemyonMakhaev commented on index.html
> +        <input type="submit" class="button" value="Подписаться">
Не будет ли семантичнее для кнопки использовать тег `button`?

2018-10-20 19:25 UTC, SemyonMakhaev commented on index.html
> +            <p>Уведомления будут приходить вам на этот email и на указанных вами телефон - +79ххххххх78.</p>
Используй `&mdash;` или `&ndash;`, иначе твой HTML будет невалидным

2018-10-20 19:25 UTC, SemyonMakhaev commented on index.html
> +        <td class="top right"><img src="./yandex.png" alt="Яндекс" width="100"></td>
У тега `img` также всегда обязательно нужно указывать атрибут `title`. Это необходимо для обеспечения доступности

2018-10-20 19:25 UTC, SemyonMakhaev commented on index.html
> +                <td class="right">© 2018, <a href="">Яндекс</a></td>
```suggestion
                <td class="right">&copy; 2018, <a href="">Яндекс</a></td>
```

2018-10-20 19:27 UTC, SemyonMakhaev commented
Для локального запуска линтера можешь использовать команду `npm run lint`

2018-10-22 09:40 UTC, creewick commented on index.css
> +h1
а `body` можно использовать?
явно показывая, что хочу применить стили ко всей странице

2018-10-22 13:42 UTC, creewick commented on index.css
> +h1
Заменил на классы

2018-10-22 13:42 UTC, creewick commented on index.html
> +    <fieldset class="form">
Пытался семантически разделить `form` от `letter`. Убрал

2018-10-22 13:42 UTC, creewick commented on index.html
> +        <input type="submit" class="button" value="Подписаться">
Заменил

2018-10-22 18:46 UTC, SemyonMakhaev approved these changes
🍏 

Всё здорово, молодец!

2018-10-22 18:46 UTC, SemyonMakhaev commented on index.css
> +.markup-1
Название класса должно быть понятным и нести какую-то смысловую нагрузку.
В данном случае удачнее будет, как мы с тобой обсуждали, использовать селектор тега `body`, как глобального родительского элемента

2018-10-22 18:46 UTC, closed without merging

2018-10-23 06:03 UTC, creewick commented on index.css
> +.markup-1
Я просто в задаче по js увидел классы по типу `task-n`
Но да, насчет `body` понял