Акишкина Вероника
urfu-2018/markup-task-1 pull request #149
Opened 2018-10-15 11:25 UTC by AirenLaird

[Посмотреть решение](https://hruview.herokuapp.com/AirenLaird/markup-task-1/master/index.html)

2018-10-15 11:26 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 19:36 UTC, SemyonMakhaev requested changes
🍅 

Вероника, привет! Извини за долгое ревью.

По коду всё круто, за исключением нескольких замечаний. Если будут вопросы, пиши мне в слаке.
Как внесёшь правки - призови или напиши мне, чтобы я успел закрыть задачу до дедлайна)

2018-10-20 19:36 UTC, SemyonMakhaev commented on index.html
> +                <td><input type="text" required="" placeholder="Имя"></td>
Зачем пустое значение атрибута `required`?

2018-10-20 19:36 UTC, SemyonMakhaev commented on index.html
> +                <td>Ваше имя</td>
Получится ли сделать так, чтобы инпут становился активным при нажатии на текст рядом с ним? Аналогично для остальных полей для ввода и чекбоксов

2018-10-20 19:36 UTC, SemyonMakhaev commented on index.html
> +            <td><img src="image.jpg" height="30" alt="Логотип"></td>
У тега `img` также всегда обязательно нужно указывать атрибут `title`. Это необходимо для обеспечения доступности

2018-10-20 19:36 UTC, SemyonMakhaev commented on index.html
> +            <td>Уведомления будут приходить вам на этот email и на указанный вами телефон - +79xxxxxxx78.</td>
Используй `&mdash;` или `&ndash;`, иначе твой HTML будет невалидным

2018-10-20 19:36 UTC, SemyonMakhaev commented on index.html
> +                <td><input type="tel" required="" pattern="89[0-9]{9}" placeholder="89xxxxxxxxx"></td>
👍

2018-10-21 07:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 07:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 07:05 UTC, AirenLaird commented
Добрый день :) Сделала поправки, вызванные замечаниями. 🔔
Конкретнее по замечаниям:
1) Убрала пустое значение у атрибута required;
2) Добавила тег lable с атрибутом for и атрибут id в тег input для каждого тега input;
3) Указала атрибут title у тега img;
4) Заменила тире на короткое тире &ndash; (А какие ещё вроде бы обычные символы портят валидацию html?)

2018-10-21 15:19 UTC, SemyonMakhaev commented
> А какие ещё вроде бы обычные символы портят валидацию html?

Вот полный список спецсимволов: http://htmlbook.ru/samhtml/tekst/spetssimvoly
Ещё вот есть W3C-валидатор HTML: https://validator.w3.org

2018-10-21 15:22 UTC, SemyonMakhaev approved these changes
🍏

Супер! Молодец 👍

2018-10-21 15:22 UTC, closed without merging

2018-10-21 16:41 UTC, AirenLaird commented
Благодарю ✨


>Воскресенье, 21 октября 2018, 20:19 +05:00 от Махаев Семён <notifications@github.com>:
>
>>А какие ещё вроде бы обычные символы портят валидацию html?
>Вот полный список спецсимволов:  http://htmlbook.ru/samhtml/tekst/spetssimvoly
>Ещё вот есть W3C-валидатор HTML:  https://validator.w3.org
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
С уважением,
Акишкина Вероника Александровна