Рожков Максим
urfu-2018/markup-task-1 pull request #152
Opened 2018-10-15 12:22 UTC by MaximRhz

[Посмотреть решение](https://hruview.herokuapp.com/MaximRhz/markup-task-1/master/index.html)

2018-10-15 12:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 13:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 14:20 UTC, chrighter requested changes
:tomato

2018-10-16 14:20 UTC, chrighter commented on index.html
> +        <h2>Хочу подписаться!</h2>
Почему используешь `h2`, если не использовал еще на странице `h1`?

2018-10-16 14:20 UTC, chrighter commented on index.html
> +        <form name="test"  action="URL" method="post">
Давай будем писать `#` вместо `URL`

2018-10-16 14:20 UTC, chrighter commented on index.html
> +                Телефон <input  type="tel" id="phone" name="phone"  placeholder="89990007766"   required>
Давай добавим валидацию на номер телефона

2018-10-16 14:20 UTC, chrighter commented on index.html
> +                Email <input  type="email" id="email" name="email"  placeholder="Enter Email"   required>
👍 за `required`

2018-10-16 14:20 UTC, chrighter commented on index.html
> +                Email <input  type="email" id="email" name="email"  placeholder="Enter Email"   required>
Почему один `placeholder` на английском языке, а другой - на русском?

Давай все приведем к одному виду

2018-10-16 14:20 UTC, chrighter commented on index.html
> +            <label for="checkPhone">на телефон</label>
Здорово, что галочка в `checkbox` ставится даже по нажатию на текст! Это очень удобно, например, когда заполняешь форму с мобильного

2018-10-16 14:20 UTC, chrighter commented on index.html
> +            <p>Для подтверждения прейдите по <a href="https://goo.gl/evS6DH" title="Rick">ссылке</a></p>
🔥

2018-10-16 14:20 UTC, chrighter commented on index.html
> +    <section>
Для верстки писем лучше использовать табличную верстку - это залог того, что верстка "не разъедется" ни в одном почтовом клиенте

Подробнее можно посмотреть здесь: https://habr.com/post/252279/

2018-10-16 14:20 UTC, chrighter commented on index.html
> +        <header>
Кажется, это `section`, а не `header`

2018-10-16 14:20 UTC, chrighter commented on index.html
> +            <img src="https://goo.gl/pYtExS" width="100"  alt="YandexLogo">
Давай будем располагать картинку как на макете - справа от текста, а не над ним

2018-10-16 14:20 UTC, chrighter commented on index.html
> +    <a href="https://goo.gl/VvYb7A" title="Пожаловаться">Пожаловаться</a>
🔥

2018-10-16 14:20 UTC, chrighter commented on index.html
> +    &#8195;&#8195;&#8195;&#8195;&#8195;
Это не самый удачный подход)

2018-10-16 14:20 UTC, chrighter commented on index.html
> +    <section>
`section` обычно используют внутри `main`- в `main`помещают основное содержимое страницы, а с помощью `section` основное содержимое "разбивают" на какие-нибудь существенные блоки
Поэтому их не стоит ставить рядом, ведь они разделяют контент на разных уровнях

2018-10-16 17:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 19:20 UTC, chrighter requested changes
🍅

2018-10-19 19:20 UTC, chrighter commented on index.html
> +            <tr>
Давай для семантичности перенесем контент в теги `tbody` и `tfoot`

2018-10-19 19:20 UTC, chrighter commented on index.html
> +                    <img src="https://goo.gl/pYtExS" width="100"  alt="YandexLogo">
Давай будем располагать картинку как в макете - вдоль первого и второго абзаца

2018-10-19 19:20 UTC, chrighter commented on index.html
> +                pattern="^8[\d]{10}$"  required>
👍

2018-10-19 19:20 UTC, chrighter commented on index.html
> +    <div>
Давай сделаем более семантично

2018-10-21 17:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 17:54 UTC, chrighter requested changes
🍏 

Не забудь это исправить

2018-10-21 17:54 UTC, chrighter commented on index.html
> +                pattern="^8[\d]{10}$"  required>
Давай просто `\d`, так как `[]` для перечисления набора символов

2018-10-21 17:54 UTC, chrighter commented on index.html
> +        [надеюсь это подойдет]
**Элемент `section`**
Категории контента: потоковое содержимое, секционное содержимое.
Элемент представляет собой универсальный раздел документа. Группирует тематическое содержимое и обычно содержит заголовок. В качестве содержимого может выступать оглавление, разделы научных публикаций, программа мероприятия

**Элемент `aside`**
Категории контента: потоковое содержимое, секционное содержимое.
Группирует содержимое, связанное с окружающим его контентом напрямую, но которое можно счесть отдельным (т.е., удаление этого блока не повлияет на понимание основного содержимого). _Чаще всего элемент позиционируется как боковая колонка (как в книгах) и включает в себя группу элементов: `nav`, цифровые данные, цитаты, рекламные блоки, архивные записи. Не подходит для блоков, просто позиционированных в стороне._

Может быть все же `section`? И вместо `main` тоже `section`

2018-10-21 18:57 UTC, chrighter approved these changes

2018-10-21 18:57 UTC, closed without merging