Ефременков Роман
urfu-2018/markup-task-1 pull request #156
Opened 2018-10-16 12:42 UTC by RAEfremenkov

2018-10-16 12:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 10:19 UTC, dotokoto requested changes

2018-10-19 10:19 UTC, dotokoto commented on index.html
> +    <link rel="stylesheet" href="./index.css">
о, даже с версткой! Выглядит симпатично 👍

2018-10-19 10:19 UTC, Dotokoto commented on index.html
> +            <span class="subscription-form__label">Ваше имя</span>
Есть специальный тег `<label>`, который связывает инпут и подпись к нему. Используй его, тем более что дальше в чекбоксах используешь

2018-10-19 10:19 UTC, Dotokoto commented on index.html
> +                required maxlength="20" pattern="[a-zA-Zа-яА-я]+">
С такими паттернами надо быть осторожнее. Например, этот паттерн не пропускает букву `ё`

2018-10-21 05:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 05:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 06:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 11:51 UTC, closed without merging

2018-10-23 17:10 UTC, RAEfremenkov commented
🔔  а почему метка в итоге invalid? =(((

2018-10-26 01:23 UTC, RAEfremenkov commented
🔔 Хрюша несправедлив, удалил красивую зеленую метку и выставил желтую! Прошу проверить и восстановить справедливость!