Белых Владислав
urfu-2018/markup-task-1 pull request #157
Opened 2018-10-17 20:38 UTC by belykhvd

2018-10-17 20:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 20:51 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 22:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 21:39 UTC, spt30 requested changes
🍅 Задание выполнено не полностью + верстка выглядит так, как будто ты не до конца разобрался
Может попробовать сделать заново?

2018-10-22 21:39 UTC, spt30 commented on index.css
> +    font-family: Arial;
Обычно добавляют более широкий набор шрифтов на случай, если у пользователя на компьютере оного не окажется: тут, как правило, пишут так: `Arial, Helvetica, sans-serif`. Последний говорит браузеру: "Если нет ни первого, ни второго, возьми любой, который есть, без засечек"

2018-10-22 21:39 UTC, spt30 commented on index.html
> +	<head>
Сделал лишний отступ

2018-10-22 21:39 UTC, spt30 commented on index.html
> +			<section><h1 class="subscription_header">Хочу подписаться!</h1></section>
Секции используешь несемантично, пересмотри лекцию или почитай примеры использования

2018-10-22 21:39 UTC, spt30 commented on index.html
> +			<section><pre>
Зачем тут `<pre>`?

2018-10-22 21:39 UTC, spt30 commented on index.html
> +			<section><h1 class="subscription_header">Хочу подписаться!</h1></section>
Равно как и `<article>`
Если не разберешься – напиши мне в слак, будем разбираться вместе

2018-10-22 21:39 UTC, spt30 commented on index.html
> +						<p><input type="checkbox">на почту</p>
лишние параграфы, оберни в `<label>`

2018-10-22 21:39 UTC, spt30 commented on index.html
> +					<section><p><input type="submit" value="Подписаться"></p></section>
Слишком много оберток для одной кнопки

2018-12-15 08:13 UTC, closed without merging