first try
urfu-2018/markup-task-1 pull request #158
Opened 2018-10-19 08:48 UTC by ainail

2018-10-19 08:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 21:47 UTC, spt30 requested changes
🍅

P.S. Разберись с отступами, пожалуйста

2018-10-22 21:47 UTC, spt30 commented on index.css
> +.ramka
не пиши транслитом

2018-10-22 21:47 UTC, spt30 commented on index.css
> +    font-family: Arial;
Обычно добавляют более широкий набор шрифтов на случай, если у пользователя на компьютере оного не окажется: тут, как правило, пишут так: Arial, Helvetica, sans-serif. Последний говорит браузеру: "Если нет ни первого, ни второго, возьми любой, который есть, без засечек"

2018-10-22 21:47 UTC, spt30 commented on index.css
> +.sz
давай более полные названия классов

2018-10-22 21:47 UTC, spt30 commented on index.html
> +
зачем тут пустая строчка?

2018-10-22 21:47 UTC, spt30 commented on index.html
> +    <body>
лишний отступ везде

2018-10-22 21:47 UTC, spt30 commented on index.html
> +                <form>
Форма начинается там, где нужно что-то заполнять
Заголовок и подпись к форме не относятся

2018-10-22 21:47 UTC, spt30 commented on index.html
> +                    <div class="text">После
Можно подобрать более семантичный тег

2018-10-22 21:47 UTC, spt30 commented on index.html
> +                    <div class="sidebar">
тут стоило сделать отдельными элементами "подпись - инпут" в столбик (наподобие списка)

2018-10-22 21:47 UTC, spt30 commented on index.html
> +                            <p><input type="text" placeholder="Васек" required></p>
Интересный плейсхолдер

2018-10-22 21:47 UTC, spt30 commented on index.html
> +                            <input type="checkbox" class="text" name="test" value="mail">на почту<br>
стоит обернуть текст в `<label>`, тогда можно будет кликать по тексту, а галочка все равно будет ставиться
это удобно на маленьких экранах

2018-10-22 21:47 UTC, spt30 commented on index.html
> +                            <input type="checkbox" class="text" name="test" value="mail">на почту<br>
почему `name="test"`? и ниже тоже
можешь почитать, зачем нужен name, если не разберешься – напиши мне в слак

2018-10-22 21:47 UTC, spt30 commented on index.html
> +        <div class="ramka mail">
Письмо лучше переписать полностью:
- нет семантики совершенно, пересмотри лекцию, также подходящий теги можешь найти тут: https://webref.ru/html
- названия классов отражают ничего
- все элементы лежат плоско и, как следствие, нет логики, выглядит просто как поток текста

2018-12-15 08:14 UTC, closed without merging