Корабельников Алексей
urfu-2018/markup-task-1 pull request #159
Opened 2018-10-20 17:24 UTC by AlexKorablenikov

[Посмотреть решение](https://hruview.herokuapp.com/AlexKorablenikov/markup-task-1/master/index.html)

2018-10-20 17:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 08:04 UTC, chrighter requested changes
🍅

2018-10-21 08:04 UTC, chrighter commented on index.html
> +        <header><h2>Хочу подписаться!</h2></header>
Почему используешь `h2`, если еще не использовал на странице `h1`?

2018-10-21 08:04 UTC, chrighter commented on index.html
> +            <input required autofocus type="text" id="name" placeholder="Имя"><br>
👍 за `required` и `autofocus`

2018-10-21 08:04 UTC, chrighter commented on index.html
> +            <input required type="tel" id="phone" placeholder="89990007766"><br>
Давай добавим валидацию этого поля

2018-10-21 08:04 UTC, chrighter commented on index.html
> +            <input type="checkbox" id="checkMail" value="ch1" >
После сабмита формы данные уйдут в формате `name1=value1&name2=value2...`, кажется, что `value="ch1"` мало о чем говорит

Давай сделаем более понятные именования

2018-10-21 08:04 UTC, chrighter commented on index.html
> +        <table>
Использование табличной верстки для верстки письма - правильный подход, молодец!

2018-10-21 08:04 UTC, chrighter commented on index.html
> +            <tbody>
👍 за `tbody` и `tfoot`

2018-10-21 08:04 UTC, chrighter commented on index.html
> +                    <td rowspan="3">
👍

2018-10-21 08:04 UTC, chrighter commented on index.html
> +                    <td>Для подтверждения прейдите по <a href="#">ссылке</a>.</td>
Давай исправим опечатки

2018-10-21 14:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 17:33 UTC, chrighter approved these changes
🍏

2018-10-21 17:33 UTC, closed without merging