r
urfu-2018/markup-task-1 pull request #160
Opened 2018-10-21 11:48 UTC by SirMajesty

2018-10-21 11:49 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 11:51 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 11:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 12:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 12:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 12:14 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 12:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 07:01 UTC, VasiliiKuznecov commented on index.css
> +body div
лучше не использовать теги для стилей, так как не везде на странице ты хочешь чтобы такой имел такой стиль
div например вообще очень часто применяется, для абсолютно разных вещей
лучше навесить класс, назвать как сущность, которую он представляет, и написать стили для класса

2018-10-23 07:01 UTC, VasiliiKuznecov commented on index.css
> +.mes
что такое mes? лучше не сокращать названия

2018-10-23 07:01 UTC, VasiliiKuznecov commented on index.html
> +            <p><label><input type="checkbox">на почту</label></p>
еще бы инпутам нужны name

2018-10-23 07:01 UTC, VasiliiKuznecov commented on index.html
> +                    <td><input type="text" placeholder="89990007766" maxlength="11" size="55"></td>
нет валидации

2018-10-23 07:01 UTC, VasiliiKuznecov commented on index.html
> +                    <td><input type="text" placeholder="email@yandex.ru" size="55"></td>
для email и телефонов есть специальные типы инпутов

2018-10-23 07:01 UTC, VasiliiKuznecov commented on index.html
> +                    <td><input type="text" placeholder="89990007766" maxlength="11" size="55"></td>
максимум 11 символов, но ширина поля в 5 раз больше? зачем?

2018-10-28 11:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 07:26 UTC, VasiliiKuznecov requested changes

2018-10-29 07:26 UTC, VasiliiKuznecov commented on index.css
> +.forma,
не называй транслитом классы

2018-10-29 07:26 UTC, VasiliiKuznecov commented on index.css
> +td
лучше не применять стили к тегам, а навесить класс, назвать его по сущности, к которой он привязан и применить стили к классу

2018-10-29 07:26 UTC, VasiliiKuznecov commented on index.html
> +                    <td><input name="phone" type="number" placeholder="89990007766" size="55"></td>
валидации так и нет

2018-10-29 07:26 UTC, VasiliiKuznecov commented on index.html
> +                    <td><input name="phone" type="number" placeholder="89990007766" size="55"></td>
для телефона тип - не число, а именно телефон

2018-12-15 08:14 UTC, closed without merging