Мчанга Кутемба
urfu-2018/markup-task-1 pull request #162
Opened 2018-11-27 18:24 UTC by kutemba0580

[Посмотреть решение](https://hruview.herokuapp.com/kutemba0580/markup-task-1/master/index.html)

2018-11-27 18:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-15 08:15 UTC, mokhov requested changes
🍅 есть что исправить

2018-12-15 08:15 UTC, mokhov commented on index.html
> +    <article>
Все-таки `article` про организацию сущностей одного типа, а не разного

2018-12-15 08:15 UTC, mokhov commented on index.html
> +                        <td>Ваше имя</td>
Есть тег label и его стоит здесь использовать для связи с input'ом

2018-12-15 08:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2019-01-06 08:07 UTC, vaseker commented on index.html
> +                        <td>Ваше имя</td>
Допустим, label for используется ниже в чекбоксах, знание есть и применено.

2019-01-06 08:10 UTC, vaseker commented
🍏

2019-01-06 08:10 UTC, closed without merging