верстка формы и письма
urfu-2018/markup-task-1 pull request #163
Opened 2018-12-09 11:14 UTC by sHooKDT

2018-12-09 11:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-15 08:16 UTC, mokhov requested changes
🍅 есть что исправить

2018-12-15 08:16 UTC, mokhov commented on index.css
> +.letter__logo
Одна из особенностей вёрстки писем – это почти полное отсутствие CSS, т.к чаще всего почтовые программы режут его. Сверстай, пожалуйста, без CSS, тем более что задание давалось когда вы «де-юре» ещё не знали о нём :)

2018-12-17 08:46 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-12-17 08:49 UTC, sHooKDT commented on index.css
> +.letter__logo
Насколько я знаю, css просто инлайнится в тэги, чтобы его не резали (тут линтер не разрешает).
Убрал css в письме полностью.

2018-12-17 08:49 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-12-24 17:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2019-01-10 05:54 UTC, closed without merging