Loginov Andrew
urfu-2018/markup-task-1 pull request #17
Opened 2018-10-10 19:32 UTC by AndrewLoginov

Form and letter

2018-10-10 19:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 04:57 UTC, mokhov requested changes
🍅 в целом очень неплохо, но чуть-чуть надо доделать

2018-10-11 04:57 UTC, mokhov commented on index.css
> +    font-family: Geneva, Arial, Helvetica, sans-serif;
А зачем везде ```font-family```дублировать?

2018-10-11 04:57 UTC, mokhov commented on index.html
> +                            <img src="https://trashbox.ru/files/71245_576811/70365621.gif"
Логотип растянуло на всю ширину

2018-10-11 04:57 UTC, mokhov commented on index.html
> +                    <input class="input_notification" type="checkbox"
```value``` – это значение, которое передаётся на почту. В случае с ```checkbox``` это 1 или 0 и не надо его отдельно указывать

2018-10-11 09:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 09:50 UTC, AndrewLoginov commented on index.html
> +                            <img src="https://trashbox.ru/files/71245_576811/70365621.gif"
Там style в бане, поэтому не задавал никакие стили для письма

2018-10-11 18:50 UTC, mokhov commented on index.html
> +                            <img src="https://trashbox.ru/files/71245_576811/70365621.gif"
Мы про это расскажем дальше, но у тебя есть выход как: сохранить картинку меньших размеров

2018-10-12 03:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 13:36 UTC, mokhov commented
:ok:

2018-10-19 13:36 UTC, closed without merging