Гладышева Татьяна
urfu-2018/markup-task-1 pull request #18
Opened 2018-10-10 19:43 UTC by Boo24

2018-10-10 19:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 07:41 UTC, nex2hex commented
🍅 
1) Сломалась верстка письма https://yadi.sk/i/PIUrje7YOruWjQ . В самом письме - таблицу надо использовать для табличных данных, а не для верстки. Тут хватит float right
2) Чекбоксы можно не стилизовать, стандартные выглядят нормально в большинстве случаев, не ломают верстку (выравнивание), экономят время на разработку

2018-10-11 15:55 UTC, nex2hex requested changes
🍅 
Смотрю только html разметку, стили не важны

2018-10-11 15:55 UTC, nex2hex commented on index.html
> +        <p>Хочу получать уведомления:
Эти поля должны быть внутри формы

2018-10-11 15:55 UTC, nex2hex commented on index.html
> +                <input class="input_text" type="text" name="name" placeholder="Имя" maxlength="90">
required

2018-10-11 15:55 UTC, nex2hex commented on index.html
> +        <button class="subscribe_button" name="subscribe">Подписаться</button>
И кнопка сабмита тоже должна быть внутри формы
На сервер по кнопке будет уходить только то, что написано внутри формы

2018-10-11 15:55 UTC, nex2hex commented on index.html
> +                <footer>
лучше так https://webref.ru/html/tfoot

2018-10-11 15:55 UTC, nex2hex commented on index.html
> +                <input type="text" class="input_text"
required

2018-10-11 19:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 19:21 UTC, nex2hex commented
🍏

2018-10-11 19:21 UTC, closed without merging