init
urfu-2018/markup-task-1 pull request #19
Opened 2018-10-10 20:59 UTC by AllEXEcuted

2018-10-10 20:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 18:04 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 18:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 18:14 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 18:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 18:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 18:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 18:35 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 18:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 18:42 UTC, nex2hex requested changes
🍅

2018-10-11 18:42 UTC, nex2hex commented on index.html
> +                <input type="submit" value="Подписаться">
`Не забывайте про валидацию полей формы`

2018-10-11 18:42 UTC, nex2hex commented on index.html
> +                <tr>
`Проявите фантазию и добавьте 5 разных семантичных тегов на ваш выбор`
Давай добавим https://webref.ru/html/tfoot

2018-10-14 18:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-15 13:34 UTC, nex2hex requested changes
🍅 
последняя мелкая правка

2018-10-15 13:34 UTC, nex2hex commented on index.html
> +                        <td>Ваше имя</td>
Текст "Ваше имя" должен быть внутри label, чтобы при клике по нему курсор помещался в поле ввода

2018-10-15 17:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 10:14 UTC, closed without merging