Никита Лебедев
urfu-2018/markup-task-1 pull request #2
Opened 2018-10-09 14:17 UTC by qmzik

2018-10-09 14:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-09 14:24 UTC, qmzik commented
Github Pages
https://qmzik.github.io/markup-task-1/

2018-10-11 18:26 UTC, spt30 requested changes

2018-10-11 18:26 UTC, spt30 commented on index.html
> +        <p>После вашего согласия на подписку вам будут приходить уведом
Давай сделаем как-нибудь так, чтобы не было переноса в верстке

2018-10-11 18:26 UTC, spt30 commented on index.html
> +    <div class="container-form">
>Не забывайте, что верстка формы должна быть семантичной

Давай придумаем тег посемантичнее, например, ```<article>```

2018-10-11 18:26 UTC, spt30 commented on index.html
> +            <div class="user-info">
Это список
Давай использовать теги списка

2018-10-11 18:26 UTC, spt30 commented on index.html
> +                <input id="phone" type="text" placeholder="89990007766" pattern="8\d{10}" required>
Как ты определил, какие поля являются обязательными?

2018-10-11 18:26 UTC, spt30 commented on index.html
> +                <span>Хочу получать уведомления:</span>
Это выглядит как заголовок

2018-10-11 18:26 UTC, spt30 commented on index.html
> +                <div class="notif-item">
Не сокращай названия классов
```<div class="notifications-item">```

2018-10-11 18:26 UTC, spt30 commented on index.html
> +                <input id="firstName" type="text" placeholder="Имя">
Везде можно обойтись без идентификаторов

2018-10-11 18:26 UTC, spt30 commented on index.html
> +    <div class="container-form">
И название классов желательно не писать типа "...container...", "...wrapper...", etc, если нет крайней на то необходимости

2018-10-11 18:26 UTC, spt30 commented on index.html
> +                <input id="phone" type="text" placeholder="89990007766" pattern="8\d{10}" required>
В html 5 есть более подходящий тип для этого инпута

2018-10-11 18:26 UTC, spt30 commented on index.html
> +                <input id="firstName" type="text" placeholder="Имя">
Раз ты решил обернуть это в форму, давай добавим всем заполняемым полям атрибут ```"name"```

2018-10-11 18:26 UTC, spt30 commented on index.html
> +            <p>Здравствуйте, Николай!</p>
Это заголовок

2018-10-11 18:26 UTC, spt30 commented on index.html
> +            <img src="https://img.tyt.by/n/it/0f/3/95911b.jpg" alt="Яндекс">
Тег не закрыт

2018-10-11 18:26 UTC, spt30 commented on index.html
> +    <div class="container-mail">
Тоже ```<article>```

2018-10-11 18:26 UTC, spt30 commented on index.html
> +        <div class="main">
```<section>``` или ```<main>``` можно

2018-10-11 18:26 UTC, spt30 commented on index.css
> +.container-mail img
Постарайся не использовать названия тегов в css, давай всему атрибут "class" 

Также, если ты ощущаешь нормальную вложенность, например, "родитель-ребенок", можно написать явно селектор ребенка (если в этом есть необходимость)

P.S. Скорее всего, будет отдельная лекция про то, как браузер осуществляет поиск имен, когда применяет css к странице, там будет понятно, почему стоит избегать того и другого

2018-10-11 18:26 UTC, spt30 commented on index.css
> +.container-mail img
Отступа у картинки не хватает
![image](https://user-images.githubusercontent.com/31798669/46824607-da92fa80-cdaa-11e8-8a83-27f304ff4b5d.png)
Или не у картинки (ниже комментарий про паддинги)

2018-10-11 18:26 UTC, spt30 commented on index.css
> +.container-form,
Шрифт в форме с засечками, на макете без засечек

2018-10-11 18:26 UTC, spt30 commented on index.css
> +    padding-right: 10px;
Можно объединить и написать ```padding: 0 10px 10px```, а лучше ```padding: 10px```
Привыкай к тому, что для текста паддинги всегда нужны (например, если у пользователя узкий экран, текст прижмется к его краю, что не очень хорошо)

2018-10-11 18:26 UTC, spt30 commented on index.html
> +            <a href="#">Пожаловаться</a>
Для единообразия можно тоже завернуть в ```<span>```, вдруг когда-нибудь ты захочешь добавить что-то, например ```<span><a href="#">Пожаловаться</a> (это анонимно)</span>```, а css`а уже очень много нагружено

2018-10-12 13:14 UTC, qmzik commented on index.html
> +            <img src="https://img.tyt.by/n/it/0f/3/95911b.jpg" alt="Яндекс">
+
![image](https://user-images.githubusercontent.com/26081016/46871342-8b040b80-ce4a-11e8-824a-98268be12bd4.png)
Если пробую закрыть

2018-10-12 13:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 09:29 UTC, spt30 commented on index.html
> +            <img src="https://img.tyt.by/n/it/0f/3/95911b.jpg" alt="Яндекс">
лол, ладно, пусть будет так)

2018-10-14 10:01 UTC, spt30 commented
🍏 Все хорошо) Молодец!

2018-10-14 10:01 UTC, closed without merging