Рыльских Алексей
urfu-2018/markup-task-1 pull request #20
Opened 2018-10-10 21:36 UTC by cfgi-lul

2018-10-10 21:36 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 22:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 08:29 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-12 14:26 UTC, SemyonMakhaev requested changes
🍅 

Алексей, здравствуй! Спасибо за пулл реквест!

Молодец, что используешь HTML5-валидацию полей  формы! Также круто, что вёрстка семантичная 👍 Есть несколько замечаний

Если будут вопросы - смело пиши мне в слаке)

Давай попробуем сделать решение максимально близким к макету.

На форме подписки обрати внимание на:
- [ ] Выравнивание текста
- [ ] Отступы между элементами
- [ ] Выравнивание полей для ввода между собой
- [ ] Стили для кнопки

Письмо:
- [ ] Размер шрифта
- [ ] Отступы между абзацами
- [ ] Цвет фона
- [ ] Стили ссылок
- [ ] Позиционирование элементов в футере

2018-10-12 14:26 UTC, SemyonMakhaev commented on index.css
> +    font-size: 130%;
Относительно чего задан этот размер шрифта? Можно ли здесь обойтись единицей измерения `px`?

2018-10-12 14:26 UTC, SemyonMakhaev commented on index.css
> +.string1
Давай попробуем именовать классы более семантично, чтобы было понятно, какой элемент стилизуется

2018-10-12 14:26 UTC, SemyonMakhaev commented on index.css
> +::-webkit-input-placeholder
А получится ли сделать более кроссбраузерно?

2018-10-12 14:26 UTC, SemyonMakhaev commented on index.css
> +    zoom: 1.5;
Это для того, чтобы изменить размер шрифта? Попробуй использовать [font-size](http://htmlbook.ru/css/font-size)

2018-10-12 14:26 UTC, SemyonMakhaev commented on index.css
> +.fieldSet
`camelCase` не принято использовать для именования классов CSS, поскольку это усложняет их чтение. Используй `kebab-case`

2018-10-12 14:26 UTC, SemyonMakhaev commented on index.css
> +    padding: 12px 20px;
👍

2018-10-12 14:26 UTC, SemyonMakhaev commented on index.css
> +    clear: left;
Получится ли здесь обойтись без `float`?

2018-10-12 14:26 UTC, SemyonMakhaev commented on index.html
> +                       required pattern="[0-9]{11}"><br>
Давай поддержим также городские (семизначные) номера телефонов

2018-10-12 14:26 UTC, SemyonMakhaev commented on index.html
> +                на телефон</label><br>
Попробуй обойтись без тегов `br` и указать отступы при помощи стилей

2018-10-12 14:26 UTC, SemyonMakhaev commented on index.html
> +                <img alt="Yandex" class="img" src="https://bit.ly/2RF4kVv" width="100"></p>
У картинок также нужно обязательно указывать атрибут `title`. Это необходимо для обеспечения доступности

2018-10-12 14:26 UTC, SemyonMakhaev commented on index.html
> +                <p>Уведомления будут приходить вам на этот email и на указанный вами телефон -
Вместо символа `-` используй `&mdash;` или `&ndash;`, иначе html будет невалиден

2018-10-12 18:43 UTC, cfgi-lul commented on index.css
> +    font-size: 130%;
А px лучше чем % для размера элементов, ведь % будут для разных размеров экранов работать одинаково?

2018-10-13 00:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-13 03:38 UTC, SemyonMakhaev commented on index.css
> +    font-size: 130%;
Я рекомендую `px`, потому что он проще для понимания и контроля вёрстки. Если вдруг у элемента однажды появится обёртка, у которой задан размер шрифта, то проценты будут рассчитываться уже от новой величины, и вёрстка сломается.

Но существуют и другие мнения, и вообще, это вопрос холиваров. Поэтому если ты точно уверен, какого эффекта ты собираешься достигнуть, то можно использовать проценты 😉

2018-10-13 04:12 UTC, SemyonMakhaev requested changes
🍅 

Уже почти круто!

![2018-10-13 09-05-37](https://user-images.githubusercontent.com/18099714/46901170-11126780-cec8-11e8-8109-e68bc0f522b5.png)

2018-10-13 04:12 UTC, SemyonMakhaev commented on index.css
> +    font-family: Calibri, sans-serif;
Шрифт лучше всего будет задать у глобального родительского элемента (например, `body`). Тогда шрифт унаследуется для всех остальных элементов, и браузер будет обрабатывать такой CSS более эффективно

2018-10-13 04:12 UTC, SemyonMakhaev commented on index.css
> +    font-size: 18px;
Попробуй указать все три свойства в одно правило - [font](https://developer.mozilla.org/ru/docs/Web/CSS/font)

2018-10-13 04:12 UTC, SemyonMakhaev commented on index.css
> +    font-size: 18px;
Много дублирующихся правил. Давай выделим для них отдельный класс или сгруппируем селекторы

2018-10-13 04:12 UTC, SemyonMakhaev commented on index.css
> +.input-field::placeholder
👍 

Вообще, в некоторых браузерах этот псевдоэлемент тоже не поддерживается, и используется с вендорными префиксами: https://webref.ru/css/placeholder#field_css_note. Чтобы было максимально кроссбраузерно, нужно указывать все эти префиксы, для каждого конкретного браузера применится нужный.

Но в данной задаче стопроцентной кроссбраузерности не требуется, поэтому это просто в качестве факультативного знания :sweat_smile:

2018-10-13 04:12 UTC, SemyonMakhaev commented on index.css
> +input[type='tel']
Селекторы можно группировать, чтобы код был более компактным, вот так:

```css
input[type='text'],
input[type='email'],
input[type='tel']
{
    font-size: 18px;
}
```

Но будет лучше, если ты выделишь для этих элементов отдельный класс

2018-10-13 04:12 UTC, SemyonMakhaev commented on index.css
> +    font-size: 15px !important;
Унаследованный `font-size` должен перебиваться и без `!important`, поскольку унаследованные правила не имеют специфичности

2018-10-13 04:12 UTC, SemyonMakhaev commented on index.css
> +    padding: 10px 30px 11px !important;
Давай попробуем избежать использования `!important`. Это не рекомендуется, потому что `!important` нарушает порядок применения правил.

https://developer.mozilla.org/ru/docs/Web/CSS/Specificity

2018-10-13 04:12 UTC, SemyonMakhaev commented on index.html
> +                       required pattern="^[0-9]{11}$||^[0-9]{7}$"><br>
👍

2018-10-13 04:12 UTC, SemyonMakhaev commented on index.html
> +                <input class="input-field-name" id="name" type="text" placeholder="Имя" required><br>
Ещё кое-где остался `br`

2018-10-13 08:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-13 09:20 UTC, SemyonMakhaev reviewed
:apple:

Ещё пара правок - и апрув

2018-10-13 09:20 UTC, SemyonMakhaev commented on index.css
> +    font: 18px normal Calibri, sans-serif;
👍 👍 👍

2018-10-13 09:20 UTC, SemyonMakhaev commented on index.css
> +    font-size: 18px;
`font-size: 18px` установлен у родителя. Он не наследуется по умолчанию?

2018-10-13 09:20 UTC, SemyonMakhaev commented on index.css
> +div > span
Очень общее правило. Кроме того, `span` семантически является инлайн-элементом, а не блочным. Можно вместо него использовать, например, `div`, а это правило убрать

2018-10-13 10:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 09:51 UTC, SemyonMakhaev approved these changes
Супер! Теперь всё круто, молодец! 🎉 🎉 🎉

2018-10-14 09:51 UTC, SemyonMakhaev commented on index.html
> +            <h2 class="sing" id="sing">Хочу подписаться!</h2>
Только здесь, наверное, не нужен `id`

2018-10-14 09:53 UTC, SemyonMakhaev commented
🍏

2018-10-14 09:56 UTC, SemyonMakhaev commented
:scream:

2018-10-14 10:00 UTC, SemyonMakhaev commented
@honest-hrundel 😠

2018-10-14 10:03 UTC, SemyonMakhaev commented
🍏

2018-10-14 10:03 UTC, closed without merging