Шелковкин Владимир
urfu-2018/markup-task-1 pull request #22
Opened 2018-10-11 08:06 UTC by Voldemart96Rus

2018-10-11 08:06 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 08:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 08:18 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 08:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 08:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 08:36 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 08:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 08:46 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 08:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 09:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 09:16 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 09:19 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 09:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-13 16:04 UTC, chrighter requested changes
🍅

2018-10-13 16:04 UTC, chrighter commented on index.css
> +.footer2
На странице не может быть 2 футера

2018-10-13 16:04 UTC, chrighter commented on index.css
> +.subscribeTable
Давай не будем именовать классы в `camelCase`, должно быть `.subscribe-table `

2018-10-13 16:04 UTC, chrighter commented on index.css
> +    background: #ebebeb;
Почему ты для задания цвета иногда используешь `hex`, а иногда имя цвета?

Давай приведем все к одному виду

2018-10-13 16:04 UTC, chrighter commented on index.css
> +.subscribe2
Непонятное название класса

2018-10-13 16:04 UTC, chrighter commented on index.html
> +                <p>После вашего согласия на подписку вам будет приходить уведомления на почту и телефон</p>
Это можно вынести за пределы формы, так как к самой форме данный контент не относится

2018-10-13 16:04 UTC, chrighter commented on index.html
> +                        <p>Вы подисались на уведомления о новастях Яндекс</p>
Давай исправим опечатки в тексте

2018-10-13 16:04 UTC, chrighter commented on index.html
> +                    <input type="checkbox" name="onEmail" value="на почту">на почту<br>
Давай сделаем так, что галочка в `checkbox` будет проставляться не только по нажатию на сам элемент, но и по нажатию на текст (`на почту` или `на телефон`)

2018-10-13 16:04 UTC, chrighter commented on index.html
> +                        <a href="URL">Пожаловаться.</a>
Давай исправим адреса ссылок на `#`

2018-10-13 16:04 UTC, chrighter commented on index.css
> +    margin-right: 0;
Давай два конкретных свойства запишем с помощью одного общего - `margin`

2018-10-13 16:04 UTC, chrighter commented on index.html
> +                            <input type="text" size="40" name="phone" placeholder="89990007766"
Почему решил не использовать ширину по умолчанию и сделал равной `40`?

2018-10-13 16:04 UTC, chrighter commented on index.html
> +                            <input type="email" size="40" name="email" placeholder="email@yandex.ru" required>
👍 за использование `name` и `required`

2018-10-13 16:04 UTC, chrighter commented on index.html
> +            <table class="subscribeTable">
Здорово, что для вёрстки письма используешь табличную вёрстку - это залог того, что вёрстка "не разъедется" ни в одном почтовом клиенте 🔥🔥

2018-10-13 16:04 UTC, chrighter commented on index.html
> +                <input type="submit" value="Подписаться">
Для повышения отзывчивости страницы можно добавлять выделение кликабельных элементов на `:hover` по ним

2018-10-13 16:04 UTC, chrighter commented on index.html
> +                <table>
Табличная вёрстка используется в основном для вёрстки писем, для вёрстки страницы она используется в крайних случаях

2018-10-13 16:04 UTC, chrighter commented on index.html
> +            <div class="main">
Давай добавим семантику

2018-10-13 16:04 UTC, chrighter commented on index.css
> +    float: right;
На будущее: `float` по жизни лучше вообще не использовать, так как это свойство в некоторых случаях ведет себя неочевидно, подробнее можно посмотреть здесь https://habr.com/post/142486/

Кроме этого, есть более удобные и понятные свойства

2018-10-16 09:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 09:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 09:12 UTC, Voldemart96Rus commented on index.html
> +                        <a href="URL">Пожаловаться.</a>
Если ссылка явно не указана зачем исправлять на #?

2018-10-16 09:14 UTC, Voldemart96Rus commented on index.html
> +                            <input type="text" size="40" name="phone" placeholder="89990007766"
заранее сделать во всю длину форму

2018-10-16 09:14 UTC, Voldemart96Rus commented on index.html
> +                            <input type="text" size="40" name="phone" placeholder="89990007766"
> заранее сделать во всю длину формы

2018-10-18 13:11 UTC, Voldemart96Rus commented
🔔

2018-10-19 21:05 UTC, chrighter requested changes
🍅

2018-10-19 21:05 UTC, chrighter commented on index.css
> +    box-shadow: 0 0 25px 5px rgba(50, 50, 50, 75);
Прозрачность задается в пределах [0, 1]

2018-10-19 21:05 UTC, chrighter commented on index.css
> +    box-shadow: 0 0 25px 5px rgba(50, 50, 50, 75);
Сейчас ты задаешь цвета иногда в `hex`, иногда в `rgba`, давай приведем к одному виду

2018-10-19 21:05 UTC, chrighter commented on index.html
> +                <tr class="subscribe-form">
Давай для большей семантичности будем использовать `tbody` и `tfoot`

2018-10-19 21:05 UTC, chrighter commented on index.html
> +                    Email <input type="email" name="email" class="email"
Почему тогда `email`, а не `email-user`, как с `name-user` было? (Лучше наверное даже `user-name`)

Давай приведем к одному виду

2018-10-19 21:05 UTC, chrighter commented on index.html
> +                        <img src="y.jpg" alt="Яндекс">
Давай будем располагать картинку как в макете - между первым и вторым абзацем

2018-10-19 21:05 UTC, chrighter commented on index.html
> +                    placeholder="89990007766" pattern="[0-9]{11}" required>
Вместо диапазона можно использовать символьный класс `\d`

2018-10-19 21:05 UTC, chrighter commented on index.html
> +                    <label class="checkbox"><input type="checkbox" name="onEmail"
Молодец!

Удобно ставить галочку в `checkbox` простым нажатием на текст, например, когда заполняешь форму с мобильного устройства

2018-10-19 21:05 UTC, chrighter commented on index.html
> +                    Хочу получать уведомления:<br>
Проверь везде табуляцию

2018-10-19 21:05 UTC, chrighter commented on index.html
> +                    <td colspan="2" class="subscribe2">
Неиспользуемый класс

2018-10-19 21:05 UTC, chrighter commented on index.html
> +                        <img src="y.jpg" alt="Яндекс">
Давай сделаем `alt` более понятным

2018-10-20 09:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 09:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 09:21 UTC, Voldemart96Rus commented on index.css
> +    box-shadow: 0 0 25px 5px rgba(50, 50, 50, 75);
как сделать прозрачность в hex? Я использовал rgba из-за прозрачности, почему я его не могу оставить???

2018-10-21 08:09 UTC, chrighter commented on index.css
> +    box-shadow: 0 0 25px 5px rgba(50, 50, 50, 75);
> как сделать прозрачность в hex? Я использовал rgba из-за прозрачности, почему я его не могу оставить???

![image](https://user-images.githubusercontent.com/22082557/47264535-743c7380-d532-11e8-87d0-2b7ab364d132.png)
Можно воспользоваться конвертером цветов, например, https://colorscheme.ru/color-converter.html , и получить желаемый цвет

2018-10-21 08:54 UTC, chrighter requested changes
🍅

2018-10-21 08:54 UTC, chrighter commented on index.html
> +            <p>После вашего согласия на подписку вам будет приходить уведомления на почту и телефон</p>
будУт

2018-10-21 08:54 UTC, chrighter commented on index.html
> +                Телефон <input type="text" name="phone" class="phone"
Почему класс `phone`, а не `user-phone`?

Давай сделаем единообразно

2018-10-21 08:54 UTC, chrighter commented on index.html
> +                Email <input type="email" name="email-user" class="email-user"
Почему класс `email-user`, а не `user-email`, раз уж `user-name`?

Давай сделаем единообразно, это относится к одной сущности и кажется удобнее

2018-10-21 08:54 UTC, chrighter commented on index.html
> +                <input type="submit" value="Подписаться" class="button-subscribe">
Лучше `subscribe-button`

2018-10-21 08:54 UTC, chrighter commented on index.html
> +            <table class="subscribe-table">
Таблица подписаться? Это же всего лишь письмо

2018-10-21 08:54 UTC, chrighter commented on index.html
> +                placeholder="89990007766" pattern="[\d]{11}" required>
Просто `\d`, `[]` обычно чтобы указать прямо весь набор набор символов, а тут из коробки числа уже

2018-10-21 09:05 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 09:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 09:15 UTC, Voldemart96Rus commented
Почему у меня пишет что 2 задача не сдана?  Хотя я сделал несколько дней назад?

2018-10-21 09:15 UTC, Voldemart96Rus commented
🔔

2018-10-21 16:27 UTC, Voldemart96Rus commented on index.html
> +            <p>После вашего согласия на подписку вам будет приходить уведомления на почту и телефон</p>
Извиняюсь))) делал ночью))

2018-10-21 18:54 UTC, chrighter approved these changes
🍏

2018-10-21 18:54 UTC, closed without merging