Зелинский Дмитрий
urfu-2018/markup-task-1 pull request #23
Opened 2018-10-11 08:22 UTC by Nerzull3

[Посмотреть решение](https://hruview.herokuapp.com/Nerzull3/markup-task-1/master/index.html)

2018-10-11 08:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 09:46 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 10:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 07:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 11:25 UTC, spt30 requested changes
🍅 В целом выглядит хорошо, но есть некоторые проблемы с семантикой
Можешь еще раз пересмотреть лекцию

2018-10-14 11:25 UTC, spt30 commented on index.html
> +                        <h1>Хочу подписаться!</h1>
Отступ лишний
Давай вернем на 4 пробела

2018-10-14 11:25 UTC, spt30 commented on index.html
> +                <p class="checkbox_p"><input type="checkbox">на почту</p>
Обычно такие штуки оборачивают в label:
```
<label>
    <input type="checkbox">
    на почту
</label>
```

2018-10-14 11:25 UTC, spt30 commented on index.html
> +                <article>
Слишком много ```<article>```, вообще говоря, это ```<p>```

2018-10-14 11:25 UTC, spt30 commented on index.html
> +                <article>
Постарайся понять, чем отличаются ```<article>``` и ```<section>```
Возможно, это тебе поможет:
![image](https://user-images.githubusercontent.com/31798669/46915731-fbd13200-cfc8-11e8-9723-5dd068db6f0e.png)

Обычно не вкладывают article в article или в section. article – это самостоятельная часть страницы
То есть если у блока есть заголовок, но это не специальный тег, вроде ```<nav>```, то это article

```<section>``` же подразумевает часть какого-то большого блока, зачастую однотипную повторяющуюся (не путать с ```<ul> <li>```

2018-10-14 11:25 UTC, spt30 commented on index.html
> +                    <input class="b_input" placeholder="Имя" maxlength="20" type="text">
Название класса ничего не отражает. Что такое b? Давай придумаем другое название

2018-10-14 11:25 UTC, spt30 commented on index.html
> +        <div class="subscribe_panel">
Это хорошее название класса
Давай все остальные классы назовем так, чтобы был понятен текущий контекст верстки, а не элемент, который ты хочешь иметь внутри

2018-10-14 11:25 UTC, spt30 commented on index.html
> +                <p class="msg_p">Здравствуйте, Николай!</p>
Не сокращай названия классов

2018-10-14 11:25 UTC, spt30 commented on index.html
> +                <div class="block_label">
Слишком много лишней вложенности
Обычно тут пишут просто вот так:
```
<label>
    Телефон
    <input class="b_input" placeholder="89990007766" maxlength="11" pattern="8[0-9]{10}" type="tel">
</label>
```

2018-10-14 11:25 UTC, spt30 commented on index.css
> +    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
Зачем здесь другой шрифт?

2018-10-14 11:25 UTC, spt30 commented on index.html
> +                <img class="icon" src="yandex_icon.png" alt="yandex icon">
Картинка не вставилась(

2018-10-14 15:47 UTC, Nerzull3 commented on index.html
> +                <p class="checkbox_p"><input type="checkbox">на почту</p>
Можно ли здесь сделать тег label блочным (display: block;)? Делают ли так?

2018-10-15 10:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 15:11 UTC, spt30 commented on index.html
> +                <p class="message_p">Здравствуйте, Николай!</p>
Тут опять на тег завязал название класса
Давай лучше ```message__paragraph```

2018-10-16 15:11 UTC, spt30 commented on index.html
> +                <p class="message_p">Здравствуйте, Николай!</p>
А вообще говоря, конкретно здесь уместнее заголовок вместо ```<p>```, например ```<h1>```

2018-10-16 15:11 UTC, spt30 commented on index.html
> +                <br>
Раз у тебя в этой задаче уже есть index.css, то давай отступ сделаем с помощью стилей

2018-10-16 15:11 UTC, spt30 commented on index.html
> +                <p class="checkbox_p"><input type="checkbox">на почту</p>
Да, можно, почему бы и нет
Впоследствии будут всякие спецификации наподобие flexbox, которые сами задают раскладку внутри себя

А пока да, можешь либо с помощью css создать блочный контекст вокруг, либо обернуть в ```<li>``` (семантически это список), только не забудь тогда в ```<ul>``` обернуть весь список

2018-10-16 15:50 UTC, spt30 requested changes

2018-10-16 15:50 UTC, spt30 commented on index.html
>          <br>
Тоже css-ом можно сделать, раз он тут уже есть

2018-10-16 15:50 UTC, spt30 commented on index.html
> +            <article>
Возможно, я в прошлый раз не очень понятно описал, как использовать ```<article>```, это не есть сам заголовок, это блок с(!) заголовком

То есть у тебя есть ```<article>``` – окно подписки
В нем лежат `<h1>`, `<h2>`(или `<p>`) и `<form>` (опять же, форма – это только то, что заполняется и может какой-то промежуточный контент, заголовки в форму не входят)

2018-10-16 15:50 UTC, spt30 commented on index.html
> +            <header>
Сорян, в прошлый раз проглядел: формально страница включает в себя ```<header>```, ```<main>``` и `<footer>`, лежащие плоско относительно друг друга

Здесь как будто бы две отдельных страницы: форма и письмо, поэтому давай уберем тут `<header>`, а в письме `<footer>`
здесь можно просто убрать, а в письме замени на что-нибудь, например, `<section>`

2018-10-16 15:50 UTC, spt30 commented on index.html
> +        <form class="letter_panel">
Плохой тег, это не форма, тут ничего не надо заполнять и нет никакого submit'а

2018-10-16 15:50 UTC, spt30 commented on index.html
> +                <label class="content_label" for="username">Ваше имя</label>
Можно тут и ниже обернуть `<label>` вокруг `<input>`, тогда не придется заморачиваться с id

2018-10-16 15:50 UTC, spt30 commented on index.html
> +        <form class="letter_panel">
Да и в целом, его можно убрать, в него только один `<div>` вложен, так что он ни на что не повлияет

2018-10-16 15:50 UTC, spt30 commented on index.html
> +            <div class="letter_content">
Тоже `<article>`

2018-10-16 15:50 UTC, spt30 commented on index.html
> +                <img class="icon" src="yandex_icon.PNG" alt="yandex icon">
Зря заменил, правильно было в lowercase написано с начала

2018-10-16 15:50 UTC, spt30 commented on index.html
> +                <footer class="footer_panel_of_letter">
При чем тут панель? И ниже тоже

2018-10-16 15:50 UTC, spt30 commented on index.html
> +            <section class="block_content">
Это все не `<section>`ы, это `<li>`, обернутые в список

2018-10-16 15:50 UTC, spt30 commented on index.html
> +            <div class="letter_content">
почему не просто letter?

2018-10-16 15:50 UTC, spt30 commented on index.html
> +                <img class="icon" src="yandex_icon.PNG" alt="yandex icon">
letter__icon

2018-10-16 15:50 UTC, spt30 commented on index.css
> +form.subscribe_panel
Время скоротечно, и его надо экономить, поэтому лишний раз не теги лучше не завязываться
Авось он поменяется, придется css тоже менять :(

2018-10-16 15:50 UTC, spt30 commented on index.css
>      border: 2px solid red;
Нормальная тема, в прошлый раз не заметил
Молодец, что заботишься о пользователях! 👍

2018-10-16 15:50 UTC, spt30 commented on index.css
>      border: 2px solid red;
Попробуй еще поставить `outline: none`, чтобы двойной обводки не было

2018-10-17 08:56 UTC, Nerzull3 commented on index.css
> +form.subscribe_panel
Я интуитивно предполагал, что так могут делать специально даже не с целью увеличения специфичности, а с целью как-то ограничить свойства, описанные в этом блоке что ли, о эти свойства применяются только для формы с таким классом... Вот и хотел узнать, правильно ли я поступил :)

2018-10-17 08:58 UTC, Nerzull3 commented on index.html
> +            <section class="block_content">
А я как-то подумал и решил, что разбить это на section'ы было бы разумно, так как у меня имеются пусть и не столь содержательные, но подобные, даже одинаковые блоки (label и input).

2018-10-17 09:05 UTC, Nerzull3 commented on index.html
> +                <label class="content_label" for="username">Ваше имя</label>
Я пытался сделать изначально label, в котором бы был размещен текст и input, но мне не понравилось выравнивание строк ввода input в css-файле. Я пытался брать конкретные input с помощью селекторов атрибутов и соответственно указывать им margin-left, чтобы все input-блоки были выровнены относительно друг друга, так как текст имел разную длину. Мне не понравилось такое выравнивание, слишком уж костыльное показалось. Может, я не прав, и так действительно делают. Но более красивым, на мой взгляд, решением мне показалось обернуть label и input в section.

2018-10-17 09:06 UTC, Nerzull3 commented on index.html
> +                <label class="content_label" for="username">Ваше имя</label>
Как я посмотрел, во второй задаче markup была такая связка label и input

2018-10-17 09:32 UTC, Nerzull3 commented on index.html
> +                <p class="message_p">Здравствуйте, Николай!</p>
Тогда придется переопределять стили, установленные по-умолчанию браузером, для h1, или h2, например. Почему здесь уместнее использовать всё-таки заголовок, а не параграф? Мне это не совсем понятно.

2018-10-17 10:13 UTC, Nerzull3 commented on index.html
> +            <div class="letter_content">
class="letter_panel" - почему этот класс не назван "letter"? Если это так, то мне больше представляется панель, на которой я размещаю элементы, которые будут относиться к письму. Звучит в более техническом плане. А письмо - объект со стороны пользователя. Как-то так :)

2018-10-17 16:52 UTC, Nerzull3 commented on index.html
> +            <section class="block_content">
Почитал про section'ы, посмотрел примеры: да, всё-таки тут не подходят они

2018-10-17 17:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 17:12 UTC, Nerzull3 commented on index.html
> +                <img class="icon" src="yandex_icon.PNG" alt="yandex icon">
очень странно, но почему-то при lowercase он не отображает картинку на гитхабе... На локальной машине всё хорошо

2018-10-17 17:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 17:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 17:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 17:22 UTC, Nerzull3 commented
Странно, но почему-то картинка не добавлялась из консоли. По поводу изменений: я решил привести цвета в css-файле к одному формату hex. Наверное, держать цвета в одном формате - хороший тон :)

2018-10-18 09:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-18 15:52 UTC, spt30 commented
>Наверное, держать цвета в одном формате - хороший тон
да, ты прав
пока я старался не заморачиваться за css

2018-10-18 16:07 UTC, spt30 approved these changes
Теперь ты молодец! 🥇

2018-10-18 16:07 UTC, spt30 commented on index.html
> +                     pattern="8[0-9]{10}" type="tel">
Вай-вай, зря перенес
Если уж переносишь, переноси все, как-то так:
```
<input
    id="user_telephone"
    placeholder="89990007766"
    maxlength="11"
    pattern="8[0-9]{10}"
    type="tel"
    >
```

2018-10-18 16:07 UTC, spt30 commented on index.html
> +                    <label class="content_label" for="username">Ваше имя</label>
так и не обернул `<label>` вокруг `<input>`'a
ладно, в будущем разберешься, как можно выравнивать по-другому
так тоже ок

2018-10-18 16:07 UTC, spt30 commented
🍏

2018-10-18 16:07 UTC, closed without merging

2018-10-18 16:21 UTC, Nerzull3 commented on index.html
> +                     pattern="8[0-9]{10}" type="tel">
Я бы не переносил, если бы тесты не заставляли) Самому неприятно было это делать