subscription on news
urfu-2018/markup-task-1 pull request #25
Opened 2018-10-11 13:04 UTC by VicClone

2018-10-11 13:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 06:37 UTC, dotokoto requested changes
Маловато семантичных тегов. Попробуй посмотреть в сторону `header`, `footer` и добавить еще больше семантики

2018-10-16 06:37 UTC, Dotokoto commented on index.html
> +            <img src="orig.png" width="200" alt="yandex">
А сама картинка где? Нужно положить ее в репозиторий рядом с html файлом и закоммитить, чтобы она подтянулась

2018-10-16 06:37 UTC, Dotokoto commented on index.html
> +        <h2>Хочу подписаться!</h2>
Почему именно `h2`, а не `h1`?

2018-10-16 06:37 UTC, Dotokoto commented on index.html
> +            <div>
Для чего эти дополнительные обертки? Они точно нужны?

2018-10-16 06:37 UTC, Dotokoto commented on index.html
> +                <label for="ntf-email">На почту</label>
Это список настроек, можно оформить его семантичнее

2018-10-16 13:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 13:25 UTC, VicClone commented on index.html
> +            <img src="orig.png" width="200" alt="yandex">
Картинку добавил

2018-10-16 14:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 14:57 UTC, VicClone commented on index.html
> +        <h2>Хочу подписаться!</h2>
Изменил на h1, подумал это не такая важная часть для h1

2018-10-16 14:58 UTC, VicClone commented on index.html
> +            <div>
Эти обертки просто для блочной структуры, изменил div на p

2018-10-16 14:59 UTC, VicClone commented on index.html
> +                <label for="ntf-email">На почту</label>
Выделил в отдельный fieldset. Это имелось ввиду?

2018-10-19 09:35 UTC, dotokoto approved these changes

2018-10-19 09:35 UTC, closed without merging