Петрова Дарья
urfu-2018/markup-task-1 pull request #30
Opened 2018-10-11 16:14 UTC by PetrovaDaria

2018-10-11 16:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 16:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 18:47 UTC, spt30 requested changes
Давай для начала приведем задачу к тому виду, который на макете

2018-10-12 03:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 13:18 UTC, spt30 requested changes
🍅В прошлый раз не посмотрел, сейчас глупо еще раз заставлять переделывать, но в общем:
сейчас уже таблицами не верстают совсем: это не семантично, неудобно и плохо поддерживаемо, давай в будущем избегать такого

2018-10-14 13:18 UTC, spt30 commented on index.html
> +                    <td><input type="text" id="name" placeholder="Имя" pattern="^[А-Яа-яЁё]+$"></td>
Можно обходиться без атрибута id:
```
<label>
    Ваше имя
    <input ... >
</label>
```
Во всех остальных местах тоже

2018-10-14 13:18 UTC, spt30 commented on index.html
> +                <h2>Хочу подписаться!</h2>
Это все-таки самый главный заголовок, пусть он будет ```<h1>```, стили css-ом поправишь

2018-10-14 13:18 UTC, spt30 commented on index.html
> +                        <td><img src="yandex.gif" alt="yandex" width="80"></td>
За формат отображения на сегодняшний день отвечает CSS, давай ширину туда унесем

2018-10-14 13:18 UTC, spt30 commented on index.html
> +    <div class="letter-container">
Зачем-то лишний ```<div>```, есть же уже ```<main>```

2018-10-14 15:04 UTC, PetrovaDaria commented on index.html
> +                    <td><input type="text" id="name" placeholder="Имя" pattern="^[А-Яа-яЁё]+$"></td>
К вопросу о таблице в форме: я не хотела ее использовать, но, используя ее, все inputы выравнялись по левому краю. Как этого можно было добиться без таблиц? По поводу id - можно конечно и без него, но разве так правда лучше? Если label и input вдруг надо будет перенести подальше друг от друга, то можно будет не переписывать ничего

2018-10-14 16:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 18:51 UTC, spt30 commented on index.html
> +                    <td><input type="text" id="name" placeholder="Имя" pattern="^[А-Яа-яЁё]+$"></td>
Привет!
Сейчас есть новые средства, такие как flexbox и grid, первые уже активно используются Можно ими делать в принципе, но в рамках этой задачи вам, кажется, нельзя их использовать
Поэтому есть вариант с ```float: right```

Но поскольку это первая задачка, она на понимание и семантику, то тут не сильно важно как выравнены элементы, если что-то еще интересно будет – пиши в слаке или где тебе удобно, ПР закрываю, ты молодец)

2018-10-14 18:51 UTC, spt30 commented
🍏 Молодец!

2018-10-14 18:51 UTC, closed without merging