Бессонов Роман
urfu-2018/markup-task-1 pull request #31
Opened 2018-10-11 16:27 UTC by Bolkonyashka

[Посмотреть решение](https://hruview.herokuapp.com/Bolkonyashka/markup-task-1/master/index.html)

2018-10-11 16:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-12 13:58 UTC, chrighter requested changes
🍅

2018-10-12 14:00 UTC, chrighter commented on index.css
> +    background-color: rgb(248, 248, 248);
Почему ты иногда задаешь цвета с `rgb`, а иногда именами?

Давай приведём все к одному виду, лучше использовать `hex`

2018-10-12 14:00 UTC, chrighter commented on index.css
> +.block-input
Кажется, это не используется

2018-10-12 14:01 UTC, chrighter commented on index.css
> +    margin-right: 15px;
Давай вместо трёх конкретных свойств использовать одно общее - `margin`

2018-10-12 14:02 UTC, chrighter commented on index.css
> +    float: right;
На будущее: `float` по жизни лучше вообще не использовать, есть более удобные и понятные свойства

2018-10-12 14:02 UTC, chrighter commented on index.css
> +.form-submit-button:hover
👍

2018-10-12 14:30 UTC, chrighter requested changes
🍅

2018-10-12 14:30 UTC, chrighter commented on index.css
> +.modified-a
Не очень понятное название класса

Для повышения отзывчивости страницы можно еще добавить выделение при наведении на ссылку

2018-10-12 14:30 UTC, chrighter commented on index.html
> +        <h2 class="form-header">Хочу подписаться!</h2>
Почему ты и используешь `h2`, а не `h1`, если на странице ещё не использовался `h1`?

2018-10-12 14:30 UTC, chrighter commented on index.html
> +                    Ваше имя<input class="form-input" name="name" type="text" placeholder="Имя">
Давай добавим `required`

2018-10-12 14:30 UTC, chrighter commented on index.html
> +                    Email<input class="form-input" name="email" type="email" placeholder="email@yandex.ru">
Давай добавим валидацию полей формы

2018-10-12 14:30 UTC, chrighter commented on index.html
> +                    Телефон<input class="form-input" name="phone" type="tel" placeholder="89990007766">
Круто, что используешь `name` 👍

2018-10-12 14:30 UTC, chrighter commented on index.html
> +                <div class="checkbox-field">
Давай добавим возможность выставления галочки в `checkbox` по нажатию на текст (`на почту` или `на телефон`)

2018-10-12 14:30 UTC, chrighter commented on index.html
> +            <button class="form-submit-button" type="submit">Подписаться</button>
Для того, чтобы страница стала более отзывчивой, можно кроме выделения цветом можно менять внешний вид курсора с помощью  `cursor: pointer`

2018-10-12 14:30 UTC, chrighter commented on index.html
> +    <div class="content-wrapper mail-content">
На будущее: для верстки писем лучше использовать табличную верстку - это залог того, что верстка "не разъедется" ни в одном почтовом клиенте

Подробнее можно посмотреть здесь: https://habr.com/post/252279/

2018-10-12 14:30 UTC, chrighter commented on index.html
> +            </div>
Давай добавим семантики

2018-10-12 16:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-12 16:10 UTC, Bolkonyashka commented
🍏

2018-10-12 16:12 UTC, Bolkonyashka commented
А яблочко всегда нужно отправлять после поправок кода? :)

2018-10-20 08:13 UTC, chrighter requested changes
🍅

2018-10-20 08:13 UTC, chrighter commented on index.html
> +                    pattern="^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$" required>
Невалидный номер 899900077666 у тебя подходит

2018-10-20 08:13 UTC, chrighter commented on index.html
> +            <div class="form-field">
Все равно не хватает семантики (очень много `div`)

2018-10-20 08:13 UTC, chrighter commented on index.html
> +            <p>Для подтверждения перейдите по <a href="#" class="no-underline-a">ссылке</a></p>
Непонятное название класса, можно просто `link` и тд

2018-10-20 08:13 UTC, chrighter commented on index.html
> +            <div class="footer-info right-float">
Класс Правый float?)

2018-10-20 08:13 UTC, chrighter commented on index.html
> +                    <label class="pointer-cursor">
Давай не будем называть классы `css`-свойствами элементов: представь, что у тебя огромный проект, тебе разве будет через неделю понятно, о каком элементе идет речь?

2018-10-20 11:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 11:44 UTC, Bolkonyashka commented
🍏 Поправил)

2018-10-20 12:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 09:11 UTC, chrighter requested changes
🍅

2018-10-21 09:11 UTC, chrighter commented on index.html
> +            <div class="footer-info right-side-info">
Правая сторона информация?

Картинка тоже расположена на правой стороне письма, например
Можно наверное `copyright` назвать или еще как-нибудь более конкретно

2018-10-21 09:11 UTC, chrighter commented on index.html
> +            <div class="footer-info left-side-info">
Левая сторона информация?

Давай конкретнее

2018-10-21 09:11 UTC, chrighter commented on index.html
> +                    <input class="modified-checkbox" type="checkbox">на телефон
`modified-checkbox`?

Почитай про `input[type="checkbox"]`

2018-10-21 09:11 UTC, chrighter commented on index.html
> +            <img class="mail-img" src="yan.jpg" alt="Yandex">
Слишком общий `alt`

2018-10-21 09:11 UTC, chrighter commented on index.html
> +            </div>
Здесь тоже не хватает семантики

2018-10-21 09:11 UTC, chrighter commented on index.html
> +                    pattern="^(8|\+7)[0-9]{10}$" required>
👍

2018-10-21 09:11 UTC, chrighter commented on index.html
> +        <section class="subscribe-info">
Почему в письме тоже `subscribe-info`?
Если пришло письмо, то человек уже подписался

2018-10-21 10:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 10:02 UTC, Bolkonyashka commented
🍏 И еще поправил :)

2018-10-21 17:35 UTC, chrighter approved these changes
🍏

2018-10-21 17:35 UTC, closed without merging