Гинзбург Лиза
urfu-2018/markup-task-1 pull request #34
Opened 2018-10-11 17:51 UTC by LizaGin

2018-10-11 17:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 17:57 UTC, anykk commented on index.html
> +        <img alt="yandexLogo" width="120px" height="60px"
Тег не закрывается

2018-10-11 18:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-11 18:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-12 19:38 UTC, SemyonMakhaev requested changes
🍅 

Елизавета, привет! Спасибо за пулл реквест)
Вёрстка получилась действительно семантичной и доступной. Здорово реализовала валидацию полей формы 👍 Есть несколько замечаний.

Если будут вопросы - обязательно пиши мне в слаке)

Давай попробуем решение приблизить максимально к макету. Ниже на скриншотах показал несоответствия с дизайном

![1](https://user-images.githubusercontent.com/18099714/46890318-dc7abd80-ce7f-11e8-83aa-8334fb987dc4.png)

![2](https://user-images.githubusercontent.com/18099714/46890340-f3b9ab00-ce7f-11e8-8d07-5986241255cd.png)

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.css
> +h1
Это очень общий селектор. Если на твоей странице вдруг появится другой элемент `h1`, то стили применятся к нему. Чтобы стилизовать только нужные тебе элементы, используй селектор класса

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.css
> +    float: right;
Попробуй здесь обойтись без `float`. Судя по макету, картинка находится в потоке с остальными элементами и не имеет "плавающей" природы

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.css
> +    padding: 2%;
Относительно чего рассчитываются все эти проценты? Возможно, в данном случае код станет более контролируемым и понятным, если задать фиксированные размеры и отступы в `px`

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.css
> +    background: white;
Здесь меняется только цвет фона, поэтому использование свойства `background` избыточно. Достаточно применить [background-color](http://htmlbook.ru/css/background-color)

```css
background-color: white;
```

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.css
> +    font-size: 90%;
Аналогично про проценты. Весьма неочевидно, от какого значения будут рассчитываться эти `90%`. Попробуй использовать `px`.

И в других местах тоже

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.css
> +.registrationWindowWrapper
`camelCase` не принято использовать для именования классов CSS, поскольку это усложняет их чтение. Используй `kebab-case`

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.css
> +    border: 1px solid lightgray;
Одно и то же правило много где продублировано. Давай попробуем либо выделить отдельный класс, либо объединить селекторы с одинаковыми правилами. Так применение стилей браузером будет более эффективным

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.css
> +    float: left;
Аналогично, попробуй здесь не использовать `float`

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.css
> +    background: rgb(248, 248, 248);
Цвета следует указывать во всём проекте в одной и той же нотации для сохранения общности. При этом лучше использовать `hex`-нотацию, так как она интуитивно более понятна, и ей проще воспользоваться при переносе цветов из макета в интерфейс

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.html
> +                     placeholder="email@yandex.ru" pattern="[a-zA-Z0-9._-]+@[a-z]+\.[a-z]{2,4}$" required>
Шаблон принимает невалидные email-адреса, например `.@q.q`

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.html
> +                     placeholder="89990007766" pattern="[0-9]{11}" maxlength="11" required>
👍 👍 👍

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.html
> +                     placeholder="89990007766" pattern="[0-9]{11}" maxlength="11" required>
Давай попробуем поддержать также городские (семизначные) номера телефонов

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.html
> +        <table>
Табличную вёрстку используют чаще всего в случаях, когда имеют дело именно с таблицами или с чем-то похожим. Применима ли она в данном случае?

2018-10-12 19:38 UTC, SemyonMakhaev commented on index.html
> +                    <img width="120" height="60" alt="yandexLogo"
У тега `img` также обязательно нужно указывать атрибут `title`. Это необходимо для обеспечения доступности

2018-10-14 14:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 15:11 UTC, LizaGin commented on index.html
> +                    <img width="120" height="60" alt="yandexLogo"
Привет
Надеюсь, что получилось исправить всё, за исключением использования float  с label
Читала пару статей, касательно вёрстки писем, в которых настоятельно рекомендуют использовать табличную верстку, считаю в данном случае её уместной, единственное, с инлайновыми стилями не проходит линтинг, пришлось вынести всё в css

2018-10-14 17:52 UTC, SemyonMakhaev commented on index.html
> +                    <img width="120" height="60" alt="yandexLogo"
Ок, согласен

2018-10-14 18:28 UTC, SemyonMakhaev requested changes
🍅 

Выглядит точно как на макете, супер! Есть пара правок, в остальном всё здорово

2018-10-14 18:28 UTC, SemyonMakhaev commented on index.css
> +    background-color: white;
Опять же, цвета нужно указывать в одной нотации

2018-10-14 18:28 UTC, SemyonMakhaev commented on index.html
> +                     placeholder="89990007766" pattern="[0-9]{11}|[0-9]{7}" maxlength="11" required>
👍

2018-10-14 18:28 UTC, SemyonMakhaev commented on index.html
> +                    <br>и на указанный вами телефон - <br>+79ххххххх78.</p>
Зачем тег `br`? Нельзя ли сделать отступы при помощи стилей?

2018-10-14 18:28 UTC, SemyonMakhaev commented on index.html
> +                     pattern="[a-zA-Z]+[._-]*[a-zA-Z]+[0-9]*@[a-z]+\.[a-z]{2,4}$" required>
Выглядит очень надёжно 😅

2018-10-14 18:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 18:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 18:43 UTC, LizaGin commented on index.html
> +                     pattern="[a-zA-Z]+[._-]*[a-zA-Z]+[0-9]*@[a-z]+\.[a-z]{2,4}$" required>
Заменила цвет, который пропустила + убрала br
Главное, чтобы был правильным 😄

2018-10-14 19:14 UTC, SemyonMakhaev commented
🍏 

Получилось очень качественно, молодец!

2018-10-14 19:14 UTC, closed without merging