Гарелышев Арсений
urfu-2018/markup-task-1 pull request #4
Opened 2018-10-09 16:29 UTC by MonstraG

2018-10-09 16:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-09 16:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-09 16:43 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-09 16:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 18:57 UTC, SemyonMakhaev requested changes
🍅 

Арсений, привет! Спасибо за пулл реквест, получилось весьма здорово 👍 CSS-правила использованы уместно, и вёрстка семантичная. Есть несколько замечаний.

Если возникнут какие-нибудь вопросы или долго не буду проверять, смело пиши мне в слаке, или в телеграмме, или где угодно.

Для начала пара вопросов по дизайну 😃 Давай попробуем решение максимально приблизить к макету. На скриншотах ниже отметил несколько несоответствий

Форма подписки:
- [ ] Поле для ввода на макете больше по высоте
- [ ] Обрати внимание на отступы у полей
- [ ] Чекбоксы на макете больше
- [ ] Попробуй стилизовать кнопку
- [ ] Шрифт можно сделать немного меньше
- [ ] Поля для ввода нужно выровнять между собой

Письмо:
- [ ] Обрати внимание на стиль логотипа
- [ ] Слишком большие отступы между абзацами
- [ ] Попробуй стилизовать ссылки, как на макете

![](https://user-images.githubusercontent.com/18099714/46826416-61e26d00-cdaf-11e8-82c1-af554d2ae8f2.png)

![3](https://user-images.githubusercontent.com/18099714/46826694-167c8e80-cdb0-11e8-87c2-9f031ed54cd9.png)



![](https://user-images.githubusercontent.com/18099714/46826664-006ece00-cdb0-11e8-8418-c744ac94ecc5.png)

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.css
> +    font-size: 18px;
Можно записать в одно правило при помощи свойства [font](https://developer.mozilla.org/ru/docs/Web/CSS/font)

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.css
> +    height: 425px;
Стоит ли фиксировать ширину и высоту этого элемента? А если когда-нибудь текст в форме поменяется? Не будет ли удачнее, если размеры формы будут динамическими в зависимости от контента?

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.css
> +    padding-right: 25px;
Удачнее будет использовать свойство [padding](http://htmlbook.ru/css/padding), чтобы обойтись одним правилом

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.css
> +input
Используй селектор класса. В случае если на странице вдруг появится другой контрол с тегом `input`, ты будешь готов к этому, и твой селектор стилизует только нужные тебе элементы

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.css
> +    margin: .25rem;
Такие специфичные единицы измерения следует использовать только в весьма специфичных ситуациях. Для решения твоей задачи здесь будет достаточно использовать `px`

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.css
> +.fieldInputs
`camelCase` не принято использовать для именования классов CSS, поскольку это усложняет их чтение. Используй `kebab-case`

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.css
> +
Лишняя пустая строка 😄

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.css
> +    padding-right: 25px;
Аналогично насчёт свойства `padding`

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.css
> +    margin: 0 -25px 0 -25px;
В данном случае можно записать `margin` в короткой нотации:

```css
margin: 0 -25px;
```

https://developer.mozilla.org/ru/docs/Web/CSS/margin

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.css
> +    float: left;
Попробуй в этой задаче обойтись без `float`. Кажется, здесь идейно весь контент - это набор последовательных блоков в потоке, и ни один из них не имеет "плавающей" природы

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.css
> +img
Тоже слишком общий селектор. Лучше выделить отдельный класс

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.html
> +                    <br>
Тебе точно нужен здесь элемент `br`? Получится ли сделать подходящий отступ при помощи стилей? И в других местах аналогично

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.html
> +                        pattern="[0-9]{11}"><br>
Давай попробуем поддержать также городские (семизначные) номера телефонов

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.html
> +                <label><input type="checkbox" class="checkbox" name="mailNotifications">на телефон</label><br>
Почему `input` находится внутри элемента `label`? В предыдущих местах ты сделал наоборот. А как правильно?

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.html
> +            <img alt="Yandex logo" src="logo.png" width="125">
У тега `img` также нужно обязательно указывать элемент `title`. Это необходимо для обеспечения доступности

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.html
> +                    <input class="field" type="text" id="nameField" placeholder="Имя" required>
Если сможешь стилизовать placeholder, как на макете, - отдельный респект :wink:

2018-10-11 18:57 UTC, SemyonMakhaev commented on index.html
> +                    <input class="field" type="tel" id="telField" placeholder="89990007766" required
👍 👍 👍

2018-10-12 12:57 UTC, SemyonMakhaev commented on index.html
> +                    <input class="field" type="tel" id="telField" placeholder="89990007766" required
Только здесь, наверное, не нужен `id`

2018-10-13 05:19 UTC, MonstraG commented
Прежде всего, хочу заметить, что у меня поля имеют одинаковый отступ.

![default](https://user-images.githubusercontent.com/17963791/46901671-47a0b000-ced1-11e8-9380-d85c87c31fae.png)

2018-10-13 05:20 UTC, MonstraG commented on index.html
> +                <label><input type="checkbox" class="checkbox" name="mailNotifications">на телефон</label><br>
Не представляю как правильно, просто тогда мне было необходимо их разделить, что бы их правильно стилизовать, ну тут конечно же так же могу сделать.

2018-10-13 05:25 UTC, MonstraG commented on index.css
> +    height: 425px;
Я просто открыл картинку прямо из задания и посмотрел в ее размеры, и написал похожие, кратные 25.

2018-10-13 05:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-13 05:29 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-13 05:29 UTC, MonstraG commented on index.css
> +
Там еще были пустые кстати. А линтер почему не ругается?

2018-10-13 05:34 UTC, MonstraG commented on index.css
> +img
Поскольку всего одна картинка, вот и общий селектор, я пытался стили максимально общими сделать.

2018-10-13 05:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-13 05:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-13 05:46 UTC, MonstraG commented
Да и кстати, по мне так логотип без белого фона таки хуже чем этот.

2018-10-13 08:51 UTC, SemyonMakhaev commented
> Прежде всего, хочу заметить, что у меня поля имеют одинаковый отступ (firefox, 1336x768)

То, что в firefox всё выглядит, как надо, это хорошо! Но надо стремиться к тому, чтобы интерфейс совпадал с дизайном хотя бы в основных современных браузерах: chrome, firefox, opera, safari

> Да и кстати, по мне так логотип без белого фона таки хуже чем этот.

Это вопрос к дизайнеру и к его чувству прекрасного 😆

2018-10-13 08:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 08:52 UTC, SemyonMakhaev commented on index.css
> +    height: 425px;
Ок

2018-10-13 08:53 UTC, MonstraG commented
Ват. Не пройден линт, но он пройден?

2018-10-13 08:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-13 08:58 UTC, SemyonMakhaev commented on index.html
> +                <label><input type="checkbox" class="checkbox" name="mailNotifications">на телефон</label><br>
На самом деле в ситуации, когда `input` находится внутри `label`, в старых браузерах функциональность активации поля при нажатии на лейбл может не работать. Но старые IE в этой задаче поддерживать необязательно, поэтому можно и так, и так

2018-10-14 08:16 UTC, MonstraG commented
Точно, я забыл про телефон +7

2018-10-14 08:29 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 11:20 UTC, SemyonMakhaev requested changes
🍎 

Выглядит уже очень круто! Есть пара небольших правок

2018-10-14 11:20 UTC, SemyonMakhaev commented on index.css
> +    font: 16px Verdana, sans-serif;
👍

2018-10-14 11:20 UTC, SemyonMakhaev commented on index.css
> +::placeholder
👍 👍 👍 

Вообще, в некоторых браузерах этот псевдоэлемент тоже не поддерживается, и используется с вендорными префиксами: https://webref.ru/css/placeholder#field_css_note. Чтобы было максимально кроссбраузерно, нужно указывать все эти префиксы, для каждого конкретного браузера применится нужный.

Но в данной задаче стопроцентной кроссбраузерности не требуется, поэтому это просто в качестве факультативного знания :sweat_smile:

2018-10-14 11:20 UTC, SemyonMakhaev commented on index.css
> +    border: 2px solid #eee;
Цвета следует указывать во всём проекте в одной и той же нотации для сохранения общности. При этом лучше использовать `hex`-нотацию, так как она интуитивно более понятна, и ей проще воспользоваться при переносе цветов из макета в интерфейс

2018-10-14 11:20 UTC, SemyonMakhaev commented on index.css
> +    border: 1px solid lightgray;
Правило многократно продублировано в коде. Нужно вынести в отдельный класс или сгруппировать селекторы

2018-10-14 11:20 UTC, SemyonMakhaev commented on index.html
> +                        pattern="^(8\d{10}|\d{7}|\+7\d{10})$">
Супер!

2018-10-14 17:56 UTC, MonstraG commented
Красное яблочко это не легально.

2018-10-14 18:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 19:39 UTC, SemyonMakhaev commented
> Красное яблочко это не легально.

Это уже яблочко, но ещё красное 😄

2018-10-14 19:54 UTC, SemyonMakhaev commented
🍏

Молодец, что написал стили!
Получилось очень круто и качественно.

2018-10-14 19:54 UTC, closed without merging