Орлов Илья
urfu-2018/markup-task-1 pull request #41
Opened 2018-10-12 11:02 UTC by Orilow

2018-10-12 11:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-12 11:07 UTC, Orilow commented
Здравствуйте!
Пара вопросов: 
Я не смог отцентрировать строки в выборке "хочу получать увеломления", как это сделать?
Какой тип написания классов нужно использовать в html? camelCase или через тире?

2018-10-16 09:21 UTC, dotokoto requested changes
Вообще в этой задаче не требовались стили. Но молодец, что сделал 👍 Я не буду сейчас особо ревьюить css, так как задачи на него будут дальше ). А вот html надо подправить.
Ну и можешь не выравнивать чекбоксы, этому вас еще научат потом )

2018-10-16 09:21 UTC, dotokoto commented on index.html
> +        <div class="mainblock">
1) Дальше отступы съехали, `h1` находится на этом же уровне
2) Точно нужна эта обертка? Почему нельзя эти же стили повесить на `main`?

2018-10-16 09:21 UTC, dotokoto commented on index.html
> +                <div class="inputblock">
Тут тоже что-то странное с отступами, они то большие, то маленькие. Сделай везде одинаково

2018-10-16 09:21 UTC, dotokoto commented on index.html
> +                        <span>Ваше имя</span>
Несемантично, есть же тег `<label>`, используй его. Причем давай сделаем так, чтобы по клику на текст наводился фокус на соответствующее поле. Это тоже делается с помощью тега `<label>`

2018-10-16 09:21 UTC, dotokoto commented on index.html
> +                            pattern="[a-zA-Zа-яА-я]+">
С такими паттернами нужно быть аккуратнее. В этот диапазон не попадает буква `ё`
<img width="595" alt="2018-10-16 11-50-15" src="https://user-images.githubusercontent.com/8973726/46997709-cf88f300-d139-11e8-9a19-6e3d440451b1.png">

2018-10-16 09:21 UTC, dotokoto commented on index.html
> +                </div>
Очень много дивов, может можно обойтись без них, или заменить на что-нибудь более семантичное?

2018-10-16 09:21 UTC, dotokoto commented on index.html
> +                        <input type="text" placeholder="email@yandex.ru" required pattern="\S+@[a-z]+.[a-z]+">
В регулярке неэкранированная `.` сработает, как один любой символ. Нужно заэкранировать

2018-10-16 09:21 UTC, dotokoto commented on index.html
> +        <p>Хочу получать уведомления на:</p>
Это скорее заголовок блока, чем просто абзац

2018-10-16 09:21 UTC, dotokoto commented on index.html
> +        <input type="checkbox" id="cbone" class="checkbox">
Можно оформить в список, это же список настроек

2018-10-16 09:21 UTC, dotokoto commented on index.html
> +        <div class="footer">
Опять же, нужна ли эта обертка? Может достаточно `<footer>` будет?

2018-10-16 09:21 UTC, dotokoto commented on index.html
> +                <div class="footerLeft">
Вообще, в html обычно не принято писать через `camelCase`. Можно не переделывать, но на будущее учесть

2018-10-16 09:21 UTC, dotokoto commented on index.html
> +        div.mainblock{
Здесь везде будет достаточно селектора по классу `.mainblock`, без тега

2018-10-16 09:21 UTC, dotokoto commented on index.html
> +        div.prepare-for-footer{
У тебя сейчас названия классов все разные. Где-то через дефисы, где-то в `camelCase`. Приведи к единому виду

2018-10-20 16:13 UTC, Orilow commented on index.html
> +        <div class="mainblock">
я посчитал что `main` это обертка над основным контентом, чтобы он отображался в поисковиках браузера(насколько я понял). А вешать стили на этот `main` как-то непривычно чтоли. Или это нормально?

2018-10-20 16:54 UTC, Orilow commented on index.html
> +        <input type="checkbox" id="cbone" class="checkbox">
сделал, но стало хуже выглядеть(

2018-10-20 17:02 UTC, Orilow commented on index.html
> +        div.mainblock{
так также понятнее. Однажды оставишь без тега, создашь класс с таким же названием но для другого тега и ищи свищи ошибки

2018-10-20 17:18 UTC, Orilow commented on index.html
> +                </div>
А стоит ли? "Дивная" верстка ставит все на свои места, все понятно-в каком блоке что есть.
Или в этом состоит суть задания?

2018-10-20 17:19 UTC, Orilow commented on index.html
> +        div.mainblock{
или подразумевается именно для это класса?

2018-10-20 17:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-20 17:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 17:58 UTC, Orilow commented on index.html
> +        div.prepare-for-footer{
так, я же исправил эту проблему. Почему она не пометилась `Outdated` ?

2018-10-20 18:00 UTC, Orilow commented
я еще не сильно разбираюсь как работают здесь requested changes, поэтому закрыл все, но это не помогло мне пройти некоторые, хотя я сделал что написано

2018-10-20 18:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 18:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 10:25 UTC, Orilow commented
🔔 переделал

2018-10-23 11:29 UTC, Dotokoto commented on index.html
> +        <div class="mainblock">
Тут задание все-таки про семантичную верстку в основном. Да и в целом ничего плохого в том, чтобы повесить стили на `main`, нет

2018-10-23 11:34 UTC, Dotokoto commented on index.html
> +                </div>
Для разбивки по блокам вам потом расскажут методологии, скорее всего в следующем семестре :) А вообще хочется, чтобы html был лаконичным. Можно делать обертки, если они действительно нужны для применения стилей или правильной верстки. Но оборачивать всё подряд в div не стоит

2018-10-23 11:43 UTC, Dotokoto commented on index.html
> +        div.mainblock{
Вообще не особо сложно обычно отлавливать ошибки. В инспекторе же видно, откуда стили применились. 
Обычно лучше писать "минимальный" подходящий селектор (удобнее всего по классу). А потом, в случае необходимости, дополнять его или дописывать другие селекторы. Так в целом css выйдет более компактным

2018-10-23 11:44 UTC, dotokoto approved these changes

2018-10-23 11:44 UTC, closed without merging

2018-11-11 15:03 UTC, Orilow commented
А я же доп сделал а мне за него не поставили extra

2018-11-15 13:37 UTC, Dotokoto commented
Я что-то не вижу допов к этому заданию, в описании задачи...

2018-11-19 08:44 UTC, Orilow commented
а, подумал, что "Кроме того: ..." это и есть extra, прошу прощения