Первая попытка
urfu-2018/markup-task-1 pull request #44
Opened 2018-10-12 12:07 UTC by Kuvadorian

2018-10-12 12:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 12:14 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 12:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-12 12:45 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 12:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 13:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 13:18 UTC, phwb requested changes

2018-10-12 13:18 UTC, phwb commented on index.html
> +       <table>
таблицы хорошо, но лучше на дивах

2018-10-12 13:18 UTC, phwb commented on index.html
> +   <form>
не нужно всю страницу оборачивать в форму

2018-10-12 13:18 UTC, phwb commented on index.html
> +    <main>
это должно быть письмо, вот тут как раз и пригодятся таблицы

2018-10-12 13:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-12 14:04 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 14:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 14:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-12 14:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-13 17:34 UTC, Kuvadorian commented
🔔

2018-10-14 07:06 UTC, phwb requested changes
🍎

2018-10-14 07:06 UTC, phwb commented on index.html
> +        <div>Ваше имя <textarea rows="1" placeholder="Имя" required></textarea></div>
вместо `textarea` используй `label` + `input`. текстареа для многострочного ввода, инпут для однострочного

2018-10-14 07:06 UTC, phwb commented on index.html
> +        <div>Ваше имя <textarea rows="1" placeholder="Имя" required></textarea></div>
используй больше семантических тегов, `main`, `section` и т.д.

2018-10-14 09:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 09:56 UTC, Kuvadorian commented
🔔

2018-10-14 15:48 UTC, phwb commented
🍏так лучше, молодец

2018-10-14 15:48 UTC, closed without merging