Домашнее задание 1: Чичи Паул
urfu-2018/markup-task-1 pull request #47
Opened 2018-10-12 14:30 UTC by chichi67

https://github.com/urfu-2018/markup-task-1/commits?author=chichi67

2018-10-12 14:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 15:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 15:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 13:30 UTC, spt30 requested changes
🍅  Хорошо, что прошли тесты, плохо, что ты все удалил перед этим(

2018-12-15 08:09 UTC, closed without merging