Копылов Дмитрий
urfu-2018/markup-task-1 pull request #48
Opened 2018-10-12 15:20 UTC by Dm17r1y

2018-10-12 15:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 15:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-12 15:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 18:52 UTC, chrighter requested changes
🍅

2018-10-14 18:52 UTC, chrighter commented on index.html
> +            <footer>
На странице не может быть 2 футера

2018-10-14 18:52 UTC, chrighter commented on index.html
> +                <span><a href="">Пожаловатся</a></span>
Давай исправим опечатки

2018-10-14 18:52 UTC, chrighter commented on index.html
> +            <p>Для подтверждения перейдите по <a href="">ссылке</a></p>
Давай сделаем ссылки хотя бы на `#`

2018-10-14 18:52 UTC, chrighter commented on index.html
> +            <input type="checkbox" name="notifications">на почту<br>
Давай сделаем так, что галочка в `checkbox` будет проставляться даже по нажатию на текст (`на почту` или `на телефон`)

2018-10-14 18:52 UTC, chrighter commented on index.html
> +        <p>После вашего согласия на подписку вам будут приходить уведомления на почту и телефон</p>
Данный контент и заголовок можно вынести за пределы формы, так как они не относятся к ней

2018-10-14 18:52 UTC, chrighter commented on index.html
> +                    <input type="tel" placeholder="89990007766" required>
Давай добавим валидацию

2018-10-14 18:52 UTC, chrighter commented on index.html
> +        <table>
Табличную вёрстку используют в основном для вёрстки писем, в остальных случаях она используется крайне редко, так как это несемантично и при таком подходе образуется очень много лишних тегов, которые тяжело читать и в которых тяжело разобраться

2018-10-14 18:52 UTC, chrighter commented on index.html
> +            <input type="checkbox" name="notifications">на телефон<br>
После сабмита происходит отправка данных формы на сервер в виде `name1=value1&name2=value2&...`, где `valueN` - это значение атрибута `value` в случае `checkbox` или введенное в поле ввода значение, а `nameN` - то, что для данного `input` записано в атрибут `name`

Поэтому давай еще добавим атрибуты `value` во все `input`

2018-10-14 18:52 UTC, chrighter commented on index.html
> +<table>
Молодец, вот для верстки писем табличная верстка - правильный подход 🔥

2018-10-14 18:52 UTC, chrighter commented on index.html
> +            <img src="yandex.png" alt="yandex" width="100" height="100">
У тебя картинка расположена на уровне 2 и 3 абзацев. Давай сделаем как в макете - на уровне 1 и 2 абзацев

2018-10-14 18:52 UTC, chrighter commented on index.html
> +                    <span>E-mail</span>
Зачем `<span>`?

2018-10-15 07:37 UTC, Dm17r1y commented on index.html
> +        <table>
Просто я сделал таблицей, чтобы input-ы были выровнены

2018-10-15 07:54 UTC, Dm17r1y commented on index.html
> +                    <span>E-mail</span>
Чтобы был не голый текст

2018-10-15 07:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 20:15 UTC, chrighter requested changes
🍅 

Осталось чуть-чуть, ты молодец!

2018-10-19 20:15 UTC, chrighter commented on index.html
>      <tr>
Давай вынесем контент в теги `tfoot` и `tbody` для улучшения семантичности

2018-10-19 20:15 UTC, chrighter commented on index.html
> +            <span><a href="#complain" id="complain">Пожаловаться</a></span>
Просто `#`

2018-10-19 20:15 UTC, chrighter commented on index.html
> +            <input type="tel" pattern="89\d{9}" placeholder="89990007766" required>
👍 за валидацию

2018-10-19 20:15 UTC, chrighter commented on index.html
> +            <label for="mail">на почту</label><br>
Молодец!

Удобно, когда галочка ставится в `checkbox` даже по нажатию на текст, например, когда заполняешь форму с мобильного

2018-10-20 03:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 08:18 UTC, chrighter approved these changes
🍏

2018-10-20 08:18 UTC, chrighter commented on index.html
>      <tr>
На будущее: давай будем соблюдать табуляцию

В остальном - 🆗

2018-10-20 08:19 UTC, closed without merging