Казаков Михаил
urfu-2018/markup-task-1 pull request #55
Opened 2018-10-13 08:37 UTC by Azakov

2018-10-13 08:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 08:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 08:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 11:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 11:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 12:18 UTC, SemyonMakhaev requested changes
🍅 

Михаил, привет! Спасибо за пулл реквест.
Круто, что вёрстка получилась семантичной и доступной 👍  Есть несколько замечаний

Если будут вопросы, пиши мне в слаке

2018-10-14 12:18 UTC, SemyonMakhaev commented on index.html
> +    <form id="outer">
Зачем здесь `id`?

2018-10-14 12:18 UTC, SemyonMakhaev commented on index.html
> +        <input id="name" type="text" placeholder="Имя" required><br>
Можно сгруппировать инпуты и соответствующие им лейблы в блочные элементы, чтобы было удобнее потом их стилизовать

2018-10-14 12:18 UTC, SemyonMakhaev commented on index.html
> +        <input id="name" type="text" placeholder="Имя" required><br>
Тебе здесь точно нужен тег `br`? Не будет ли удачнее реализовать отступы при помощи стилей?

2018-10-14 12:18 UTC, SemyonMakhaev commented on index.html
> +        <input id="phone" type="text" placeholder="89990007766" required><br>
То есть я могу в поле "Телефон" написать любую строку? Давай попробуем добавить валидацию

2018-10-14 12:18 UTC, SemyonMakhaev commented on index.html
> +        <input class="button" id="button" form="outer" type="submit" value="Подписаться">
Идентификатор формы нужно указывать только в случае, если инпут находится за пределами формы

http://htmlbook.ru/html/input/form

2018-10-14 12:18 UTC, SemyonMakhaev commented on index.html
> +        <input class="button" id="button" form="outer" type="submit" value="Подписаться">
Зачем здесь `id`?

2018-10-14 12:18 UTC, SemyonMakhaev commented on index.html
> +        <input class="button" id="button" form="outer" type="submit" value="Подписаться">
Не будет ли семантичнее использовать для кнопки тег [button](http://htmlbook.ru/html/button)?

2018-10-14 12:18 UTC, SemyonMakhaev commented on index.html
> +        <p>После вашего согласия на подписку вам будут
Этот элемент, вероятно, не относится к форме. Может быть вынесем его наружу тега `form`?

2018-10-14 12:18 UTC, SemyonMakhaev commented on index.html
> +<table>
Табличная вёрстка используется в первую очередь для создания таблиц. Для создания интерфейсов с сетчатой структурой таблицы использовать не рекомендуется, лучше добиться того же эффекта при помощи стилей. Попробуй использовать более подходящие теги.

Хотя для обеспечения совместимости с очень старыми браузерами, где новые технологии не поддерживаются, табличная вёрстка используется в качестве альтернативы и по сей день 😅

2018-10-14 12:18 UTC, SemyonMakhaev commented on index.html
> +            <img src="https://img.tyt.by/n/it/0f/3/95911b.jpg"
Для картинок нужно также обязательно всегда указывать атрибут [title](http://htmlbook.ru/html/attr/title). Это необходимо для обеспечения доступности

2018-10-14 12:18 UTC, SemyonMakhaev commented on index.html
> +                 alt="yandex_logo" width="150" height="150">
Атрибут [alt](http://htmlbook.ru/html/img/alt) содержит текстовую интерпретацию изображения. Её может увидеть пользователь, если картинка, например, не загрузилась.

Кроме того, пользователи с ограниченными возможностями при помощи скринридеров получают текстовую информацию с экрана. Содержимое атрибута `alt` - это единственное, что они смогут узнать об изображении.

Давай попробуем придумать более удачное описание этой картинки 😉

2018-10-14 12:18 UTC, SemyonMakhaev commented on index.html
> +            ©&nbsp; 2018, <a href="https://yandex.ru/company/">Яндекс</a>
Вместо символа `©` используй `&copy;`, иначе твой html будет невалиден

2018-10-14 12:24 UTC, SemyonMakhaev commented
Отдельный респект, если добавишь стилей, чтобы интерфейс получился, как на макете 😃 

![2015_06_10_12_06_35_79b56615ad6b75a28352dc50425e6c19](https://user-images.githubusercontent.com/18099714/46916579-faf2cd00-cfd5-11e8-95c4-d7951f13b8ef.jpg)

2018-10-14 14:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 14:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 15:12 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 15:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 15:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 15:28 UTC, SemyonMakhaev requested changes
🍅 

Молодец, что добавил стилей! 👍 
Осталось ещё несколько правок

![2018-10-14 20-21-24](https://user-images.githubusercontent.com/18099714/46918768-8c226d80-cfef-11e8-8fb7-f65bb62516aa.png)


![2018-10-14 20-24-05](https://user-images.githubusercontent.com/18099714/46918770-96446c00-cfef-11e8-9560-63ae2fdde2de.png)

2018-10-14 15:28 UTC, SemyonMakhaev commented on index.css
> +    font: 12pt sans-serif;
Шрифт лучше всего будет задать у глобального родительского элемента (например, `body`). Тогда шрифт унаследуется для всех остальных элементов, и браузер будет обрабатывать такой CSS более эффективно

2018-10-14 15:28 UTC, SemyonMakhaev commented on index.css
> +    font: 12pt sans-serif;
В вебе обычно используют единицу измерения `px`, она удобнее для переноса стилей из макетов

2018-10-14 15:28 UTC, SemyonMakhaev commented on index.css
> +h1
Это общий селектор. Если на твоей странице появится другой элемент с тегом `h1`, то стили применятся и для него. Используй селектор класса

2018-10-14 15:28 UTC, SemyonMakhaev commented on index.css
> +    background: none;
Зачем это правило?

2018-10-14 15:28 UTC, SemyonMakhaev commented on index.css
> +a
> Это общий селектор. Если на твоей странице появится другой элемент с тегом `h1`, то стили применятся и для него. Используй селектор класса

Аналогично про `a`

2018-10-14 15:28 UTC, SemyonMakhaev commented on index.css
> +    background: azure;
Здесь лучше подойдёт `background-color`, [background](https://developer.mozilla.org/ru/docs/Web/CSS/background) используется для задания нескольких свойств, оно здесь избыточно

2018-10-14 15:28 UTC, SemyonMakhaev commented on index.css
> +.footer-right_a
`snake_case` не принято использовать для именования классов CSS, поскольку это усложняет их чтение. Используй `kebab-case`, как везде

Однако добавлю, что существуют разные соглашения по именованию классов. Например, в Яндексе наша команда использует методологию БЭМ, в которой реализуется некоторое подобие snake case написания. Если интересно, можешь поизучать 😉 
https://ru.bem.info/methodology/naming-convention/

2018-10-14 15:28 UTC, SemyonMakhaev commented on index.html
> +                    <input class="fields" id="phone" type="tel" pattern="[0-9]{,11}"
Можно использовать `\d` в шаблоне

2018-10-14 15:28 UTC, SemyonMakhaev commented on index.html
> +                    <input class="fields" id="phone" type="tel" pattern="[0-9]{,11}"
Шаблон принимает невалидные номера телефонов (менее 7 цифр)

2018-10-14 15:28 UTC, SemyonMakhaev commented on index.html
> +        <span class="footer-right_a">&copy;&nbsp; 2018, <a href="https://yandex.ru/company/">Яндекс</a></span>
А зачем здесь `&nbsp;`? Он вообще обычно используется для неразрывного пробела, но за ним обычный пробел...

2018-10-14 15:28 UTC, SemyonMakhaev commented on index.css
> +img
> Это общий селектор. Если на твоей странице появится другой элемент с тегом `h1`, то стили применятся и для него. Используй селектор класса

Аналогично про `img`

2018-10-14 17:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 17:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 17:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 17:43 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 17:45 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 17:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 17:48 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 17:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 17:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 17:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 19:37 UTC, SemyonMakhaev requested changes
🍅 

Осталось поправить два css-правила и шаблон, в остальном всё круто 👍
Поправишь - напиши мне, чтобы я успел закрыть задачу)

2018-10-14 19:37 UTC, SemyonMakhaev commented on index.css
> +    font: 18px sans-serif;
Это правило наследуется от `body`, здесь его можно не указывать

2018-10-14 19:37 UTC, SemyonMakhaev commented on index.html
> +                    <input class="fields" id="phone" type="tel" pattern="\d[0-9]{6,11}"
Шаблон принимает строку, где 12 цифр.

Мне кажется, можно проще - цифра, повторённая от 7 до 11 раз, вот так: `\d{7,11}`

2018-10-14 23:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 23:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-15 05:36 UTC, SemyonMakhaev approved these changes
🍏

Всё круто! Молодец, что сверстал под макет, получилось очень здорово 👍 👍 👍

2018-10-15 05:36 UTC, SemyonMakhaev commented on index.css
> +    font: 14px sans-serif;
Здесь тебе достаточно указать размер шрифта. Используй [font-size](http://htmlbook.ru/css/font-size)

2018-10-15 05:36 UTC, closed without merging