Ильющенко Анастасия
urfu-2018/markup-task-1 pull request #56
Opened 2018-10-13 10:02 UTC by Kaprican

2018-10-13 10:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 12:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 12:21 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 12:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 05:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 06:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 06:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 06:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 13:49 UTC, chrighter requested changes
🍅

2018-10-19 13:49 UTC, chrighter commented on index.html
> +            <p>После вашего согласия на подписку вам будут приходить уведомления на почту и на телефон</p>
Это можно вынести за пределы формы, так как к ней данный контент не относится

2018-10-19 13:49 UTC, chrighter commented on index.html
> +                <input required="" id="Name" type="text" placeholder="Имя">
Можно просто `required`

2018-10-19 13:49 UTC, chrighter commented on index.html
> +                <input required="" id="phoneNumber" type="text" pattern="[89|+79][0-9]{9}"
Неверное регулярное выражение

2018-10-19 13:49 UTC, chrighter commented on index.html
> +                    <label for="checkemail">На почту</label>
Здорово, что сделала возможным выставлять галочку в `checkbox` даже просто по нажатию на текст 👍

2018-10-19 13:49 UTC, chrighter commented on index.html
> +            <tr>
Давай для увеличения семантичности добавим теги `tfoot` и `tbody`

2018-10-19 13:49 UTC, chrighter commented on index.html
> +                    <img src="https://cs6.pikabu.ru/post_img/big/2014/09/23/1/1411420967_1716884301.jpg"
Давай добавим картинке ограничения по размеру

2018-10-19 13:49 UTC, chrighter commented on index.html
> +                    <input type="checkbox" id="checkphone" name="notification" value="phone" checked>
Зачем `checked`?

2018-12-15 08:10 UTC, closed without merging