Маслов Даниил
urfu-2018/markup-task-1 pull request #59
Opened 2018-10-13 11:26 UTC by daniilmaslof

[Посмотреть решение](https://hruview.herokuapp.com/daniilmaslof/markup-task-1/master/index.html)

2018-10-13 11:27 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 12:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 14:03 UTC, chrighter requested changes
🍅

2018-10-19 14:03 UTC, chrighter commented on index.html
> +        <h2>Хочу подписаться!</h2>
Почему используешь `h2`, если еще не использовать `h1` на странице?

2018-10-19 14:03 UTC, chrighter commented on index.html
> +        src="https://avatars.mds.yandex.net/get-bunker/50064/9c8dea8c94b9bea5ef1677932c8272cbfca4995a/orig"
Давай расположим картинку как на макете

2018-10-19 14:03 UTC, chrighter commented on index.html
> +    <footer>
Давай расположим содержимое футера как на макете

2018-10-19 14:03 UTC, chrighter commented on index.html
> +                       pattern="8[0-9]{2}[0-9]{3}[0-9]{4}">
Неверное регулярное выражение

2018-10-19 14:03 UTC, chrighter commented on index.html
> +                <input required type="email" name="email" id="email" placeholder="email@yandex.ru">
Давай тогда во всех `input`атрибуты с новой строки писать для единообразия

2018-10-19 14:03 UTC, chrighter commented on index.html
> +<article>
На будущее: для верстки писем лучше использовать табличную верстку - это залог того, что верстка "не разъедется" ни в одном почтовом клиенте

Подробнее можно посмотреть здесь: https://habr.com/post/252279/

2018-10-19 14:03 UTC, chrighter commented on index.html
> +                <label for="atPhone">на телефон</label>
Здорово, что добавил возможность выделения `checkbox` даже по нажатию на текст! 👍 

Это удобно, например, когда заполняешь форму с мобильного

2018-11-02 09:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-02 09:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-15 08:10 UTC, closed without merging