Маркевич Роман
urfu-2018/markup-task-1 pull request #61
Opened 2018-10-13 11:38 UTC by Tassadar2499

2018-10-13 11:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 11:53 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 11:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 09:37 UTC, dotokoto requested changes

2018-10-16 09:37 UTC, Dotokoto commented on index.html
> +    <div class="registrationForm">
В html не принято писать в `camelCase`. Обычно пишут `registration-form`

2018-10-16 09:37 UTC, Dotokoto commented on index.html
> +        <label for="loginForm">Ваше имя</label>
Отступы съехали у всего, что внутри `<form>`

2018-10-16 09:37 UTC, Dotokoto commented on index.html
> +        <input type="text" id="emailForm" name="email">
Есть более подходящий тип для этого поля

2018-10-16 09:37 UTC, Dotokoto commented on index.html
> +        <input type="text" id="phoneForm" name="phone">
И для этого тоже есть более подходящий тип

2018-10-16 09:37 UTC, Dotokoto commented on index.html
> +        <p>Хочу получать уведомления:</p>
Это скорее заголовок блока, чем просто абзац

2018-10-16 09:37 UTC, Dotokoto commented on index.html
> +        <input type="checkbox" id="checkEmail">
Это список опций, можно более семантично оформить

2018-10-16 09:37 UTC, Dotokoto commented on index.html
> +        <table>
Вообще, таблицы используются для верстки писем из-за плохой поддержки почтовыми клиентами других способов верстки. Но в этом задании можно сверстать более семантично

2018-10-16 09:37 UTC, Dotokoto commented on index.html
> +                    alt="Логотип"
Неинформативный `alt`. Какой логотип? Непонятно

2018-10-16 09:37 UTC, Dotokoto commented on index.html
> +    <div class="Letter">
Можно подобрать более семантичный тег

2018-10-16 11:28 UTC, Tassadar2499 commented on index.html
> +        <table>
А как сверстать, не используя стили и таблицы? Мне в тестах пишут, что - the `style` attribute is banned

2018-10-16 11:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 11:37 UTC, Tassadar2499 commented
Пришлось закомментировать стили.

2018-10-19 09:33 UTC, dotokoto approved these changes

2018-10-19 09:33 UTC, closed without merging