Георгий Рылов
urfu-2018/markup-task-1 pull request #62
Opened 2018-10-13 12:31 UTC by g0djan

2018-10-13 12:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 13:33 UTC, spt30 commented
найс первый коммит:D

2018-10-14 13:39 UTC, spt30 requested changes
🍅 небольшие замечания, но в целом все хорошо

2018-10-14 13:39 UTC, spt30 commented on index.html
> +        Ваше имя <input type="text" required="" placeholder="Имя"><br>
Эту штуку можно оборачивать в специальный тег ```<label>```, чтобы при клике по строке "Ваше имя", появлялся фокус в поле input

Тег ```<br>``` тогда можно будет убрать

Аналогично с чекбоксами

2018-10-14 13:39 UTC, spt30 commented on index.html
> +        <p>
Это не параграф, давай придумаем другой тег

2018-10-14 13:39 UTC, spt30 commented on index.html
> +
Строчка лишняя

2018-10-14 13:39 UTC, spt30 commented on index.html
> +
и тут строчка лишняя

2018-10-14 13:39 UTC, spt30 commented on index.html
> +        Email<input type="email" placeholder="email@yandex.ru" required=""><br>
можно писать просто ```required```, хотя ```required=""``` тоже работает, но так не пишут

2018-10-21 18:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 16:41 UTC, spt30 commented
🍏молодец!

2018-10-22 16:41 UTC, closed without merging