Марухин Алексей
urfu-2018/markup-task-1 pull request #63
Opened 2018-10-13 12:34 UTC by SaverAlex

2018-10-13 12:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 13:36 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 13:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 16:33 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 16:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 16:43 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 16:49 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 16:53 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 16:56 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 17:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 18:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 18:35 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 18:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 09:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-15 13:36 UTC, nex2hex requested changes
🍅

2018-10-15 13:36 UTC, nex2hex commented on index.html
> +        <td><input placeholder="Имя"></td>
Текст "Ваше имя" должен быть внутри label, чтобы при клике по нему курсор помещался в поле ввода

2018-10-15 13:36 UTC, nex2hex commented on index.html
> +        <td><input placeholder="Имя"></td>
Нет валидации полей формы

2018-10-15 13:36 UTC, nex2hex commented on index.html
> +        <tr><td><button>Подписаться</button></td></tr>
type="submit"

2018-10-15 13:36 UTC, nex2hex commented on index.html
> +    <div>Здравствуйте, Николай!</div>
письмо можно в section вставить

2018-10-18 06:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-18 15:30 UTC, nex2hex requested changes
🍅 
уже лучше

2018-10-18 15:30 UTC, nex2hex commented on index.html
> +                    <td><input id="email" placeholder="email@yandex.ru"
зачем? можно же просто type="email"

2018-10-18 15:30 UTC, nex2hex commented on index.html
> +                    <td><input id="phone" placeholder="89990007766"
и тут

2018-10-18 15:30 UTC, nex2hex commented on index.html
> +                        <tr><td><input type="checkbox">на почту</td></tr>
текст должен быть внутри label чтобы по нему можно было кликнуть

2018-10-18 15:30 UTC, nex2hex commented on index.html
> +    </body>
</section> закрывается тут
секция включает в себя все письмо

2018-10-18 16:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 16:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 16:34 UTC, SaverAlex commented
:bell:

2018-10-22 15:21 UTC, closed without merging