Шевчук Екатерина
urfu-2018/markup-task-1 pull request #65
Opened 2018-10-13 13:28 UTC by shevkate

2018-10-13 13:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 16:09 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 16:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 20:22 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 20:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 20:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 21:16 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 21:22 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 21:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 21:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 21:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 21:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 13:50 UTC, spt30 commented
Забавно, ты считала решения, но 2 раза написала "второе решение"

2018-10-14 13:55 UTC, shevkate commented
Извиняюсь! Это очень плохо? Я и пробелы раза с 6 только убрала. Уже не соображала в ночи. А вообще я умею считать, правда

2018-10-14 13:56 UTC, spt30 requested changes
🍅Посмотри, пожалуйста, как ставили отступы другие ребята и расставь так же
Очень неудобно читать

2018-10-14 14:22 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 14:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 14:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-18 16:26 UTC, spt30 requested changes
очень круто, что все без стилей сделано
несколько мелких замечаний, но в целом молодец!

2018-10-18 16:26 UTC, spt30 commented on index.html
> +                <table>
Давай в другой раз обходиться без таблиц
Когда я говорил про отступы, я имел в виду избегать вот таких конструкций: 
```<tr><td><p>Для подтверждения перейдите по <a href="#">ссылке</a></p></td><td></td></tr>```
Здесь лучше было сделать так:
```
<tr>
    <td>
        <p>
            Для подтверждения перейдите по <a href="#">ссылке</a>
        </p>
    </td>
    <td></td>
</tr>

2018-10-18 16:26 UTC, spt30 commented on index.html
> +    <head>
`<html>`, `<head>` и `<body>` должны быть без отступов

2018-10-18 16:26 UTC, spt30 commented on index.html
> +        <section class="newsletter">
это `<article>`, равноправный с письмом блок
оба имеют заголовки
оба могут существовать как отдельные сущности

2018-10-18 16:26 UTC, spt30 commented on index.html
> +                    <tr><td><input type="checkbox" name="sendto" required size="20">на почту</td></tr>
тут нет `<label>`, из-за этого, когда кликаешь на текст "на почту", не ставится галочка
у тебя выше написано правильно, когда кликаешь на "Ваше имя", например, сразу фокус появляется
давай сделаем `<label>`

2018-10-18 16:26 UTC, spt30 commented on index.html
> +            <form action="#" name="YaForm">
форма – это то, что нужно заполнять
заголовок и параграф в нее не входят

2018-10-18 16:26 UTC, spt30 commented on index.html
> +                        <td><input id="name" type="text" autofocus placeholder="Имя" required size="20"></td>
🥇за автофокус

2018-10-18 17:44 UTC, shevkate commented on index.html
> +                <table>
:ok_hand:

2018-10-18 17:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-18 17:44 UTC, shevkate commented on index.html
> +    <head>
:ok_hand:

2018-10-18 17:45 UTC, shevkate commented on index.html
> +        <section class="newsletter">
:ok_hand:

2018-10-18 17:45 UTC, shevkate commented on index.html
> +                    <tr><td><input type="checkbox" name="sendto" required size="20">на почту</td></tr>
:ok_hand:

2018-10-18 17:45 UTC, shevkate commented on index.html
> +            <form action="#" name="YaForm">
:ok_hand:

2018-10-20 10:42 UTC, spt30 approved these changes
Молодец! Очень круто)

P.S. ты коммент оставляешь 👌такой, наверное, для того, чтобы самой следить за тем, что ты исправила
Я обычно реакцию в комментарию в ревью добавляю, так оповещения не достают, если 100 правок прислал, а потом тебе на каждый коммент приходит смайлик

2018-10-20 10:42 UTC, spt30 commented on index.html
> +<article class="newsletter">
а вот `<article>` уже надо отступать
Ладно, привыкнешь) Сам тебя запутал

2018-10-20 10:42 UTC, spt30 commented
🍏 все круто

2018-10-20 10:42 UTC, closed without merging