Громова Анна
urfu-2018/markup-task-1 pull request #68
Opened 2018-10-13 15:13 UTC by AnnaGromova

2018-10-13 15:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-13 15:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 14:11 UTC, spt30 requested changes
🍅Есть небольшие замечания

2018-10-14 14:11 UTC, spt30 commented on index.html
> +        </label>
Что-то эти поля у тебя в верстке слиплись в одну строку, надо бы их как-то разделить

2018-10-14 14:11 UTC, spt30 commented on index.html
> +        <input type="checkbox" name="postMail" id="agreePostMail"><label for="agreePostMail">На почту</label>
Эти тоже

2018-10-14 14:11 UTC, spt30 commented on index.html
> +        <p>Хочу получать уведомления</p>
Двоеточие

2018-10-14 14:11 UTC, spt30 commented on index.html
> +            Телефон<input type="tel" id="phone" placeholder="89990007766" pattern="^(8|\+7)9\d{9}$" required>
Этим трем инпутам не хватает атрибута "name"

2018-10-14 14:11 UTC, spt30 commented on index.html
> +        <input type="checkbox" name="telmail" id="agreeTelMail"><label for="agreeTelMail">На телефон</label>
давай придумаем другие имена для чекбоксов, например, telNotifications и mailNotifications

2018-10-14 14:11 UTC, spt30 commented on index.html
> +                    © 2018<a href="https://www.yandex.ru/">Яндекс</a>
Давай вставим значок копирайта с помощью html-кода, обычно делают так

И еще тут не хватает запятой и пробела

2018-10-14 14:11 UTC, spt30 commented on index.html
> +                    Здравствуйте, Николай!
Как-то не так, давай сделаем красиво
![image](https://user-images.githubusercontent.com/31798669/46917850-d2260400-cfe4-11e8-8ea5-513e97391ab3.png)

2018-10-14 16:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 18:45 UTC, AnnaGromova commented
:green_apple:

2018-10-18 16:28 UTC, spt30 commented
ты пыталась:(

2018-10-18 16:29 UTC, AnnaGromova commented
нуу ты долго не проверяешь)

2018-10-18 16:31 UTC, spt30 commented
тут сыглы

2018-10-18 16:32 UTC, AnnaGromova commented
пришлось гуглить что это значит

2018-10-18 16:33 UTC, spt30 approved these changes

2018-10-18 16:33 UTC, spt30 commented on index.html
> +        <input type="checkbox" name="mailNotification" id="agreePostMail">
уведомления во множественном числе, лучше было notifications

2018-10-18 16:33 UTC, spt30 commented on index.html
> +        <input type="checkbox" name="mailNotification" id="agreePostMail">
а id-шники не поправила)

2018-10-18 16:33 UTC, spt30 commented
🍏ты молодец!

2018-10-18 16:33 UTC, closed without merging