Solodovnikova Ekaterina
urfu-2018/markup-task-1 pull request #7
Opened 2018-10-10 05:02 UTC by KatySolo

initial solution

2018-10-10 05:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 05:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 05:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 05:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-13 08:00 UTC, chrighter commented on index.html
> +        <h2>Хочу подписаться!</h2>
Почему используешь `h2` на странице, если еще нигде не использовала `h1`?

2018-10-13 08:01 UTC, chrighter commented on index.css
> +    background: rgb(248, 248, 248);
Почему иногда цвета задаёшь в `rgb`, а иногда с помощью имени?

Давай всё приведём к общему виду

2018-10-13 08:22 UTC, chrighter commented on index.html
> +            <div>
Давай добавим семантики

2018-10-13 08:24 UTC, chrighter commented on index.html
> +                <input type="checkbox" name="way1" value="email">на почту<br>
Давай сделаем так, что галочка в `checkbox` будет проставляться даже по нажатию на текст (`на почту` или `на телефон`)

2018-10-13 08:29 UTC, chrighter commented on index.html
> +                <input type="checkbox" name="way2" value="phone">на телефон
При сабмите на сервер уходят данные в виде `name1=value1&name2=value2....`, кажется, что имя `way2` мало о чем будет говорить

Давай сделаем более понятное именование

2018-10-13 08:32 UTC, chrighter commented on index.html
> +                <input type="tel" placeholder="89990007766" pattern="[8]\d{11}">
Неверное регулярное выражение

2018-10-13 08:34 UTC, chrighter commented on index.html
> +                <input type="email" placeholder="email@yandex.ru">
Давай сделаем поля ввода обязательными и добавим атрибуты `name`

2018-10-13 08:36 UTC, chrighter commented on index.html
> +                +79xxxxxxx78.</p>
`</p>` на новую строку

2018-10-13 09:15 UTC, chrighter requested changes
🍅

2018-10-13 09:15 UTC, chrighter commented on index.html
> +            <p>Уведомления буудт приходить вам на этот email
Исправь опечатки

2018-10-13 09:15 UTC, chrighter commented on index.html
> +    <div class="second_page">
На будущее: для верстки писем лучше использовать табличную верстку - это залог того, что верстка "не разъедется" ни в одном почтовом клиенте

Подробнее можно посмотреть здесь: https://habr.com/post/252279/

2018-10-13 09:15 UTC, chrighter commented on index.css
> +    float: right;
На будущее: `float` по жизни лучше вообще не использовать, так как это свойство в некоторых случаях ведет себя неочевидно, подробнее можно посмотреть здесь https://habr.com/post/142486/

Кроме этого, есть более удобные и понятные свойства

2018-10-13 09:15 UTC, chrighter commented on index.css
> +input:invalid
👍

2018-10-13 09:15 UTC, chrighter commented on index.css
> +input[type='checkbox']
👍

2018-10-13 09:15 UTC, chrighter commented on index.css
> +    text-decoration: none;
Можно еще добавлять эффекты на при наведении на кликабельные элементы - это позволит сделать страницу более отзывчивой

2018-10-13 09:15 UTC, chrighter commented on index.css
> +body > div
👍 за использование селекторов отношений

2018-10-13 09:15 UTC, chrighter commented on index.html
> +                <span class="copyright">&#169; 2018, <a href="http://www.yandex.ru">Яндекс</a></span>
Значок копирайта можно еще записать с помощью `&copy;` для читабельности

2018-10-13 09:27 UTC, KatySolo commented on index.html
> +                <input type="tel" placeholder="89990007766" pattern="[8]\d{11}">
неверное в плане, что начинаться телефон может и с +7, просто 7 и 8 или в том смысле, что не отрабатывает?

2018-10-13 15:07 UTC, chrighter commented on index.html
> +                <input type="tel" placeholder="89990007766" pattern="[8]\d{11}">
Не отрабатывает

2018-10-14 08:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 18:31 UTC, chrighter requested changes
🍅 
Еще чуть-чуть, ты молодец!

2018-10-14 18:31 UTC, chrighter commented on index.css
> +input:hover
👍

2018-10-14 18:31 UTC, chrighter commented on index.html
> +            <!--<tr></tr>-->
Давай уберем лишний комментарий

2018-10-14 18:31 UTC, chrighter commented on index.html
> +            <tr>
Всё круто, молодец! 🔥 

Но кажется, что надо поместить это в футер таблицы, а все вышестоящее - в тело таблицы

2018-10-14 18:31 UTC, chrighter commented on index.html
> +                              value="email">на почту</label><br>
Я еще бы перенесла `</label>` на новую строку под открывающий тэг

2018-10-14 18:31 UTC, chrighter commented on index.html
> +                              value="email">на почту</label><br>
👍 за то, что галочка в `checkbox` ставится даже по нажатию на текст
Согласись, это очень удобно, особенно когда заполняешь форму с какого-нибудь мобильного устройства

2018-10-14 18:36 UTC, chrighter commented on index.html
> +                              value="email">на почту</label><br>
И давай в форме заменим кучу дивов на что-то более семантичное

2018-10-15 07:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 13:27 UTC, chrighter approved these changes
🍏🔥

2018-10-16 13:29 UTC, closed without merging