Подписка №1
urfu-2018/markup-task-1 pull request #70
Opened 2018-10-13 17:36 UTC by ekimovskih

2018-10-13 17:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 17:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 17:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 18:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 18:16 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 18:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 18:36 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 18:48 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 18:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 19:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 19:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 19:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-13 19:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 19:53 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 20:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 20:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 20:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-13 20:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 09:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 15:21 UTC, VasiliiKuznecov requested changes

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +    <article>
думаю, article тут неуместны, так как это про единообразные элементы, которых много
тут их всего два и они очень разной структуры

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +    <h1>Хочу подписаться!</h1>
без форматирования очень сложно читать, добавь табуляции

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +    <p>После вашего согласия на подписку вам будут приходить<br>
не используй никогда br
лучше разбей на два параграфа

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +    <section>
кажется, section не нужен, он только оборачивает table

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +            <td>Ваше имя</td>
хотелось бы по нажатию на лейбл фокусироваться на инпуте

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +            <td><input placeholder="email@yandex.ru" type="text"></td>
есть специальный тип для емэйлов

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +            <td><input placeholder="89990007766" type="text"></td>
и для телефонов

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +            <td><input placeholder="89990007766" type="text"></td>
у тебя нет никакой валидации

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +    <section>
лучше оберни все инпуты в форму

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +            <td><input placeholder="Имя" type="text"></td>
добавь инпутам имена

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +    <input type="checkbox">на почту<br>
не помешало бы имя и значение

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +    <input type="checkbox">на почту<br>
и чтобы можно было нажать "на почтку" и проставилась галочка

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +    <td>(c)2018,<a href="nope" title="Яндекс">Яндекс</a></td>
копирайт не справа

2018-10-17 15:21 UTC, VasiliiKuznecov commented on index.html
> +    <footer>
article и footer и прочие новые теги лучше не использовать при верстке писем, так как некоторые почтовые клиенты неправильно на них могут реагировать

2018-12-15 08:11 UTC, closed without merging