Боярников Семён
urfu-2018/markup-task-1 pull request #73
Opened 2018-10-13 20:58 UTC by StarLordJ

2018-10-13 20:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-15 13:31 UTC, nex2hex requested changes
🍅

2018-10-15 13:31 UTC, nex2hex commented on index.html
> +                        <p class="form_userinfo_value">Ваше имя</p>
Текст "Ваше имя" должен быть внутри label, чтобы при клике по нему курсор помещался в поле ввода

2018-10-15 13:31 UTC, nex2hex commented on index.html
> +                        <label for="onEmail">
for можно не указывать

2018-10-15 13:31 UTC, nex2hex commented on index.html
> +                <button>Подписаться</button>
type="submit"

2018-10-15 13:31 UTC, nex2hex commented on index.html
> +                <thead>
пустой тэг не нужен

2018-10-17 16:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 16:56 UTC, closed without merging