add html and css
urfu-2018/markup-task-1 pull request #75
Opened 2018-10-14 05:32 UTC by libgtso

2018-10-14 05:33 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 05:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 05:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 13:13 UTC, SemyonMakhaev requested changes
🍅 

Александр, здравствуй! Спасибо за пулл реквест. Получилось семантично и доступно, молодец! 👍 

Есть несколько замечаний. Если будут вопросы пиши мне в слаке)

По поводу дизайна - на скриншоте отметил несколько несоответствий с макетом.
Письмо вообще получилось довольно близко к макету, круто! Можно его только чуть поуже сделать.

![2018-10-13 09-05-37](https://user-images.githubusercontent.com/18099714/46916772-7e152280-cfd8-11e8-9ea1-a4f0687cb9ac.png)

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.html
> +            <span>Яндекс</span>
Давай сделаем логотип картинкой

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.css
> +.subscription_wrap
`snake_case` не принято использовать для именования классов CSS, поскольку это усложняет их чтение. Используй `kebab-case`

Однако добавлю, что существуют разные соглашения по именованию классов. Например, в Яндексе наша команда использует методологию БЭМ, в которой реализуется некоторое подобие snake case написания. Если интересно, можешь поизучать 😉 
https://ru.bem.info/methodology/naming-convention/

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.css
> +    font-family: Arial, Helvetica, sans-serif;
Шрифт лучше всего будет задать у глобального родительского элемента (например, `body`). Тогда шрифт унаследуется для всех остальных элементов, и браузер будет обрабатывать такой CSS более эффективно

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.css
> +    white-space: normal;
У свойства [white-space](http://htmlbook.ru/css/white-space) по умолчанию значение `normal`

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.css
> +    background: #f8f8f8;
Для задания цвета лучше использовать [background-color](http://htmlbook.ru/css/background-color)

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.css
> +    background: none;
Зачем это правило?

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.css
> +    color: red;
Цвета следует указывать во всём проекте в одной и той же нотации для сохранения общности. При этом лучше использовать `hex`-нотацию, так как она интуитивно более понятна, и ей проще воспользоваться при переносе цветов из макета в интерфейс

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.css
> +.footer .copyright a
Зачем такая вложенность в селекторе? Не будет ли достаточно `.copyright a` или как-то так?

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.html
> +                После вашего согласия на подписку вам будут приходить уведомления на почту и
Зачем перенос строки?

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.html
> +                required maxlength="20" pattern="[a-zA-Zа-яА-я]+">
Шаблон не принимает пробел и `-`

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.html
> +            <input class="form_field" type="email" pattern="\S+@[a-z]+.[a-z]+" placeholder="email@yandex.ru">
Шаблон принимает строки вида `$%#@q.q` и не принимает `example@myDomain.TLD`

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.html
> +                required pattern="\d{11}" minlength="11"
Давай попробуем поддержать также городские (семизначные) номера телефнов

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.html
> +            <a class="" href="/">Пожаловаться</a>
Почему пустой `class`?

2018-10-14 13:13 UTC, SemyonMakhaev commented on index.html
> +                <a href="">Яндекс</a>
Зачем пустой атрибут `href`?

2018-10-16 16:46 UTC, libgtso commented on index.html
> +            <span>Яндекс</span>
есть вопрос - куда и как постучаться в слаке? сегодня пытался как-то выяснить вопросы по задачам о javascript, но как-то не зашло

2018-10-17 14:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 14:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 09:01 UTC, SemyonMakhaev requested changes
🍅 

Молодец, что написал стили, получилось очень близко к макету, круто!
Извини за долгую проверку. Есть ещё несколько небольших правок. Когда зальёшь, призови меня / напиши мне / сделай что-нибудь, чтобы я успел закрыть задачу до дедлайна :joy:

2018-10-20 09:01 UTC, SemyonMakhaev commented on index.css
> +    border: 1px solid #d5d4d4;
Правило несколько раз дублируется. Нужно вынести в отдельный класс или сгруппировать селекторы

2018-10-20 09:01 UTC, SemyonMakhaev commented on index.html
> +                required pattern="\d{7,11}" minlength="7"
👍

2018-10-20 09:01 UTC, SemyonMakhaev commented on index.html
> +            <img class="logo" src="./logo.jpg" alt="Yandex">
`logo.jpg`, кажется, потерялся

2018-10-20 09:01 UTC, SemyonMakhaev commented on index.html
> +                required maxlength="20" pattern="^[А-Яа-яЁё\s]+$">
👍 👍 👍

2018-10-20 09:01 UTC, SemyonMakhaev commented on index.css
> +    font-family: Arial, Helvetica, sans-serif;
Когда в `font-family` задан набор шрифтов, браузер по порядку идёт по списку и пытается подключить очередной шрифт. Если этого шрифта нет в операционной системе, браузер проверяет следующий и так далее по списку.

Шрифт `Arial` по умолчанию есть в каждой уважающей себя операционной системе. Поэтому `Helvetica` в этом случае никогда не применится. Нужно либо их поменять местами, либо удалить гельветику, в зависимости от того, какого эффекта ты хочешь достичь 😉 

http://htmlbook.ru/css/font-family

2018-10-20 09:04 UTC, SemyonMakhaev commented on index.html
> +                required maxlength="20" pattern="^[А-Яа-яЁё\s]+$">
На правах рекламы порекомендую онлайн-сервис для тестирования регулярок 😄 

https://regex101.com

2018-10-22 14:58 UTC, libgtso commented
@SemyonMakhaev реквестирую

2018-10-22 18:51 UTC, SemyonMakhaev commented
🍏 

Супер 👍

2018-10-22 18:51 UTC, closed without merging

2018-10-22 19:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты