Ромасс Андрей
urfu-2018/markup-task-1 pull request #77
Opened 2018-10-14 07:55 UTC by Fylhtq42

2018-10-14 07:56 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 07:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 09:45 UTC, dotokoto requested changes

2018-10-16 09:45 UTC, Dotokoto commented on index.html
> +                <h4>После вашего согласия на пописку вам будут приходить уведомления на почту и телефон</h4>
Почему именно `h4`

2018-10-16 09:45 UTC, Dotokoto commented on index.html
> +                <section>
Описание `section` с https://developer.mozilla.org/ru/docs/Web/HTML/Element/section:
```
HTML элемент <section> представляет собой автономную секцию функционала,  содержащуюся внутри HTML-документа, чаще всего с заголовком, в которой нет прочих специфических определяющих элементов, чтобы представить данный функционал.
```
Это ведь не автономные секции документа, а части одной формы. Их не нужно оформлять в `section`

2018-10-16 09:45 UTC, Dotokoto commented on index.html
> +                    <input placeholder="89990007766" id="Phone" name="Name" pattern="[0-9]{11}" required>
Для телефонов есть свой тип

2018-10-16 09:45 UTC, Dotokoto commented on index.html
> +                <h4>Хочу получать уведомления:</h4>
Опять же, почему h4?

2018-10-16 09:45 UTC, Dotokoto commented on index.html
> +                <section>
то же самое про `section`, что и выше

2018-10-16 09:45 UTC, Dotokoto commented on index.html
> +            <button type="submit" autofocus>Подписаться</button>
Зачем `autofocus` на кнопке, если сначала надо заполнить поля формы?

2018-10-18 10:38 UTC, Fylhtq42 commented on index.html
> +                <section>
Окей, убираю все секции.

2018-10-18 10:39 UTC, Fylhtq42 commented on index.html
> +                <h4>После вашего согласия на пописку вам будут приходить уведомления на почту и телефон</h4>
Для красоты выделил h4. Но сейчас понял что просто p достаточно.

2018-10-18 10:39 UTC, Fylhtq42 commented on index.html
> +            <button type="submit" autofocus>Подписаться</button>
Действительно.

2018-10-18 10:43 UTC, Fylhtq42 commented on index.html
> +                <section>
Без секций теперь код слишком плохо смотрится. Есть ли какая то альтернатива смысловому выделению такого блока.

2018-10-18 10:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 09:54 UTC, dotokoto approved these changes

2018-10-19 09:56 UTC, closed without merging