Решение задачи "Подписка на бложик"
urfu-2018/markup-task-1 pull request #8
Opened 2018-10-10 09:03 UTC by AIBarabanshchikova

2018-10-10 09:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 16:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 04:54 UTC, mokhov requested changes
🍅

2018-10-11 04:54 UTC, mokhov commented on index.html
> +                <input type="text" required placeholder="Имя" pattern="[a-zA-Zа-яА-ЯёЁ]+">
👍 за букву ё

2018-10-11 04:54 UTC, mokhov commented on index.html
> +    <form class="form">
Не обязательно всё заключать в форму, можно только непосредственно форму (то что у тебя в ```fieldWrapper```)

2018-10-11 04:54 UTC, mokhov commented on index.html
> +        <label><input type="checkbox">на почту</label>
У чекбокса не хватает атрибута ```name```

2018-10-11 04:54 UTC, mokhov commented on index.html
> +    <div class="letter" >
Почему везде пробел перед ```>```?

2018-10-11 04:55 UTC, mokhov commented on index.css
> +    border: 1px solid rgb(39, 39, 39);
Здесь не оправдано использование функции, можно в шестнадцатиричном формате писать

2018-10-11 06:05 UTC, AIBarabanshchikova commented on index.html
> +    <form class="form">
Но там же есть ещё поля вне fieldWrapper (два checkbox и submit)

2018-10-11 06:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-11 06:38 UTC, AIBarabanshchikova commented
🍏

2018-10-11 06:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 17:03 UTC, AIBarabanshchikova commented
🍏

2018-10-16 14:26 UTC, ASchibrikova commented
🔔

2018-10-19 13:34 UTC, mokhov approved these changes

2018-10-19 13:34 UTC, mokhov commented on index.html
> +    <form class="form">
Но было-то вообще всё

2018-10-19 13:34 UTC, mokhov commented
Отлично!

2018-10-19 13:34 UTC, closed without merging