Крячко Григорий
urfu-2018/markup-task-1 pull request #80
Opened 2018-10-14 09:02 UTC by GrigoryEien

2018-10-14 09:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 09:12 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 09:14 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 09:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 11:40 UTC, mokhov requested changes
🍅

2018-10-19 11:40 UTC, mokhov commented on index.html
> +        </label>На почту<br>
А почему текст не внутри label?

2018-10-19 11:40 UTC, mokhov commented on index.html
> +         alt="yandex logo" width="100">
Почему нет ```height```?

2018-10-19 13:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 05:33 UTC, closed without merging