Серов Егор
urfu-2018/markup-task-1 pull request #81
Opened 2018-10-14 09:36 UTC by Jueblack

2018-10-14 09:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 09:49 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 09:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 10:02 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 10:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 10:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 18:02 UTC, chrighter requested changes
🍅

2018-10-14 18:02 UTC, chrighter commented on index.html
> +        Ваше имя <input type="text" required="" placeholder="Имя">
Просто `required`

2018-10-14 18:02 UTC, chrighter commented on index.html
> +        Телефон &nbsp; <input type="tel"  placeholder="89990007766" required>
Давай добавим валидацию

2018-10-14 18:02 UTC, chrighter commented on index.html
> +        <input type="checkbox">на почту <br>
Давай добавим возможность выбора `checkbox` по нажатию на текст (`на почту` или `на телефон`)

2018-10-14 18:02 UTC, chrighter commented on index.html
> +    <img src="yalogo.jpg" title="logo" alt="image yandex logo" >
А где картинка?)

2018-10-14 18:02 UTC, chrighter commented on index.html
> +    <a href="https://yandex.ru/support/">Пожаловаться</a> &copy;2018 <a href="https://yandex.ru">Яндекс</a>
👍 за /support

2018-10-14 18:02 UTC, chrighter commented on index.html
> +    Вы подписались на уведомление о новостях Яндекса.
Давай напишем как в макете - уведомлениЯ

2018-10-14 18:02 UTC, chrighter commented on index.html
> +<p>
На будущее: для верстки писем лучше использовать табличную верстку - это залог того, что верстка "не разъедется" ни в одном почтовом клиенте

Подробнее можно посмотреть здесь: https://habr.com/post/252279/

2018-10-14 18:02 UTC, chrighter commented on index.html
> +    <a href="https://yandex.ru/support/">Пожаловаться</a> &copy;2018 <a href="https://yandex.ru">Яндекс</a>
В макете `Пожаловаться` написано слева, а копирайт - справа

Давай сделаем так же

2018-10-14 18:02 UTC, chrighter commented on index.html
> +        Email  <input type="email" placeholder="email@yandex.ru" required="" >
После сабмита происходит отправка данных формы на сервер в виде `name1=value1&name2=value2&...`, где `valueN` - это значение атрибута `value` в случае `checkbox` или введенное в поле ввода значение, а `nameN` - то, что для данного `input` записано в атрибут name

Поэтому давай еще добавим атрибуты `name` и `value` во все `input`

2018-10-15 10:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:36 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 11:48 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 12:04 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 12:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 12:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 13:06 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 13:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 16:04 UTC, chrighter requested changes
🍅 

Ты молодец, осталось немного!)

2018-10-16 16:04 UTC, chrighter commented on index.html
> +    <tr>
Давай чтобы было более семантично, будем использовать `tbody` и `tfoot`

2018-10-16 16:04 UTC, chrighter commented on index.html
> +        <label><input type="checkbox" value="на почту">на почту</label> <br>
👍 за то, что галочки в `checkbox` ставятся даже по нажатию на текст

2018-10-16 16:04 UTC, chrighter commented on index.html
> +        Ваше имя <input type="text" name="name" required value="Имя">
Давай сделаем так, чтобы при фокусе на `input` текст в нем сам пропадал, сейчас приходится удалять его ручками, прежде чем что-то вводить

2018-10-16 16:04 UTC, chrighter commented on index.html
> +        <td><img src="http://pokupkivinternete.ru/poleznye-sovety/img/50126.jpg"
Сейчас у тебя картинка располагается на одном уровне со вторым абцазем
Давай будем располагать картинку как в макете - на одном уровне с первым и вторым абзацем

2018-10-17 07:49 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 07:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 08:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 15:54 UTC, chrighter approved these changes
🍏 молодец!

2018-10-17 15:55 UTC, closed without merging