Раджабов Роман
urfu-2018/markup-task-1 pull request #82
Opened 2018-10-14 10:13 UTC by RadzhabovRoman

2018-10-14 10:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 17:07 UTC, spt30 requested changes
🍅

2018-10-14 17:07 UTC, spt30 commented on index.html
> +    <article>
Респект за уместное использование ```<article>``` 👍

2018-10-14 17:07 UTC, spt30 commented on index.html
> +        <header>
Лишний ```<header>```, давай просто ```<h1>``` оставим

2018-10-14 17:07 UTC, spt30 commented on index.html
> +            <br><br>
Зачем тут два ```<br>```, еще и на одной строке?

2018-10-14 17:07 UTC, spt30 commented on index.html
> +            <label>Ваше имя <input type="text" placeholder="Имя" required></label>
давай делать переносы, чтобы читабельнее было:
```
<label>
    Ваше имя
    <input type="text" placeholder="Имя" required>
</label>
```

2018-10-14 17:07 UTC, spt30 commented on index.html
> +        <hr>
```<hr>``` не относится к контенту футера

2018-10-14 17:07 UTC, spt30 commented on index.html
> +        <img
письмо выглядет вовсе не как на макете, картинка должна быть справа от текста

2018-10-16 12:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 17:22 UTC, RadzhabovRoman commented
Я заккомитил исправления без комментария, поэтому наверное лучше здесь оставить комментарий по этому поводу.

2018-10-18 16:36 UTC, spt30 approved these changes
👍 четко

2018-10-18 16:38 UTC, spt30 commented
🍏

P.S. не знаю, как с другими менторами, мне пока бессмыслено что-то писать не в личку
захожу, когда появляется время и смотрю всех в хронологическом порядке

2018-10-18 16:38 UTC, closed without merging