Дерендеева Анастасия
urfu-2018/markup-task-1 pull request #84
Opened 2018-10-14 10:52 UTC by DerendeevaNastya

2018-10-14 10:53 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 11:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 11:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 11:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 11:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 12:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 12:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 12:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 12:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-15 11:50 UTC, nex2hex requested changes
🍅

2018-10-15 11:50 UTC, nex2hex commented on index.html
> +        Ваше имя<input type="text" name="firstname" placeholder="Имя" required><br><br>
Текст "Ваше имя" должен быть внутри label, чтобы при клике по нему курсор помещался в поле ввода

2018-10-15 11:50 UTC, nex2hex commented on index.html
> +        <input name="checkEmail" type="checkbox" value="email">на почту<br>
и тут

2018-10-16 17:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 10:19 UTC, nex2hex commented on index.html
> +        <label for="name">Ваше имя</label><input type="text" id="name" placeholder="Имя"
так проще
`<label>Ваше имя<input type="text" placeholder="Имя"></label>`

и не надо idшники придумывать

2018-10-17 10:19 UTC, closed without merging