Холкин Антон Николаевич
urfu-2018/markup-task-1 pull request #89
Opened 2018-10-14 12:42 UTC by hukopo

2018-10-14 12:43 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 12:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 12:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-15 16:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 17:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 12:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-18 17:49 UTC, spt30 requested changes
Запарился-запарился)))
Но есть небольшие недочеты

2018-10-18 17:49 UTC, spt30 commented on index.html
> +    <div class="sub text">
очень много дивов, есть более семантичные теги
это как раз та самая задача, где все надо сделать семантично и разобраться

2018-10-18 17:49 UTC, spt30 commented on index.html
> +    <div class="sub text">
не сокращай названия классов

2018-10-18 17:49 UTC, spt30 commented on index.css
> +    color: #ccc;
![image](https://user-images.githubusercontent.com/31798669/47173390-5e0e9780-d327-11e8-8ad9-980e7114b8af.png)
что-то пошло не так

2018-10-18 17:49 UTC, spt30 commented on index.html
> +        <img class="letterImage" src="./ya.png" alt="yandex img not found">
классы не принято писать в camelCase, пиши через землю (snake_case) или тире (kebab-case)

2018-10-18 17:49 UTC, spt30 commented on index.html
> +                <input placeholder=" Имя" type="text">
не пиши так плейсхолдер, лучше сделай паддинг с помощью css

2018-10-18 20:29 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 09:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 10:53 UTC, spt30 approved these changes
Обычно `<section>` вкладывают в `<article>`, а не наоборот

2018-10-20 10:54 UTC, spt30 commented
🍏 я запомнил, что ты умеешь верстать и любишь себя загружать
Поэтому дальше буду доставать))

2018-10-20 10:54 UTC, closed without merging