Пылаев Владимир КБ-301
urfu-2018/markup-task-1 pull request #91
Opened 2018-10-14 13:13 UTC by Jamboba

2018-10-14 13:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 12:51 UTC, Jamboba commented
🔔

2018-10-18 19:14 UTC, spt30 requested changes
Слишком плоский код, все лежит ровно и не семантично
В лекции было много тегов различных, ими удобно пользоваться и создавать грамотную разметку
чтобы визуально было понятно

тут сходу видно минимум два `<article>`, два `<ul>`

2018-10-18 19:14 UTC, spt30 commented on index.html
> +    <form>
Форма – это то, что нужно заполнять, то есть все инпуты, чекбоксы и кнопочка
Остальное к форме не относится

2018-10-18 19:14 UTC, spt30 commented on index.html
> +        <p>Ваше имя <input type="text" name="name" placeholder="Имя"></p>
это не параграфы, это часть списка (список полей для заполнения)

2018-10-18 19:14 UTC, spt30 commented on index.html
> +        <p>Ваше имя <input type="text" name="name" placeholder="Имя"></p>
из-за того, что название поля не обернуто в `<label>`, нельзя кликнуть на название и попасть сразу в `<input>`

2018-10-18 19:14 UTC, spt30 commented on index.html
> +        <input type="checkbox">На почту<br>
тоже список и тоже label нет

2018-10-18 19:14 UTC, spt30 commented on index.html
> +            <p>Здраствуйте, Николай! <img src="ya.png" alt="yandex logo"></p>
плохая вставка изображения
хотелось бы, чтобы было расположение как на макете

2018-10-18 19:14 UTC, spt30 commented on index.html
> +            <p></p>
не надо так:(
параграф не для этого придумали, верстка должна быть семантичной

2018-10-18 19:14 UTC, spt30 commented on index.html
> +        <p>
не параграф

2018-10-20 08:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 11:03 UTC, spt30 requested changes
"ну кисонька, ну еще капельку"!

2018-10-20 11:03 UTC, spt30 commented on index.html
> +        <form>
так и не поправил(
заголовок к форме не относится

2018-10-20 11:03 UTC, spt30 commented on index.html
> +            Хочу получать уведомления:
тоже бы во что-нибудь обернуть
Представь, что ты хочешь на этот текст наложить стили
В какой бы тег ты обернул? Вот в такой и оберни)

2018-10-20 11:03 UTC, spt30 commented on index.html
> +                        <hr>
Крутая вложенность
Очень ровно легла линия, молодец!

2018-10-20 11:03 UTC, spt30 commented on index.html
> +                </tr></tfoot>
тут перенос забыл:(

2018-10-20 12:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 06:58 UTC, Jamboba commented
🔔 Сергей, я призываю тебя, сними с меня эту головную боль

2018-10-22 16:45 UTC, spt30 commented
🍏теперь молодец)

2018-10-22 16:45 UTC, closed without merging