Анисимов Данил
urfu-2018/markup-task-1 pull request #93
Opened 2018-10-14 13:24 UTC by frosthamster

[Посмотреть решение](https://hruview.herokuapp.com/frosthamster/markup-task-1/master/index.html)

2018-10-14 13:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 14:30 UTC, SemyonMakhaev requested changes
🍅 

Данил, привет! Спасибо за пулл реквест!
Молодец, что используешь семантичные теги 👍 Есть несколько замечаний

Если будут вопросы, пиши мне в слаке)

2018-10-14 14:30 UTC, SemyonMakhaev commented on index.html
> +        <input id="name" placeholder="Имя" required><br>
Можно сгруппировать инпуты и соответствующие им лейблы в блочные элементы, чтобы было удобнее потом их стилизовать

2018-10-14 14:30 UTC, SemyonMakhaev commented on index.html
> +        <input id="email" type="email" placeholder="email@gmail.com" required><br>
Тебе здесь точно нужен тег `br`? Не будет ли удачнее реализовать отступы при помощи стилей?

2018-10-14 14:30 UTC, SemyonMakhaev commented on index.html
> +        <input id="phone" type="tel" pattern="8[0-9]{10}" placeholder="89990007766" required><br>
Можно в шаблоне использовать `\d`

2018-10-14 14:30 UTC, SemyonMakhaev commented on index.html
> +        <input id="phone" type="tel" pattern="8[0-9]{10}" placeholder="89990007766" required><br>
Давай также поддержим городские (семизначные) номера телефонов

2018-10-14 14:30 UTC, SemyonMakhaev commented on index.html
> +        <button>Подписаться</button>
Чтобы данные из формы при нажатии на кнопку отправлялись на сервер, можно добавить у кнопки атрибут `type` со значением `submit`

2018-10-14 14:30 UTC, SemyonMakhaev commented on index.html
> +    <table>
Табличная вёрстка используется в первую очередь для создания таблиц. Для создания интерфейсов с сетчатой структурой таблицы использовать не рекомендуется, лучше добиться того же эффекта при помощи стилей. Попробуй использовать более подходящие теги.

Хотя для обеспечения совместимости с очень старыми браузерами, где новые технологии не поддерживаются, табличная вёрстка используется в качестве альтернативы и по сей день 😅

2018-10-14 14:30 UTC, SemyonMakhaev commented on index.html
> +                <img width="170" height="100" alt="яндекс"
Для картинок нужно также обязательно всегда указывать атрибут [title](http://htmlbook.ru/html/attr/title). Это необходимо для обеспечения доступности

2018-10-14 14:30 UTC, SemyonMakhaev commented on index.html
> +            <td>Для подтверждения перейдите по <a href="">ссылке</a></td>
Зачем пустой атрибут `href`?

2018-10-14 14:30 UTC, SemyonMakhaev commented on index.html
> +            <td><a href="">Пожаловаться</a></td>
Аналогично про `href`

2018-10-14 14:30 UTC, SemyonMakhaev commented on index.html
> +            <td>© 2018, <a href="https://yandex.com">Яндекс</a></td>
Вместо символа `©` используй `&copy;`, иначе твой html будет невалиден

2018-10-14 14:33 UTC, SemyonMakhaev commented
Отдельный респект, если добавишь стилей, чтобы интерфейс получился, как на макете 😃 

![2015_06_10_12_06_35_79b56615ad6b75a28352dc50425e6c19](https://user-images.githubusercontent.com/18099714/46916579-faf2cd00-cfd5-11e8-95c4-d7951f13b8ef.jpg)

2018-10-14 16:11 UTC, frosthamster commented on index.html
> +        <input id="email" type="email" placeholder="email@gmail.com" required><br>
насколько я понял, в этой задаче не нужно было использовать css, только чистый html
https://yandex-urfu.slack.com/archives/C0B5UNFSA/p1539176402000100

2018-10-14 16:14 UTC, frosthamster commented on index.html
> +    <table>
на лекции сказали, сверстать на табличках
мне переделать на нормальную верстку?

2018-10-14 16:14 UTC, frosthamster commented on index.html
> +            <td>Для подтверждения перейдите по <a href="">ссылке</a></td>
по идее, там должна быть ссылка, но я не знал, что туда вставлять

2018-10-14 18:38 UTC, SemyonMakhaev commented on index.html
> +        <input id="email" type="email" placeholder="email@gmail.com" required><br>
Всё верно. Это исключительно по твоему желанию. Я зачту задачу и без стилей, только с правками `html`

2018-10-14 18:44 UTC, SemyonMakhaev commented on index.html
> +    <table>
Раз на лекции сказали, можно оставить так. Для вёрстки писем это приемлемо. Главное, чтобы ты понимал, в каких случаях применима табличная вёрстка, а в каких нет 😄

2018-10-16 21:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 21:51 UTC, frosthamster commented
🍏

2018-10-20 13:28 UTC, SemyonMakhaev commented
👍

2018-10-20 13:28 UTC, closed without merging