Плаксин Иван
urfu-2018/markup-task-1 pull request #95
Opened 2018-10-14 13:39 UTC by ZeroNetto

2018-10-14 13:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 13:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 13:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-18 04:40 UTC, chrighter requested changes
🍅

2018-10-18 04:40 UTC, chrighter commented on index.html
> +                    уведомления на почту и телефон
Этот контент можно вынести за пределы формы, так как он не относится к ней

2018-10-18 04:40 UTC, chrighter commented on index.html
> +                            <input name="name" placeholder="Имя" required="" pattern="[A-Za-zА-Яа-яЁё]+">
Просто `required`

2018-10-18 04:40 UTC, chrighter commented on index.html
> +                <table>
Табличную верстку применяют как правило только для верстки писем

2018-10-18 04:40 UTC, chrighter commented on index.html
> +                        <td><input type="checkbox" id="onMail"></td>
Давай сделаем так, что галочка в `checkbox` будет ставиться даже по нажатию просто на текст (`На почту` или `На телефон`), это удобно, например когда заполняешь форму с мобильного

2018-10-18 04:40 UTC, chrighter commented on index.html
> +        <article>
Для верстки писем лучше использовать табличную верстку - это залог того, что верстка "не разъедется" ни в одном почтовом клиенте

Подробнее можно посмотреть здесь: https://habr.com/post/252279/

2018-10-18 04:40 UTC, chrighter commented on index.html
> +                <img src="https://vistanews.ru/uploads/posts/2018-02/1518446023_315988009.jpg"
Давай будем располагать картинку на как на макете

2018-10-18 04:40 UTC, chrighter commented on index.html
> +        <footer>
Давай содержимое футера тоже расположим как на макете

2018-10-18 04:40 UTC, chrighter commented on index.html
> +                            required="" pattern="[0-9]{11}">
👍 за валидацию

2018-10-18 04:40 UTC, chrighter commented on index.html
> +                        <td><input type="checkbox" id="onTel"></td>
После сабмите происходит отправка данных формы на сервер в виде `name1=value1&name2=value2&...`, где `valueN` - это значение атрибута `value` в случае `checkbox` или введенное в поле ввода значение, а `nameN` - то, что для данного `input` записано в атрибут `name`

Поэтому давай еще добавим атрибуты `name`и `value` там, где необходимо

2018-10-20 17:13 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-20 17:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 09:29 UTC, chrighter requested changes
🍅

2018-10-21 09:29 UTC, chrighter commented on index.html
> +                <pre>
Зачем для этого контента `pre`?

2018-10-21 09:29 UTC, chrighter commented on index.html
> +            <h2>Хочу подписаться!</h2>
Почему используешь `h2`, если не использовал ранее на странице `h1`?

2018-10-21 09:29 UTC, chrighter commented on index.html
> +        <table>
👍

2018-10-21 09:29 UTC, chrighter commented on index.html
> +                <td rowspan="2">
👍

2018-10-21 09:29 UTC, chrighter commented on index.html
> +                    width="200" alt="Яндекс">
Слишком общий `alt`, давай назовем конкретнее

2018-10-21 09:29 UTC, chrighter commented on index.html
> +            <tr>
Давай разделим контент на `tbody` и `tfoot`

2018-10-21 12:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 17:43 UTC, chrighter requested changes
Совсем чуть-чуть осталось
🍅

2018-10-21 17:43 UTC, chrighter commented on index.html
> +                    <td>©2018,<a href="https://www.yandex.ru/">Яндекс</a></td>
Давай копирайт спецсимволом сделаем

2018-10-21 18:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-21 18:38 UTC, chrighter reviewed
🍏

2018-10-21 18:38 UTC, chrighter approved these changes
🍏

2018-10-21 18:38 UTC, closed without merging