Денисов Андрей
urfu-2018/markup-task-1 pull request #96
Opened 2018-10-14 13:53 UTC by AndyDen98

2018-10-14 13:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 09:58 UTC, dotokoto requested changes

2018-10-16 09:58 UTC, Dotokoto commented on index.html
> +            <p>Ваше имя<input name="name" placeholder="Имя" required=""></p>
Есть тег `label` специально для подписей к полям

2018-10-16 09:58 UTC, Dotokoto commented on index.html
> +            <p>Email<input type="email" placeholder="email@yandex.ru" required=""></p>
Можно писать просто `required`

2018-10-16 09:58 UTC, Dotokoto commented on index.html
> +        <img src="yandex.gif" width="200" alt="image" id="picture">
`alt` неинформативный. Что за `image`? По описанию непонятно

2018-10-16 09:58 UTC, Dotokoto commented on index.html
> +        <img src="yandex.gif" width="200" alt="image" id="picture">
И для чего `id` этому тегу?

2018-10-18 19:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 09:57 UTC, closed without merging