Белоруссова Юлия
urfu-2018/markup-task-1 pull request #98
Opened 2018-10-14 14:40 UTC by JulieBlack666

2018-10-14 14:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 15:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 13:32 UTC, mokhov commented on index.html
> +            <p>Ваше имя	<input type="text" placeholder="Имя" size="50"></p>
Хорошо бы связать текст «Ваше имя» и ```<input>``` для этого можно обернуть всё в ```<label>```, например

2018-10-19 13:33 UTC, mokhov requested changes
Нужно доделать 🍅

2018-10-19 13:33 UTC, mokhov commented on index.html
> +    <form>
Зачем здесь тег формы?

2018-10-21 09:53 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 09:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 05:31 UTC, closed without merging